package com.yly.presscard;

import com.eis.util.CheckUtil;
import com.yly.presscard.Presscardapptb;
import com.yly.presscard.PresscardapptbExample;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class PresscardapptbDAOImpl extends SqlMapClientDaoSupport implements PresscardapptbDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table presscardapptb
     *
     * @ibatorgenerated Wed Mar 09 20:23:53 CST 2016
     */
    public PresscardapptbDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table presscardapptb
     *
     * @ibatorgenerated Wed Mar 09 20:23:53 CST 2016
     */
    public int countByExample(PresscardapptbExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("presscardapptb.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table presscardapptb
     *
     * @ibatorgenerated Wed Mar 09 20:23:53 CST 2016
     */
    public int deleteByExample(PresscardapptbExample example) {
        int rows = getSqlMapClientTemplate().delete("presscardapptb.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table presscardapptb
     *
     * @ibatorgenerated Wed Mar 09 20:23:53 CST 2016
     */
    public void insert(Presscardapptb record) {
    	String namespace="ibatorgenerated_insert";
    	if(CheckUtil.isEmptry(record.getCardType()))
    		namespace="ibatorgenerated_insertEreader";
        getSqlMapClientTemplate().insert("presscardapptb."+namespace, record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table presscardapptb
     *
     * @ibatorgenerated Wed Mar 09 20:23:53 CST 2016
     */
    public void insertSelective(Presscardapptb record) {
        getSqlMapClientTemplate().insert("presscardapptb.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table presscardapptb
     *
     * @ibatorgenerated Wed Mar 09 20:23:53 CST 2016
     */
    public List selectByExample(PresscardapptbExample example) {
        List list = getSqlMapClientTemplate().queryForList("presscardapptb.ibatorgenerated_selectByExample", example);
        return list;
    }
    public List selectEreaderByExample(PresscardapptbExample example) {
        List list = getSqlMapClientTemplate().queryForList("presscardapptb.ibatorgenerated_selectEreaderByExample", example);
        return list;
    }
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table presscardapptb
     *
     * @ibatorgenerated Wed Mar 09 20:23:53 CST 2016
     */
    public int updateByExampleSelective(Presscardapptb record, PresscardapptbExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("presscardapptb.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table presscardapptb
     *
     * @ibatorgenerated Wed Mar 09 20:23:53 CST 2016
     */
    public int updateByExample(Presscardapptb record, PresscardapptbExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("presscardapptb.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table presscardapptb
     *
     * @ibatorgenerated Wed Mar 09 20:23:53 CST 2016
     */
    private static class UpdateByExampleParms extends PresscardapptbExample {
        private Object record;

        public UpdateByExampleParms(Object record, PresscardapptbExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    public void insertCard(Presscardapptb p) {
    	
        getSqlMapClientTemplate().insert("presscardapptb.ibatorgenerated_insertcard", p);
    }
    public List selectCardByExample(PresscardapptbExample example) {
        List list = getSqlMapClientTemplate().queryForList("presscardapptb.getCardListBySql", example);
        return list;
    }
    public List getReport(PresscardapptbExample example) {
        List list = getSqlMapClientTemplate().queryForList("presscardapptb.getReport", example);
        return list;
    }    
    
}