package com.yly.info;

import com.yly.info.Biunitinfotb;
import com.yly.info.BiunitinfotbExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class BiunitinfotbDAOImpl extends SqlMapClientDaoSupport implements BiunitinfotbDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biunitinfotb
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public BiunitinfotbDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biunitinfotb
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public int countByExample(BiunitinfotbExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("biunitinfotb.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biunitinfotb
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public int deleteByExample(BiunitinfotbExample example) {
        int rows = getSqlMapClientTemplate().delete("biunitinfotb.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biunitinfotb
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public int deleteByPrimaryKey(Integer unitid) {
        Biunitinfotb key = new Biunitinfotb();
        key.setUnitid(unitid);
        int rows = getSqlMapClientTemplate().delete("biunitinfotb.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biunitinfotb
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public void insert(Biunitinfotb record) {
        getSqlMapClientTemplate().insert("biunitinfotb.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biunitinfotb
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public void insertSelective(Biunitinfotb record) {
        getSqlMapClientTemplate().insert("biunitinfotb.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biunitinfotb
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public List selectByExample(BiunitinfotbExample example) {
        List list = getSqlMapClientTemplate().queryForList("biunitinfotb.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biunitinfotb
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public Biunitinfotb selectByPrimaryKey(Integer unitid) {
        Biunitinfotb key = new Biunitinfotb();
        key.setUnitid(unitid);
        Biunitinfotb record = (Biunitinfotb) getSqlMapClientTemplate().queryForObject("biunitinfotb.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biunitinfotb
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public int updateByExampleSelective(Biunitinfotb record, BiunitinfotbExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("biunitinfotb.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biunitinfotb
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public int updateByExample(Biunitinfotb record, BiunitinfotbExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("biunitinfotb.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biunitinfotb
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public int updateByPrimaryKeySelective(Biunitinfotb record) {
        int rows = getSqlMapClientTemplate().update("biunitinfotb.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biunitinfotb
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public int updateByPrimaryKey(Biunitinfotb record) {
        int rows = getSqlMapClientTemplate().update("biunitinfotb.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table biunitinfotb
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    private static class UpdateByExampleParms extends BiunitinfotbExample {
        private Object record;

        public UpdateByExampleParms(Object record, BiunitinfotbExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}