package com.yly.info;

public class Biunitinfotb {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biunitinfotb.Unitid
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    private Integer unitid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biunitinfotb.Hyid
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    private Short hyid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biunitinfotb.HyName
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    private String hyName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biunitinfotb.Unittype
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    private Short unittype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biunitinfotb.Unitstat
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    private Short unitstat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biunitinfotb.Unitdes
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    private String unitdes;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biunitinfotb.Chnshort
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    private String chnshort;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biunitinfotb.unitperson
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    private String unitperson;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biunitinfotb.Unittel
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    private String unittel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biunitinfotb.Unitaddr
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    private String unitaddr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biunitinfotb.unittestflag
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    private String unittestflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biunitinfotb.LeadStore
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    private Integer leadStore;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biunitinfotb.Unitlevel
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    private String unitlevel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biunitinfotb.rsvd
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    private String rsvd;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biunitinfotb.Unitid
     *
     * @return the value of biunitinfotb.Unitid
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public Integer getUnitid() {
        return unitid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biunitinfotb.Unitid
     *
     * @param unitid the value for biunitinfotb.Unitid
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public void setUnitid(Integer unitid) {
        this.unitid = unitid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biunitinfotb.Hyid
     *
     * @return the value of biunitinfotb.Hyid
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public Short getHyid() {
        return hyid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biunitinfotb.Hyid
     *
     * @param hyid the value for biunitinfotb.Hyid
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public void setHyid(Short hyid) {
        this.hyid = hyid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biunitinfotb.HyName
     *
     * @return the value of biunitinfotb.HyName
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public String getHyName() {
        return hyName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biunitinfotb.HyName
     *
     * @param hyName the value for biunitinfotb.HyName
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public void setHyName(String hyName) {
        this.hyName = hyName == null ? null : hyName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biunitinfotb.Unittype
     *
     * @return the value of biunitinfotb.Unittype
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public Short getUnittype() {
        return unittype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biunitinfotb.Unittype
     *
     * @param unittype the value for biunitinfotb.Unittype
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public void setUnittype(Short unittype) {
        this.unittype = unittype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biunitinfotb.Unitstat
     *
     * @return the value of biunitinfotb.Unitstat
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public Short getUnitstat() {
        return unitstat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biunitinfotb.Unitstat
     *
     * @param unitstat the value for biunitinfotb.Unitstat
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public void setUnitstat(Short unitstat) {
        this.unitstat = unitstat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biunitinfotb.Unitdes
     *
     * @return the value of biunitinfotb.Unitdes
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public String getUnitdes() {
        return unitdes;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biunitinfotb.Unitdes
     *
     * @param unitdes the value for biunitinfotb.Unitdes
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public void setUnitdes(String unitdes) {
        this.unitdes = unitdes == null ? null : unitdes.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biunitinfotb.Chnshort
     *
     * @return the value of biunitinfotb.Chnshort
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public String getChnshort() {
        return chnshort;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biunitinfotb.Chnshort
     *
     * @param chnshort the value for biunitinfotb.Chnshort
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public void setChnshort(String chnshort) {
        this.chnshort = chnshort == null ? null : chnshort.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biunitinfotb.unitperson
     *
     * @return the value of biunitinfotb.unitperson
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public String getUnitperson() {
        return unitperson;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biunitinfotb.unitperson
     *
     * @param unitperson the value for biunitinfotb.unitperson
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public void setUnitperson(String unitperson) {
        this.unitperson = unitperson == null ? null : unitperson.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biunitinfotb.Unittel
     *
     * @return the value of biunitinfotb.Unittel
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public String getUnittel() {
        return unittel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biunitinfotb.Unittel
     *
     * @param unittel the value for biunitinfotb.Unittel
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public void setUnittel(String unittel) {
        this.unittel = unittel == null ? null : unittel.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biunitinfotb.Unitaddr
     *
     * @return the value of biunitinfotb.Unitaddr
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public String getUnitaddr() {
        return unitaddr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biunitinfotb.Unitaddr
     *
     * @param unitaddr the value for biunitinfotb.Unitaddr
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public void setUnitaddr(String unitaddr) {
        this.unitaddr = unitaddr == null ? null : unitaddr.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biunitinfotb.unittestflag
     *
     * @return the value of biunitinfotb.unittestflag
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public String getUnittestflag() {
        return unittestflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biunitinfotb.unittestflag
     *
     * @param unittestflag the value for biunitinfotb.unittestflag
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public void setUnittestflag(String unittestflag) {
        this.unittestflag = unittestflag == null ? null : unittestflag.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biunitinfotb.LeadStore
     *
     * @return the value of biunitinfotb.LeadStore
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public Integer getLeadStore() {
        return leadStore;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biunitinfotb.LeadStore
     *
     * @param leadStore the value for biunitinfotb.LeadStore
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public void setLeadStore(Integer leadStore) {
        this.leadStore = leadStore;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biunitinfotb.Unitlevel
     *
     * @return the value of biunitinfotb.Unitlevel
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public String getUnitlevel() {
        return unitlevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biunitinfotb.Unitlevel
     *
     * @param unitlevel the value for biunitinfotb.Unitlevel
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public void setUnitlevel(String unitlevel) {
        this.unitlevel = unitlevel == null ? null : unitlevel.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biunitinfotb.rsvd
     *
     * @return the value of biunitinfotb.rsvd
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public String getRsvd() {
        return rsvd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biunitinfotb.rsvd
     *
     * @param rsvd the value for biunitinfotb.rsvd
     *
     * @ibatorgenerated Fri Mar 25 15:05:16 CST 2016
     */
    public void setRsvd(String rsvd) {
        this.rsvd = rsvd == null ? null : rsvd.trim();
    }
    public String getOperId() {
 		return operId;
 	}

 	public void setOperId(String operId) {
 		this.operId = operId;
 	}

 	public String getCurrDate() {
 		return currDate;
 	}

 	public void setCurrDate(String currDate) {
 		this.currDate = currDate;
 	}


 	private String operId;

   	private String currDate;

}