package com.blue.userdepartauth;

import com.blue.userdepartauth.UserDepartAuth;
import com.blue.userdepartauth.UserDepartAuthExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UserDepartAuthDAOImpl extends SqlMapClientDaoSupport implements UserDepartAuthDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_depart_auth
     *
     * @ibatorgenerated Mon Mar 17 16:40:14 CST 2014
     */
    public UserDepartAuthDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_depart_auth
     *
     * @ibatorgenerated Mon Mar 17 16:40:14 CST 2014
     */
    public int countByExample(UserDepartAuthExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("user_depart_auth.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_depart_auth
     *
     * @ibatorgenerated Mon Mar 17 16:40:14 CST 2014
     */
    public int deleteByExample(UserDepartAuthExample example) {
        int rows = getSqlMapClientTemplate().delete("user_depart_auth.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_depart_auth
     *
     * @ibatorgenerated Mon Mar 17 16:40:14 CST 2014
     */
    public int deleteByPrimaryKey(Long id) {
        UserDepartAuth key = new UserDepartAuth();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("user_depart_auth.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_depart_auth
     *
     * @ibatorgenerated Mon Mar 17 16:40:14 CST 2014
     */
    public void insert(UserDepartAuth record) {
        getSqlMapClientTemplate().insert("user_depart_auth.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_depart_auth
     *
     * @ibatorgenerated Mon Mar 17 16:40:14 CST 2014
     */
    public void insertSelective(UserDepartAuth record) {
        getSqlMapClientTemplate().insert("user_depart_auth.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_depart_auth
     *
     * @ibatorgenerated Mon Mar 17 16:40:14 CST 2014
     */
    public List selectByExample(UserDepartAuthExample example) {
        List list = getSqlMapClientTemplate().queryForList("user_depart_auth.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_depart_auth
     *
     * @ibatorgenerated Mon Mar 17 16:40:14 CST 2014
     */
    public UserDepartAuth selectByPrimaryKey(Long id) {
        UserDepartAuth key = new UserDepartAuth();
        key.setId(id);
        UserDepartAuth record = (UserDepartAuth) getSqlMapClientTemplate().queryForObject("user_depart_auth.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_depart_auth
     *
     * @ibatorgenerated Mon Mar 17 16:40:14 CST 2014
     */
    public int updateByExampleSelective(UserDepartAuth record, UserDepartAuthExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("user_depart_auth.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_depart_auth
     *
     * @ibatorgenerated Mon Mar 17 16:40:14 CST 2014
     */
    public int updateByExample(UserDepartAuth record, UserDepartAuthExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("user_depart_auth.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_depart_auth
     *
     * @ibatorgenerated Mon Mar 17 16:40:14 CST 2014
     */
    public int updateByPrimaryKeySelective(UserDepartAuth record) {
        int rows = getSqlMapClientTemplate().update("user_depart_auth.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_depart_auth
     *
     * @ibatorgenerated Mon Mar 17 16:40:14 CST 2014
     */
    public int updateByPrimaryKey(UserDepartAuth record) {
        int rows = getSqlMapClientTemplate().update("user_depart_auth.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table user_depart_auth
     *
     * @ibatorgenerated Mon Mar 17 16:40:14 CST 2014
     */
    private static class UpdateByExampleParms extends UserDepartAuthExample {
        private Object record;

        public UpdateByExampleParms(Object record, UserDepartAuthExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}