package com.blue.version.updatestep;

import com.blue.version.updatestep.UpdateStep;
import com.blue.version.updatestep.UpdateStepExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UpdateStepDAOImpl extends SqlMapClientDaoSupport implements UpdateStepDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table update_step
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public UpdateStepDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table update_step
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int countByExample(UpdateStepExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("update_step.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table update_step
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int deleteByExample(UpdateStepExample example) {
        int rows = getSqlMapClientTemplate().delete("update_step.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table update_step
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int deleteByPrimaryKey(Long id) {
        UpdateStep key = new UpdateStep();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("update_step.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table update_step
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void insert(UpdateStep record) {
        getSqlMapClientTemplate().insert("update_step.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table update_step
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void insertSelective(UpdateStep record) {
        getSqlMapClientTemplate().insert("update_step.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table update_step
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public List selectByExample(UpdateStepExample example) {
        List list = getSqlMapClientTemplate().queryForList("update_step.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table update_step
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public UpdateStep selectByPrimaryKey(Long id) {
        UpdateStep key = new UpdateStep();
        key.setId(id);
        UpdateStep record = (UpdateStep) getSqlMapClientTemplate().queryForObject("update_step.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table update_step
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int updateByExampleSelective(UpdateStep record, UpdateStepExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("update_step.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table update_step
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int updateByExample(UpdateStep record, UpdateStepExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("update_step.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table update_step
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int updateByPrimaryKeySelective(UpdateStep record) {
        int rows = getSqlMapClientTemplate().update("update_step.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table update_step
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int updateByPrimaryKey(UpdateStep record) {
        int rows = getSqlMapClientTemplate().update("update_step.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table update_step
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private static class UpdateByExampleParms extends UpdateStepExample {
        private Object record;

        public UpdateByExampleParms(Object record, UpdateStepExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}