package com.blue.version.updatestep;

public class UpdateStep {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column update_step.ID
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column update_step.STEP
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private Integer step;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column update_step.MEMO
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private String memo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column update_step.VERSION_ID
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private String versionId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column update_step.ID
     *
     * @return the value of update_step.ID
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column update_step.ID
     *
     * @param id the value for update_step.ID
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column update_step.STEP
     *
     * @return the value of update_step.STEP
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public Integer getStep() {
        return step;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column update_step.STEP
     *
     * @param step the value for update_step.STEP
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void setStep(Integer step) {
        this.step = step;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column update_step.MEMO
     *
     * @return the value of update_step.MEMO
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column update_step.MEMO
     *
     * @param memo the value for update_step.MEMO
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column update_step.VERSION_ID
     *
     * @return the value of update_step.VERSION_ID
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public String getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column update_step.VERSION_ID
     *
     * @param versionId the value for update_step.VERSION_ID
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void setVersionId(String versionId) {
        this.versionId = versionId == null ? null : versionId.trim();
    }
}