package com.blue.projectfiles;

import com.blue.projectfiles.ProjectFiles;
import com.blue.projectfiles.ProjectFilesExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ProjectFilesDAOImpl extends SqlMapClientDaoSupport implements ProjectFilesDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table project_files
     *
     * @ibatorgenerated Wed Mar 27 15:38:43 CST 2013
     */
    public ProjectFilesDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table project_files
     *
     * @ibatorgenerated Wed Mar 27 15:38:43 CST 2013
     */
    public int countByExample(ProjectFilesExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("project_files.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table project_files
     *
     * @ibatorgenerated Wed Mar 27 15:38:43 CST 2013
     */
    public int deleteByExample(ProjectFilesExample example) {
        int rows = getSqlMapClientTemplate().delete("project_files.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table project_files
     *
     * @ibatorgenerated Wed Mar 27 15:38:43 CST 2013
     */
    public int deleteByPrimaryKey(Long id) {
        ProjectFiles key = new ProjectFiles();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("project_files.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table project_files
     *
     * @ibatorgenerated Wed Mar 27 15:38:43 CST 2013
     */
    public void insert(ProjectFiles record) {
        getSqlMapClientTemplate().insert("project_files.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table project_files
     *
     * @ibatorgenerated Wed Mar 27 15:38:43 CST 2013
     */
    public void insertSelective(ProjectFiles record) {
        getSqlMapClientTemplate().insert("project_files.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table project_files
     *
     * @ibatorgenerated Wed Mar 27 15:38:43 CST 2013
     */
    public List selectByExampleWithBLOBs(ProjectFilesExample example) {
        List list = getSqlMapClientTemplate().queryForList("project_files.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table project_files
     *
     * @ibatorgenerated Wed Mar 27 15:38:43 CST 2013
     */
    public List selectByExampleWithoutBLOBs(ProjectFilesExample example) {
        List list = getSqlMapClientTemplate().queryForList("project_files.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table project_files
     *
     * @ibatorgenerated Wed Mar 27 15:38:43 CST 2013
     */
    public ProjectFiles selectByPrimaryKey(Long id) {
        ProjectFiles key = new ProjectFiles();
        key.setId(id);
        ProjectFiles record = (ProjectFiles) getSqlMapClientTemplate().queryForObject("project_files.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table project_files
     *
     * @ibatorgenerated Wed Mar 27 15:38:43 CST 2013
     */
    public int updateByExampleSelective(ProjectFiles record, ProjectFilesExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("project_files.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table project_files
     *
     * @ibatorgenerated Wed Mar 27 15:38:43 CST 2013
     */
    public int updateByExampleWithBLOBs(ProjectFiles record, ProjectFilesExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("project_files.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table project_files
     *
     * @ibatorgenerated Wed Mar 27 15:38:43 CST 2013
     */
    public int updateByExampleWithoutBLOBs(ProjectFiles record, ProjectFilesExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("project_files.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table project_files
     *
     * @ibatorgenerated Wed Mar 27 15:38:43 CST 2013
     */
    public int updateByPrimaryKeySelective(ProjectFiles record) {
        int rows = getSqlMapClientTemplate().update("project_files.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table project_files
     *
     * @ibatorgenerated Wed Mar 27 15:38:43 CST 2013
     */
    public int updateByPrimaryKeyWithBLOBs(ProjectFiles record) {
        int rows = getSqlMapClientTemplate().update("project_files.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table project_files
     *
     * @ibatorgenerated Wed Mar 27 15:38:43 CST 2013
     */
    public int updateByPrimaryKeyWithoutBLOBs(ProjectFiles record) {
        int rows = getSqlMapClientTemplate().update("project_files.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table project_files
     *
     * @ibatorgenerated Wed Mar 27 15:38:43 CST 2013
     */
    private static class UpdateByExampleParms extends ProjectFilesExample {
        private Object record;

        public UpdateByExampleParms(Object record, ProjectFilesExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}