package com.blue.user;

import com.blue.user.EpUser;
import com.blue.user.EpUserExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpUserDAOImpl extends SqlMapClientDaoSupport implements EpUserDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ep_user
     *
     * @ibatorgenerated Mon Sep 03 14:54:56 CST 2012
     */
    public EpUserDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ep_user
     *
     * @ibatorgenerated Mon Sep 03 14:54:56 CST 2012
     */
    public int countByExample(EpUserExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("ep_user.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ep_user
     *
     * @ibatorgenerated Mon Sep 03 14:54:56 CST 2012
     */
    public int deleteByExample(EpUserExample example) {
        int rows = getSqlMapClientTemplate().delete("ep_user.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ep_user
     *
     * @ibatorgenerated Mon Sep 03 14:54:56 CST 2012
     */
    public void insert(EpUser record) {
        getSqlMapClientTemplate().insert("ep_user.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ep_user
     *
     * @ibatorgenerated Mon Sep 03 14:54:56 CST 2012
     */
    public void insertSelective(EpUser record) {
        getSqlMapClientTemplate().insert("ep_user.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ep_user
     *
     * @ibatorgenerated Mon Sep 03 14:54:56 CST 2012
     */
    public List selectByExample(EpUserExample example) {
        List list = getSqlMapClientTemplate().queryForList("ep_user.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ep_user
     *
     * @ibatorgenerated Mon Sep 03 14:54:56 CST 2012
     */
    public int updateByExampleSelective(EpUser record, EpUserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ep_user.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ep_user
     *
     * @ibatorgenerated Mon Sep 03 14:54:56 CST 2012
     */
    public int updateByExample(EpUser record, EpUserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ep_user.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table ep_user
     *
     * @ibatorgenerated Mon Sep 03 14:54:56 CST 2012
     */
    private static class UpdateByExampleParms extends EpUserExample {
        private Object record;

        public UpdateByExampleParms(Object record, EpUserExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}