package com.blue.taxi;

import java.util.Collection;

import com.eis.base.BaseForm;
import com.eis.cache.SingleDicMap;

public class TaxiInfoForm extends BaseForm{
    
	private String depart_f;
	private String project_f;
	private Collection depart_f_options;
	
	public Collection getDepart_f_options() {
		return  SingleDicMap.getOptionCollection("9990");
	}

	public void setDepart_f_options(Collection collection) {
		depart_f_options = collection;
	}
	
	
	public String getDepart_f() {
		return depart_f;
	}

	public void setDepart_f(String depart_f) {
		this.depart_f = depart_f;
	}

	public String getProject_f() {
		return project_f;
	}

	public void setProject_f(String project_f) {
		this.project_f = project_f;
	}


	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column taxi_info.TAXI_ID
     *
     * @ibatorgenerated Wed Mar 19 10:46:29 CST 2014
     */
    private Integer taxiId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column taxi_info.TAXI_DATE
     *
     * @ibatorgenerated Wed Mar 19 10:46:29 CST 2014
     */
    private String taxiDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column taxi_info.TAXI_REASON
     *
     * @ibatorgenerated Wed Mar 19 10:46:29 CST 2014
     */
    private String taxiReason;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column taxi_info.TAXI_PATH
     *
     * @ibatorgenerated Wed Mar 19 10:46:29 CST 2014
     */
    private String taxiPath;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column taxi_info.TAXI_AMT
     *
     * @ibatorgenerated Wed Mar 19 10:46:29 CST 2014
     */
    private Double taxiAmt;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column taxi_info.EXPENSE_ID
     *
     * @ibatorgenerated Wed Mar 19 10:46:29 CST 2014
     */
    private long expensesId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column taxi_info.TAXI_ID
     *
     * @return the value of taxi_info.TAXI_ID
     *
     * @ibatorgenerated Wed Mar 19 10:46:29 CST 2014
     */
    public Integer getTaxiId() {
        return taxiId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column taxi_info.TAXI_ID
     *
     * @param taxiId the value for taxi_info.TAXI_ID
     *
     * @ibatorgenerated Wed Mar 19 10:46:29 CST 2014
     */
    public void setTaxiId(Integer taxiId) {
        this.taxiId = taxiId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column taxi_info.TAXI_DATE
     *
     * @return the value of taxi_info.TAXI_DATE
     *
     * @ibatorgenerated Wed Mar 19 10:46:29 CST 2014
     */
    public String getTaxiDate() {
        return taxiDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column taxi_info.TAXI_DATE
     *
     * @param taxiDate the value for taxi_info.TAXI_DATE
     *
     * @ibatorgenerated Wed Mar 19 10:46:29 CST 2014
     */
    public void setTaxiDate(String taxiDate) {
        this.taxiDate = taxiDate == null ? null : taxiDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column taxi_info.TAXI_REASON
     *
     * @return the value of taxi_info.TAXI_REASON
     *
     * @ibatorgenerated Wed Mar 19 10:46:29 CST 2014
     */
    public String getTaxiReason() {
        return taxiReason;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column taxi_info.TAXI_REASON
     *
     * @param taxiReason the value for taxi_info.TAXI_REASON
     *
     * @ibatorgenerated Wed Mar 19 10:46:29 CST 2014
     */
    public void setTaxiReason(String taxiReason) {
        this.taxiReason = taxiReason == null ? null : taxiReason.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column taxi_info.TAXI_PATH
     *
     * @return the value of taxi_info.TAXI_PATH
     *
     * @ibatorgenerated Wed Mar 19 10:46:29 CST 2014
     */
    public String getTaxiPath() {
        return taxiPath;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column taxi_info.TAXI_PATH
     *
     * @param taxiPath the value for taxi_info.TAXI_PATH
     *
     * @ibatorgenerated Wed Mar 19 10:46:29 CST 2014
     */
    public void setTaxiPath(String taxiPath) {
        this.taxiPath = taxiPath == null ? null : taxiPath.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column taxi_info.TAXI_AMT
     *
     * @return the value of taxi_info.TAXI_AMT
     *
     * @ibatorgenerated Wed Mar 19 10:46:29 CST 2014
     */
    public Double getTaxiAmt() {
        return taxiAmt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column taxi_info.TAXI_AMT
     *
     * @param taxiAmt the value for taxi_info.TAXI_AMT
     *
     * @ibatorgenerated Wed Mar 19 10:46:29 CST 2014
     */
    public void setTaxiAmt(Double taxiAmt) {
        this.taxiAmt = taxiAmt;
    }

	public long getExpensesId() {
		return expensesId;
	}

	public void setExpensesId(long expensesId) {
		this.expensesId = expensesId;
	}
    private String taxiTime;

	public String getTaxiTime() {
		return taxiTime;
	}

	public void setTaxiTime(String taxiTime) {
		this.taxiTime = taxiTime;
	}
    
    private Integer taxiInvoiceno;

	public Integer getTaxiInvoiceno() {
		return taxiInvoiceno;
	}

	public void setTaxiInvoiceno(Integer taxiInvoiceno) {
		this.taxiInvoiceno = taxiInvoiceno;
	}
    
}