package com.blue.version.paramchg;

import com.blue.version.paramchg.ParamChg;
import com.blue.version.paramchg.ParamChgExample;
import java.util.List;

public interface ParamChgDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    int countByExample(ParamChgExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    int deleteByExample(ParamChgExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    void insert(ParamChg record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    void insertSelective(ParamChg record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    List selectByExample(ParamChgExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    ParamChg selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    int updateByExampleSelective(ParamChg record, ParamChgExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    int updateByExample(ParamChg record, ParamChgExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    int updateByPrimaryKeySelective(ParamChg record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    int updateByPrimaryKey(ParamChg record);
}