package com.blue.version.paramchg;

public class ParamChg {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column param_chg.ID
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column param_chg.SUB_SYS
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private String subSys;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column param_chg.PARENT_MENU
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private String parentMenu;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column param_chg.SUB_MENU
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private String subMenu;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column param_chg.MEMO
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private String memo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column param_chg.CHG_TYPE
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private String chgType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column param_chg.ORIGINL
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private String originl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column param_chg.TARGET
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private String target;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column param_chg.VERSION_ID
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private String versionId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column param_chg.ID
     *
     * @return the value of param_chg.ID
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column param_chg.ID
     *
     * @param id the value for param_chg.ID
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column param_chg.SUB_SYS
     *
     * @return the value of param_chg.SUB_SYS
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public String getSubSys() {
        return subSys;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column param_chg.SUB_SYS
     *
     * @param subSys the value for param_chg.SUB_SYS
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void setSubSys(String subSys) {
        this.subSys = subSys == null ? null : subSys.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column param_chg.PARENT_MENU
     *
     * @return the value of param_chg.PARENT_MENU
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public String getParentMenu() {
        return parentMenu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column param_chg.PARENT_MENU
     *
     * @param parentMenu the value for param_chg.PARENT_MENU
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void setParentMenu(String parentMenu) {
        this.parentMenu = parentMenu == null ? null : parentMenu.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column param_chg.SUB_MENU
     *
     * @return the value of param_chg.SUB_MENU
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public String getSubMenu() {
        return subMenu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column param_chg.SUB_MENU
     *
     * @param subMenu the value for param_chg.SUB_MENU
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void setSubMenu(String subMenu) {
        this.subMenu = subMenu == null ? null : subMenu.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column param_chg.MEMO
     *
     * @return the value of param_chg.MEMO
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column param_chg.MEMO
     *
     * @param memo the value for param_chg.MEMO
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column param_chg.CHG_TYPE
     *
     * @return the value of param_chg.CHG_TYPE
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public String getChgType() {
        return chgType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column param_chg.CHG_TYPE
     *
     * @param chgType the value for param_chg.CHG_TYPE
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void setChgType(String chgType) {
        this.chgType = chgType == null ? null : chgType.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column param_chg.ORIGINL
     *
     * @return the value of param_chg.ORIGINL
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public String getOriginl() {
        return originl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column param_chg.ORIGINL
     *
     * @param originl the value for param_chg.ORIGINL
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void setOriginl(String originl) {
        this.originl = originl == null ? null : originl.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column param_chg.TARGET
     *
     * @return the value of param_chg.TARGET
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column param_chg.TARGET
     *
     * @param target the value for param_chg.TARGET
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column param_chg.VERSION_ID
     *
     * @return the value of param_chg.VERSION_ID
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public String getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column param_chg.VERSION_ID
     *
     * @param versionId the value for param_chg.VERSION_ID
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void setVersionId(String versionId) {
        this.versionId = versionId == null ? null : versionId.trim();
    }
}