package com.blue.version.paramchg;

import com.blue.version.paramchg.ParamChg;
import com.blue.version.paramchg.ParamChgExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ParamChgDAOImpl extends SqlMapClientDaoSupport implements ParamChgDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public ParamChgDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int countByExample(ParamChgExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("param_chg.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int deleteByExample(ParamChgExample example) {
        int rows = getSqlMapClientTemplate().delete("param_chg.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int deleteByPrimaryKey(Long id) {
        ParamChg key = new ParamChg();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("param_chg.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void insert(ParamChg record) {
        getSqlMapClientTemplate().insert("param_chg.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void insertSelective(ParamChg record) {
        getSqlMapClientTemplate().insert("param_chg.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public List selectByExample(ParamChgExample example) {
        List list = getSqlMapClientTemplate().queryForList("param_chg.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public ParamChg selectByPrimaryKey(Long id) {
        ParamChg key = new ParamChg();
        key.setId(id);
        ParamChg record = (ParamChg) getSqlMapClientTemplate().queryForObject("param_chg.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int updateByExampleSelective(ParamChg record, ParamChgExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("param_chg.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int updateByExample(ParamChg record, ParamChgExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("param_chg.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int updateByPrimaryKeySelective(ParamChg record) {
        int rows = getSqlMapClientTemplate().update("param_chg.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int updateByPrimaryKey(ParamChg record) {
        int rows = getSqlMapClientTemplate().update("param_chg.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table param_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private static class UpdateByExampleParms extends ParamChgExample {
        private Object record;

        public UpdateByExampleParms(Object record, ParamChgExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}