package com.blue.pm.mainplanjob;

public class MainPlanJob {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column main_plan_job.PROJECT_ID
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    private String projectId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column main_plan_job.USER_ID
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    private String userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column main_plan_job.IS_DOEN
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    private String isDoen;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column main_plan_job.INPUT_DATE
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    private String inputDate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column main_plan_job.PROJECT_ID
     *
     * @return the value of main_plan_job.PROJECT_ID
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column main_plan_job.PROJECT_ID
     *
     * @param projectId the value for main_plan_job.PROJECT_ID
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column main_plan_job.USER_ID
     *
     * @return the value of main_plan_job.USER_ID
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column main_plan_job.USER_ID
     *
     * @param userId the value for main_plan_job.USER_ID
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column main_plan_job.IS_DOEN
     *
     * @return the value of main_plan_job.IS_DOEN
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    public String getIsDoen() {
        return isDoen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column main_plan_job.IS_DOEN
     *
     * @param isDoen the value for main_plan_job.IS_DOEN
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    public void setIsDoen(String isDoen) {
        this.isDoen = isDoen == null ? null : isDoen.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column main_plan_job.INPUT_DATE
     *
     * @return the value of main_plan_job.INPUT_DATE
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    public String getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column main_plan_job.INPUT_DATE
     *
     * @param inputDate the value for main_plan_job.INPUT_DATE
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    public void setInputDate(String inputDate) {
        this.inputDate = inputDate == null ? null : inputDate.trim();
    }
}