package com.blue.pm.mainplanjob;

import com.blue.pm.mainplanjob.MainPlanJob;
import com.blue.pm.mainplanjob.MainPlanJobExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class MainPlanJobDAOImpl extends SqlMapClientDaoSupport implements MainPlanJobDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_plan_job
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    public MainPlanJobDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_plan_job
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    public int countByExample(MainPlanJobExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("main_plan_job.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_plan_job
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    public int deleteByExample(MainPlanJobExample example) {
        int rows = getSqlMapClientTemplate().delete("main_plan_job.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_plan_job
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    public int deleteByPrimaryKey(String projectId) {
        MainPlanJob key = new MainPlanJob();
        key.setProjectId(projectId);
        int rows = getSqlMapClientTemplate().delete("main_plan_job.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_plan_job
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    public void insert(MainPlanJob record) {
        getSqlMapClientTemplate().insert("main_plan_job.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_plan_job
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    public void insertSelective(MainPlanJob record) {
        getSqlMapClientTemplate().insert("main_plan_job.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_plan_job
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    public List selectByExample(MainPlanJobExample example) {
        List list = getSqlMapClientTemplate().queryForList("main_plan_job.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_plan_job
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    public MainPlanJob selectByPrimaryKey(String projectId) {
        MainPlanJob key = new MainPlanJob();
        key.setProjectId(projectId);
        MainPlanJob record = (MainPlanJob) getSqlMapClientTemplate().queryForObject("main_plan_job.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_plan_job
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    public int updateByExampleSelective(MainPlanJob record, MainPlanJobExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("main_plan_job.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_plan_job
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    public int updateByExample(MainPlanJob record, MainPlanJobExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("main_plan_job.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_plan_job
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    public int updateByPrimaryKeySelective(MainPlanJob record) {
        int rows = getSqlMapClientTemplate().update("main_plan_job.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_plan_job
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    public int updateByPrimaryKey(MainPlanJob record) {
        int rows = getSqlMapClientTemplate().update("main_plan_job.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table main_plan_job
     *
     * @ibatorgenerated Tue Aug 06 11:24:58 CST 2013
     */
    private static class UpdateByExampleParms extends MainPlanJobExample {
        private Object record;

        public UpdateByExampleParms(Object record, MainPlanJobExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}