package com.blue.budget.detail;

import java.util.Collection;

import com.eis.base.BaseForm;
import com.eis.cache.SingleDicMap;

public class BudgetDetailForm extends BaseForm{
    private String oper;
    
	public String getOper() {
		return oper;
	}


	public void setOper(String oper) {
		this.oper = oper;
	}


	private String depart_f;
	private String project_f;
	private Collection depart_f_options;
	
	private Collection fee_kind_options;
	private Collection budget_kind_options;
	public Collection getFee_kind_options() {
		return  SingleDicMap.getOptionCollection("7001");
	}


	public void setFee_kind_options(Collection fee_kind_options) {
		this.fee_kind_options = fee_kind_options;
	}

	public Collection getBudget_kind_options() {
		return  SingleDicMap.getOptionCollection("7000");
	}

	public void setBudget_kind_options(Collection budget_kind_options) {
		this.budget_kind_options = budget_kind_options;
	}

	public Collection getDepart_f_options() {
		return  SingleDicMap.getOptionCollection("9990");
	}

	public void setDepart_f_options(Collection collection) {
		depart_f_options = collection;
	}

	public String getDepart_f() {
		return depart_f;
	}

	public void setDepart_f(String depart_f) {
		this.depart_f = depart_f;
	}

	public String getProject_f() {
		return project_f;
	}

	public void setProject_f(String project_f) {
		this.project_f = project_f;
	}

	 /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column budget_detail.BUDGET_ID
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    private Long budgetId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column budget_detail.BUDGET_KIND
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    private String budgetKind;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column budget_detail.FEE_KIND
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    private String feeKind;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column budget_detail.YEARMONTH
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    private String yearmonth;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column budget_detail.PROJECT_NO
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    private String projectNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column budget_detail.PROJECT_NAME
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    private String projectName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column budget_detail.FEE_AMT
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    private Double feeAmt;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column budget_detail.FEE_BAL
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    private Double feeBal;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column budget_detail.DEPART
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    private String depart;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column budget_detail.BUDGET_ID
     *
     * @return the value of budget_detail.BUDGET_ID
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public Long getBudgetId() {
        return budgetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column budget_detail.BUDGET_ID
     *
     * @param budgetId the value for budget_detail.BUDGET_ID
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public void setBudgetId(Long budgetId) {
        this.budgetId = budgetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column budget_detail.BUDGET_KIND
     *
     * @return the value of budget_detail.BUDGET_KIND
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public String getBudgetKind() {
        return budgetKind;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column budget_detail.BUDGET_KIND
     *
     * @param budgetKind the value for budget_detail.BUDGET_KIND
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public void setBudgetKind(String budgetKind) {
        this.budgetKind = budgetKind == null ? null : budgetKind.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column budget_detail.FEE_KIND
     *
     * @return the value of budget_detail.FEE_KIND
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public String getFeeKind() {
        return feeKind;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column budget_detail.FEE_KIND
     *
     * @param feeKind the value for budget_detail.FEE_KIND
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public void setFeeKind(String feeKind) {
        this.feeKind = feeKind == null ? null : feeKind.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column budget_detail.YEARMONTH
     *
     * @return the value of budget_detail.YEARMONTH
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public String getYearmonth() {
        return yearmonth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column budget_detail.YEARMONTH
     *
     * @param yearmonth the value for budget_detail.YEARMONTH
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public void setYearmonth(String yearmonth) {
        this.yearmonth = yearmonth == null ? null : yearmonth.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column budget_detail.PROJECT_NO
     *
     * @return the value of budget_detail.PROJECT_NO
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public String getProjectNo() {
        return projectNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column budget_detail.PROJECT_NO
     *
     * @param projectNo the value for budget_detail.PROJECT_NO
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public void setProjectNo(String projectNo) {
        this.projectNo = projectNo == null ? null : projectNo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column budget_detail.PROJECT_NAME
     *
     * @return the value of budget_detail.PROJECT_NAME
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column budget_detail.PROJECT_NAME
     *
     * @param projectName the value for budget_detail.PROJECT_NAME
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column budget_detail.FEE_AMT
     *
     * @return the value of budget_detail.FEE_AMT
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public Double getFeeAmt() {
        return feeAmt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column budget_detail.FEE_AMT
     *
     * @param feeAmt the value for budget_detail.FEE_AMT
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public void setFeeAmt(Double feeAmt) {
        this.feeAmt = feeAmt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column budget_detail.FEE_BAL
     *
     * @return the value of budget_detail.FEE_BAL
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public Double getFeeBal() {
        return feeBal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column budget_detail.FEE_BAL
     *
     * @param feeBal the value for budget_detail.FEE_BAL
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public void setFeeBal(Double feeBal) {
        this.feeBal = feeBal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column budget_detail.DEPART
     *
     * @return the value of budget_detail.DEPART
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public String getDepart() {
        return depart;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column budget_detail.DEPART
     *
     * @param depart the value for budget_detail.DEPART
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public void setDepart(String depart) {
        this.depart = depart == null ? null : depart.trim();
    }
	private String regDate_from;
	private String regDate_to;

	public String getRegDate_from() {
		return regDate_from;
	}

	public void setRegDate_from(String regDate_from) {
		this.regDate_from = regDate_from;
	}

	public String getRegDate_to() {
		return regDate_to;
	}

	public void setRegDate_to(String regDate_to) {
		this.regDate_to = regDate_to;
	}
	private String feeKind_f;

	public String getFeeKind_f() {
		return feeKind_f;
	}

	public void setFeeKind_f(String feeKind_f) {
		this.feeKind_f = feeKind_f;
	}
	
}