package com.blue.version.databasechg;

import com.blue.version.databasechg.DatabaseChg;
import com.blue.version.databasechg.DatabaseChgExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class DatabaseChgDAOImpl extends SqlMapClientDaoSupport implements DatabaseChgDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table database_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public DatabaseChgDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table database_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int countByExample(DatabaseChgExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("database_chg.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table database_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int deleteByExample(DatabaseChgExample example) {
        int rows = getSqlMapClientTemplate().delete("database_chg.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table database_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int deleteByPrimaryKey(Long id) {
        DatabaseChg key = new DatabaseChg();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("database_chg.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table database_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void insert(DatabaseChg record) {
        getSqlMapClientTemplate().insert("database_chg.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table database_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void insertSelective(DatabaseChg record) {
        getSqlMapClientTemplate().insert("database_chg.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table database_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public List selectByExample(DatabaseChgExample example) {
        List list = getSqlMapClientTemplate().queryForList("database_chg.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table database_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public DatabaseChg selectByPrimaryKey(Long id) {
        DatabaseChg key = new DatabaseChg();
        key.setId(id);
        DatabaseChg record = (DatabaseChg) getSqlMapClientTemplate().queryForObject("database_chg.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table database_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int updateByExampleSelective(DatabaseChg record, DatabaseChgExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("database_chg.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table database_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int updateByExample(DatabaseChg record, DatabaseChgExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("database_chg.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table database_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int updateByPrimaryKeySelective(DatabaseChg record) {
        int rows = getSqlMapClientTemplate().update("database_chg.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table database_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int updateByPrimaryKey(DatabaseChg record) {
        int rows = getSqlMapClientTemplate().update("database_chg.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table database_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private static class UpdateByExampleParms extends DatabaseChgExample {
        private Object record;

        public UpdateByExampleParms(Object record, DatabaseChgExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}