/*
 * @# ProjectMaintainForm.java 2008-11-6 houxh
 *
 */
 
package com.projectmaintain;

import java.util.Collection;

import com.blue.enums.ProjectType;
import com.blue.enums.Status;
import com.blue.enums.Steps;
import com.eis.base.BaseForm;
import com.eis.cache.ReDefSDicMap;
import com.eis.cache.RedefSDicCodes;
import com.eis.cache.SingleDic;
import com.eis.cache.SingleDicMap;


public class ProjectMaintainForm extends BaseForm {
	
	public static final String EIS = "3";
	public static final String EIS_COLLECTION = "9987";
	public static final String V_PLUS = "2";
	public static final String V_PLUS_COLLECTION = "9986";
	
	private String day;
	private String endDate;
	private String endDate_f;
	private Integer id;
	private Collection isInContractCollection;
	private Collection needDevCollection;
	private Collection owningCollection;
	private String preProjects;
	private Collection priorityCollection;
	private Collection projectClassCollection;
	private String projectId_f;
	
	private String reason;
	private String startDate;
	private String status_f;
	private String step_f;
	private String subSys;
	private String realEndDate;
	private String requireManager;
	
	private Collection statusCollection;
	
	private Collection stepCollection;
	
	private Collection requireManagers;
	private Collection projectManagers;

	private String projectId;
	private String versionId;
	private int scaleId;
	private String checker;
	private String mainPlanDis;
	private String productIds;
	private double planCost;
	private String[] ids;
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_list.PROJECT_NAME
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    private String projectName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_list.STAT
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    private String stat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_list.USER_ID
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    private String userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_list.MEMO
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    private String memo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_list.ISS_ID
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    private String issId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_list.IS_IN_CONTRACT
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    private String isInContract;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_list.NEED_DEV
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    private String needDev;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_list.OWNING
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    private String owning;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_list.PROJECT_CLASS
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    private String projectClass;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_list.PRIORITY
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    private Integer priority;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_list.PROJECT_MANAGER
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    private String projectManager;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_list.TECH_MANAGER
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    private String techManager;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_list.SETUP_DATE
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    private String setupDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_list.PLAN_START_DATE
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    private String planStartDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_list.PLAN_END_DATE
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    private String planEndDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_list.STEP
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    private String step;

   

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column project_list.STAT
     *
     * @return the value of project_list.STAT
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column project_list.STAT
     *
     * @param stat the value for project_list.STAT
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    public void setStat(String stat) {
        this.stat = stat == null ? null : stat.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column project_list.PRIORITY
     *
     * @param priority the value for project_list.PRIORITY
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
    public Integer getPriority() {
		return priority;
	}

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column project_list.PROJECT_MANAGER
     *
     * @return the value of project_list.PROJECT_MANAGER
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    public String getProjectManager() {
        return projectManager;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column project_list.PROJECT_MANAGER
     *
     * @param projectManager the value for project_list.PROJECT_MANAGER
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    public void setProjectManager(String projectManager) {
        this.projectManager = projectManager == null ? null : projectManager.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column project_list.TECH_MANAGER
     *
     * @return the value of project_list.TECH_MANAGER
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    public String getTechManager() {
        return techManager;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column project_list.TECH_MANAGER
     *
     * @param techManager the value for project_list.TECH_MANAGER
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    public void setTechManager(String techManager) {
        this.techManager = techManager == null ? null : techManager.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column project_list.SETUP_DATE
     *
     * @return the value of project_list.SETUP_DATE
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    public String getSetupDate() {
        return setupDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column project_list.SETUP_DATE
     *
     * @param setupDate the value for project_list.SETUP_DATE
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    public void setSetupDate(String setupDate) {
        this.setupDate = setupDate == null ? null : setupDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column project_list.PLAN_START_DATE
     *
     * @return the value of project_list.PLAN_START_DATE
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    public String getPlanStartDate() {
        return planStartDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column project_list.PLAN_START_DATE
     *
     * @param planStartDate the value for project_list.PLAN_START_DATE
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    public void setPlanStartDate(String planStartDate) {
        this.planStartDate = planStartDate == null ? null : planStartDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column project_list.PLAN_END_DATE
     *
     * @return the value of project_list.PLAN_END_DATE
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    public String getPlanEndDate() {
        return planEndDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column project_list.PLAN_END_DATE
     *
     * @param planEndDate the value for project_list.PLAN_END_DATE
     *
     * @ibatorgenerated Mon Aug 27 17:37:04 CST 2012
     */
    public void setPlanEndDate(String planEndDate) {
        this.planEndDate = planEndDate == null ? null : planEndDate.trim();
    }

    
	/**
	 * @return
	 */
	public String getDay() {
		return day;
	}

	/**
	 * @return
	 */
	public String getEndDate() {
		return endDate;
	}

	/**
	 * @return
	 */
	public String getEndDate_f() {
		return endDate_f;
	}

	public Integer getId() {
		return id;
	}

	/**
	 * @return
	 */
	public String getIsInContract() {
		return isInContract;
	}
	
	/**
	 * @return
	 */
	public Collection getIsInContractCollection() {
		return SingleDicMap.getOptionCollection(SingleDic.YES_OR_NO);
	}
	/**
	 * @return
	 */
	public String getIssId() {
		return issId;
	}

	/**
	 * @return
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * @return
	 */
	public String getNeedDev() {
		return needDev;
	}

	/**
	 * @return
	 */
	public Collection getNeedDevCollection() {
		return SingleDicMap.getOptionCollection(SingleDic.YES_OR_NO);
	}

	/**
	 * @return
	 */
	public String getOwning() {
		return owning;
	}

	/**
	 * @return
	 */
	public Collection getOwningCollection() {
		return SingleDicMap.getOptionCollection(SingleDic.PROJECT_OWNING);
	}

	/**
	 * @return
	 */
	public String getPreProjects() {
		return preProjects;
	}


	public Collection getPriorityCollection() {
		return SingleDicMap.getOptionCollection(SingleDic.PRIORITY);
	}

	/**
	 * @return
	 */
	public String getProjectClass() {
		return (projectClass==null?"":projectClass.trim());
	}

	/**
	 * @return
	 */
	public Collection getProjectClassCollection() {
		return ProjectType.toCollection();
	}

	public String getProjectClassName(){
		if(projectClass != null){
			if(V_PLUS.equals(owning)){
				return SingleDicMap.getDicItemVal(V_PLUS_COLLECTION,projectClass.trim());
			}else if(EIS.equals(owning)){
				return SingleDicMap.getDicItemVal(EIS_COLLECTION,projectClass.trim());
			}
		}
		
		return "";
	}

	/**
	 * @return
	 */
	public String getProjectId() {
		return projectId;
	}

	/**
	 * @return
	 */
	public String getProjectId_f() {
		return projectId_f;
	}


	/**
	 * @return
	 */
	public String getProjectName() {
		return projectName;
	}

	/**
	 * @return
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * @return
	 */
	public String getStartDate() {
		return startDate;
	}


	/**
	 * @return
	 */
	public String getStatus_f() {
		return status_f;
	}

	/**
	 * @return
	 */
	public Collection getStatusCollection() {
		return Status.toCollection();
	}

	public String getStep() {
		return step;
	}



	/**
	 * @return
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * @param string
	 */
	public void setDay(String string) {
		day = string;
	}

	/**
	 * @param string
	 */
	public void setEndDate(String string) {
		endDate = string;
	}

	/**
	 * @param string
	 */
	public void setEndDate_f(String string) {
		endDate_f = string;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @param string
	 */
	public void setIsInContract(String string) {
		isInContract = string;
	}

	/**
	 * @param collection
	 */
	public void setIsInContractCollection(Collection collection) {
		isInContractCollection = collection;
	}

	/**
	 * @param string
	 */
	public void setIssId(String string) {
		issId = string;
	}

	/**
	 * @param string
	 */
	public void setMemo(String string) {
		memo = string;
	}

	/**
	 * @param string
	 */
	public void setNeedDev(String string) {
		needDev = string;
	}

	/**
	 * @param collection
	 */
	public void setNeedDevCollection(Collection collection) {
		needDevCollection = collection;
	}

	/**
	 * @param string
	 */
	public void setOwning(String string) {
		owning = string;
	}

	/**
	 * @param collection
	 */
	public void setOwningCollection(Collection collection) {
		owningCollection = collection;
	}

	/**
	 * @param string
	 */
	public void setPreProjects(String string) {
		preProjects = string;
	}

	public void setPriorityCollection(Collection priorityCollection) {
		this.priorityCollection = priorityCollection;
	}

	/**
	 * @param string
	 */
	public void setProjectClass(String string) {
		projectClass = string;
	}

	/**
	 * @param collection
	 */
	public void setProjectClassCollection(Collection collection) {
		projectClassCollection = collection;
	}

	/**
	 * @param string
	 */
	public void setProjectId(String string) {
		projectId = string;
	}

	/**
	 * @param string
	 */
	public void setProjectId_f(String string) {
		projectId_f = string;
	}

	/**
	 * @param string
	 */
	public void setProjectName(String string) {
		projectName = string;
	}

	/**
	 * @param string
	 */
	public void setReason(String string) {
		reason = string;
	}

	/**
	 * @param string
	 */
	public void setStartDate(String string) {
		startDate = string;
	}

	/**
	 * @param string
	 */
	public void setStatus_f(String string) {
		status_f = string;
	}
	/**
	 * @param collection
	 */
	public void setStatusCollection(Collection collection) {
		statusCollection = collection;
	}
	public void setStep(String step) {
		this.step = step;
	}

	public void setStepCollection(Collection stepCollection) {
		this.stepCollection = stepCollection;
	}

	/**
	 * @param string
	 */
	public void setUserId(String string) {
		userId = string;
	}

	public String getStep_f() {
		return step_f;
	}

	public void setStep_f(String step_f) {
		this.step_f = step_f;
	}

	public String getSubSys() {
		return subSys;
	}

	public void setSubSys(String subSys) {
		this.subSys = subSys;
	}

	public String getRealEndDate() {
		return realEndDate;
	}

	public void setRealEndDate(String realEndDate) {
		this.realEndDate = realEndDate;
	}

	public String getRequireManager() {
		return requireManager;
	}

	public void setRequireManager(String requireManager) {
		this.requireManager = requireManager;
	}

	public Collection getRequireManagers() {
		return ReDefSDicMap.getOptionCollection(RedefSDicCodes.PM);
	}

	public void setRequireManagers(Collection requireManagers) {
		this.requireManagers = requireManagers;
	}

	public Collection getProjectManagers() {
		return ReDefSDicMap.getOptionCollection(RedefSDicCodes.PM);
	}

	public void setProjectManagers(Collection projectManagers) {
		this.projectManagers = projectManagers;
	}

	public String getVersionId() {
		return versionId;
	}

	public void setVersionId(String versionId) {
		this.versionId = versionId;
	}

	public String[] getIds() {
		return ids;
	}

	public void setIds(String[] ids) {
		this.ids = ids;
	}

	public int getScaleId() {
		return scaleId;
	}

	public void setScaleId(int scaleId) {
		this.scaleId = scaleId;
	}

	public String getChecker() {
		return checker;
	}

	public void setChecker(String checker) {
		this.checker = checker;
	}

	public String getMainPlanDis() {
		return mainPlanDis;
	}

	public void setMainPlanDis(String mainPlanDis) {
		this.mainPlanDis = mainPlanDis;
	}

	public String getProductIds() {
		return productIds;
	}

	public void setProductIds(String productIds) {
		this.productIds = productIds;
	}

	public double getPlanCost() {
		return planCost;
	}

	public void setPlanCost(double planCost) {
		this.planCost = planCost;
	}

}
