package com.blue.project.reviewrecord;

import com.blue.project.reviewrecord.ReviewRecord;
import com.blue.project.reviewrecord.ReviewRecordExample;
import java.util.List;

public interface ReviewRecordDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    int countByExample(ReviewRecordExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    int deleteByExample(ReviewRecordExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    void insert(ReviewRecord record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    void insertSelective(ReviewRecord record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    List selectByExample(ReviewRecordExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    ReviewRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    int updateByExampleSelective(ReviewRecord record, ReviewRecordExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    int updateByExample(ReviewRecord record, ReviewRecordExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    int updateByPrimaryKeySelective(ReviewRecord record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    int updateByPrimaryKey(ReviewRecord record);
}