package com.blue.project.reviewrecord;

import com.blue.project.reviewrecord.ReviewRecord;
import com.blue.project.reviewrecord.ReviewRecordExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ReviewRecordDAOImpl extends SqlMapClientDaoSupport implements ReviewRecordDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    public ReviewRecordDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    public int countByExample(ReviewRecordExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("review_record.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    public int deleteByExample(ReviewRecordExample example) {
        int rows = getSqlMapClientTemplate().delete("review_record.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    public int deleteByPrimaryKey(Long id) {
        ReviewRecord key = new ReviewRecord();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("review_record.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    public void insert(ReviewRecord record) {
        getSqlMapClientTemplate().insert("review_record.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    public void insertSelective(ReviewRecord record) {
        getSqlMapClientTemplate().insert("review_record.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    public List selectByExample(ReviewRecordExample example) {
        List list = getSqlMapClientTemplate().queryForList("review_record.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    public ReviewRecord selectByPrimaryKey(Long id) {
        ReviewRecord key = new ReviewRecord();
        key.setId(id);
        ReviewRecord record = (ReviewRecord) getSqlMapClientTemplate().queryForObject("review_record.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    public int updateByExampleSelective(ReviewRecord record, ReviewRecordExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("review_record.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    public int updateByExample(ReviewRecord record, ReviewRecordExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("review_record.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    public int updateByPrimaryKeySelective(ReviewRecord record) {
        int rows = getSqlMapClientTemplate().update("review_record.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    public int updateByPrimaryKey(ReviewRecord record) {
        int rows = getSqlMapClientTemplate().update("review_record.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table review_record
     *
     * @ibatorgenerated Fri Jan 11 10:45:37 CST 2013
     */
    private static class UpdateByExampleParms extends ReviewRecordExample {
        private Object record;

        public UpdateByExampleParms(Object record, ReviewRecordExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}