package com.yly.pki;

import com.yly.pki.Secpkitb;
import com.yly.pki.SecpkitbExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SecpkitbDAOImpl extends SqlMapClientDaoSupport implements SecpkitbDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table secpkitb
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public SecpkitbDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table secpkitb
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public int countByExample(SecpkitbExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("secpkitb.ibatorgenerated_countByExample", example);
        return count.intValue();
    }
    public int updateBySamIdAndSamCsn(Secpkitb record) {
        int rows = getSqlMapClientTemplate().update("secpkitb.updateBySamIdAndSamCsn", record);
        return rows;
    }
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table secpkitb
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public int deleteByExample(SecpkitbExample example) {
        int rows = getSqlMapClientTemplate().delete("secpkitb.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table secpkitb
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public int deleteByPrimaryKey(String pubKey) {
        Secpkitb key = new Secpkitb();
        key.setPubKey(pubKey);
        int rows = getSqlMapClientTemplate().delete("secpkitb.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table secpkitb
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public void insert(Secpkitb record) {
        getSqlMapClientTemplate().insert("secpkitb.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table secpkitb
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public void insertSelective(Secpkitb record) {
        getSqlMapClientTemplate().insert("secpkitb.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table secpkitb
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public List selectByExample(SecpkitbExample example) {
        List list = getSqlMapClientTemplate().queryForList("secpkitb.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table secpkitb
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public Secpkitb selectByPrimaryKey(String pubKey) {
        Secpkitb key = new Secpkitb();
        key.setPubKey(pubKey);
        Secpkitb record = (Secpkitb) getSqlMapClientTemplate().queryForObject("secpkitb.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table secpkitb
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public int updateByExampleSelective(Secpkitb record, SecpkitbExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("secpkitb.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table secpkitb
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public int updateByExample(Secpkitb record, SecpkitbExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("secpkitb.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table secpkitb
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public int updateByPrimaryKeySelective(Secpkitb record) {
        int rows = getSqlMapClientTemplate().update("secpkitb.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table secpkitb
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public int updateByPrimaryKey(Secpkitb record) {
        int rows = getSqlMapClientTemplate().update("secpkitb.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table secpkitb
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    private static class UpdateByExampleParms extends SecpkitbExample {
        private Object record;

        public UpdateByExampleParms(Object record, SecpkitbExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}