package com.yly.pki;

import java.util.Collection;
import java.util.Date;

import org.apache.struts.upload.FormFile;

import com.eis.base.BaseForm;
import com.eis.cache.ReDefSDicMap;
import com.eis.cache.RedefSDicCodes;
import com.eis.cache.SingleDic;
import com.eis.cache.SingleDicMap;

public class SecpkitbForm extends BaseForm {
	private String samId_min;
	private String samId_max;
    private String beginDate_f;
    private String endDate_f;
	private FormFile file;
	public FormFile getFile() {
		return file;
	}

	public void setFile(FormFile file) {
		this.file = file;
	}
    public String getBeginDate_f() {
		return beginDate_f;
	}

	public void setBeginDate_f(String beginDate_f) {
		this.beginDate_f = beginDate_f;
	}

	public String getEndDate_f() {
		return endDate_f;
	}

	public void setEndDate_f(String endDate_f) {
		this.endDate_f = endDate_f;
	}

	public String getSamId_min() {
		return samId_min;
	}

	public void setSamId_min(String samId_min) {
		this.samId_min = samId_min;
	}

	public String getSamId_max() {
		return samId_max;
	}

	public void setSamId_max(String samId_max) {
		this.samId_max = samId_max;
	}

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column secpkitb.PubKey
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    private String pubKey;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column secpkitb.SamId
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    private String samId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column secpkitb.SamCSN
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    private String samCSN;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column secpkitb.PubExponent
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    private String pubExponent;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column secpkitb.KeyType
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    private Short keyType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column secpkitb.IssueTime
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    private Date issueTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column secpkitb.CurrPeriod
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    private Date currPeriod;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column secpkitb.Rsvd
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    private String rsvd;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column secpkitb.PubKey
     *
     * @return the value of secpkitb.PubKey
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public String getPubKey() {
        return pubKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column secpkitb.PubKey
     *
     * @param pubKey the value for secpkitb.PubKey
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public void setPubKey(String pubKey) {
        this.pubKey = pubKey == null ? null : pubKey.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column secpkitb.SamId
     *
     * @return the value of secpkitb.SamId
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public String getSamId() {
        return samId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column secpkitb.SamId
     *
     * @param samId the value for secpkitb.SamId
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public void setSamId(String samId) {
        this.samId = samId == null ? null : samId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column secpkitb.SamCSN
     *
     * @return the value of secpkitb.SamCSN
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public String getSamCSN() {
        return samCSN;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column secpkitb.SamCSN
     *
     * @param samCSN the value for secpkitb.SamCSN
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public void setSamCSN(String samCSN) {
        this.samCSN = samCSN == null ? null : samCSN.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column secpkitb.PubExponent
     *
     * @return the value of secpkitb.PubExponent
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public String getPubExponent() {
        return pubExponent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column secpkitb.PubExponent
     *
     * @param pubExponent the value for secpkitb.PubExponent
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public void setPubExponent(String pubExponent) {
        this.pubExponent = pubExponent == null ? null : pubExponent.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column secpkitb.KeyType
     *
     * @return the value of secpkitb.KeyType
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public Short getKeyType() {
        return keyType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column secpkitb.KeyType
     *
     * @param keyType the value for secpkitb.KeyType
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public void setKeyType(Short keyType) {
        this.keyType = keyType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column secpkitb.IssueTime
     *
     * @return the value of secpkitb.IssueTime
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public Date getIssueTime() {
        return issueTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column secpkitb.IssueTime
     *
     * @param issueTime the value for secpkitb.IssueTime
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public void setIssueTime(Date issueTime) {
        this.issueTime = issueTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column secpkitb.CurrPeriod
     *
     * @return the value of secpkitb.CurrPeriod
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public Date getCurrPeriod() {
        return currPeriod;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column secpkitb.CurrPeriod
     *
     * @param currPeriod the value for secpkitb.CurrPeriod
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public void setCurrPeriod(Date currPeriod) {
        this.currPeriod = currPeriod;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column secpkitb.Rsvd
     *
     * @return the value of secpkitb.Rsvd
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public String getRsvd() {
        return rsvd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column secpkitb.Rsvd
     *
     * @param rsvd the value for secpkitb.Rsvd
     *
     * @ibatorgenerated Mon May 30 16:49:12 CST 2016
     */
    public void setRsvd(String rsvd) {
        this.rsvd = rsvd == null ? null : rsvd.trim();
    }

}
