package com.blue.travel.detail;

import com.eis.base.BaseForm;

public class TravelDetailForm extends BaseForm {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column travel_detail.TDETAIL_ID
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    private Long tdetailId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column travel_detail.EXPENSES_ID
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    private Long expensesId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column travel_detail.FROM_DATE
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    private String fromDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column travel_detail.TO_DATE
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    private String toDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column travel_detail.TRAVEL_FROM
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    private String travelFrom;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column travel_detail.TRAVEL_TO
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    private String travelTo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column travel_detail.TRANSPORT_MODE
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    private String transportMode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column travel_detail.INVOICENO
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    private Integer invoiceno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column travel_detail.FEE
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    private Double fee;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column travel_detail.TDETAIL_ID
     *
     * @return the value of travel_detail.TDETAIL_ID
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    public Long getTdetailId() {
        return tdetailId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column travel_detail.TDETAIL_ID
     *
     * @param tdetailId the value for travel_detail.TDETAIL_ID
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    public void setTdetailId(Long tdetailId) {
        this.tdetailId = tdetailId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column travel_detail.EXPENSES_ID
     *
     * @return the value of travel_detail.EXPENSES_ID
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    public Long getExpensesId() {
        return expensesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column travel_detail.EXPENSES_ID
     *
     * @param expensesId the value for travel_detail.EXPENSES_ID
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    public void setExpensesId(Long expensesId) {
        this.expensesId = expensesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column travel_detail.FROM_DATE
     *
     * @return the value of travel_detail.FROM_DATE
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    public String getFromDate() {
        return fromDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column travel_detail.FROM_DATE
     *
     * @param fromDate the value for travel_detail.FROM_DATE
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    public void setFromDate(String fromDate) {
        this.fromDate = fromDate == null ? null : fromDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column travel_detail.TO_DATE
     *
     * @return the value of travel_detail.TO_DATE
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    public String getToDate() {
        return toDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column travel_detail.TO_DATE
     *
     * @param toDate the value for travel_detail.TO_DATE
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    public void setToDate(String toDate) {
        this.toDate = toDate == null ? null : toDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column travel_detail.TRAVEL_FROM
     *
     * @return the value of travel_detail.TRAVEL_FROM
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    public String getTravelFrom() {
        return travelFrom;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column travel_detail.TRAVEL_FROM
     *
     * @param travelFrom the value for travel_detail.TRAVEL_FROM
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    public void setTravelFrom(String travelFrom) {
        this.travelFrom = travelFrom == null ? null : travelFrom.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column travel_detail.TRAVEL_TO
     *
     * @return the value of travel_detail.TRAVEL_TO
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    public String getTravelTo() {
        return travelTo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column travel_detail.TRAVEL_TO
     *
     * @param travelTo the value for travel_detail.TRAVEL_TO
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    public void setTravelTo(String travelTo) {
        this.travelTo = travelTo == null ? null : travelTo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column travel_detail.TRANSPORT_MODE
     *
     * @return the value of travel_detail.TRANSPORT_MODE
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    public String getTransportMode() {
        return transportMode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column travel_detail.TRANSPORT_MODE
     *
     * @param transportMode the value for travel_detail.TRANSPORT_MODE
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    public void setTransportMode(String transportMode) {
        this.transportMode = transportMode == null ? null : transportMode.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column travel_detail.INVOICENO
     *
     * @return the value of travel_detail.INVOICENO
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    public Integer getInvoiceno() {
        return invoiceno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column travel_detail.INVOICENO
     *
     * @param invoiceno the value for travel_detail.INVOICENO
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    public void setInvoiceno(Integer invoiceno) {
        this.invoiceno = invoiceno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column travel_detail.FEE
     *
     * @return the value of travel_detail.FEE
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    public Double getFee() {
        return fee;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column travel_detail.FEE
     *
     * @param fee the value for travel_detail.FEE
     *
     * @ibatorgenerated Mon Mar 31 15:26:29 CST 2014
     */
    public void setFee(Double fee) {
        this.fee = fee;
    }
}