package com.blue.version.reportchg;

public class ReportChg {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column report_chg.ID
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column report_chg.REPORT_NAME
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private String reportName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column report_chg.SUB_SYS
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private String subSys;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column report_chg.CHG_TYPE
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private String chgType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column report_chg.ORIGINL
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private String originl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column report_chg.TARGET
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private String target;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column report_chg.LOCATION
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private String location;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column report_chg.VERSION_ID
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private String versionId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column report_chg.ID
     *
     * @return the value of report_chg.ID
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column report_chg.ID
     *
     * @param id the value for report_chg.ID
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column report_chg.REPORT_NAME
     *
     * @return the value of report_chg.REPORT_NAME
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public String getReportName() {
        return reportName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column report_chg.REPORT_NAME
     *
     * @param reportName the value for report_chg.REPORT_NAME
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void setReportName(String reportName) {
        this.reportName = reportName == null ? null : reportName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column report_chg.SUB_SYS
     *
     * @return the value of report_chg.SUB_SYS
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public String getSubSys() {
        return subSys;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column report_chg.SUB_SYS
     *
     * @param subSys the value for report_chg.SUB_SYS
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void setSubSys(String subSys) {
        this.subSys = subSys == null ? null : subSys.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column report_chg.CHG_TYPE
     *
     * @return the value of report_chg.CHG_TYPE
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public String getChgType() {
        return chgType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column report_chg.CHG_TYPE
     *
     * @param chgType the value for report_chg.CHG_TYPE
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void setChgType(String chgType) {
        this.chgType = chgType == null ? null : chgType.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column report_chg.ORIGINL
     *
     * @return the value of report_chg.ORIGINL
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public String getOriginl() {
        return originl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column report_chg.ORIGINL
     *
     * @param originl the value for report_chg.ORIGINL
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void setOriginl(String originl) {
        this.originl = originl == null ? null : originl.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column report_chg.TARGET
     *
     * @return the value of report_chg.TARGET
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column report_chg.TARGET
     *
     * @param target the value for report_chg.TARGET
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column report_chg.LOCATION
     *
     * @return the value of report_chg.LOCATION
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column report_chg.LOCATION
     *
     * @param location the value for report_chg.LOCATION
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column report_chg.VERSION_ID
     *
     * @return the value of report_chg.VERSION_ID
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public String getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column report_chg.VERSION_ID
     *
     * @param versionId the value for report_chg.VERSION_ID
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void setVersionId(String versionId) {
        this.versionId = versionId == null ? null : versionId.trim();
    }
}