package com.blue.version.reportchg;

import com.blue.version.reportchg.ReportChg;
import com.blue.version.reportchg.ReportChgExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ReportChgDAOImpl extends SqlMapClientDaoSupport implements ReportChgDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public ReportChgDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int countByExample(ReportChgExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("report_chg.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int deleteByExample(ReportChgExample example) {
        int rows = getSqlMapClientTemplate().delete("report_chg.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int deleteByPrimaryKey(Long id) {
        ReportChg key = new ReportChg();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("report_chg.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void insert(ReportChg record) {
        getSqlMapClientTemplate().insert("report_chg.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public void insertSelective(ReportChg record) {
        getSqlMapClientTemplate().insert("report_chg.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public List selectByExample(ReportChgExample example) {
        List list = getSqlMapClientTemplate().queryForList("report_chg.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public ReportChg selectByPrimaryKey(Long id) {
        ReportChg key = new ReportChg();
        key.setId(id);
        ReportChg record = (ReportChg) getSqlMapClientTemplate().queryForObject("report_chg.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int updateByExampleSelective(ReportChg record, ReportChgExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("report_chg.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int updateByExample(ReportChg record, ReportChgExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("report_chg.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int updateByPrimaryKeySelective(ReportChg record) {
        int rows = getSqlMapClientTemplate().update("report_chg.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    public int updateByPrimaryKey(ReportChg record) {
        int rows = getSqlMapClientTemplate().update("report_chg.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    private static class UpdateByExampleParms extends ReportChgExample {
        private Object record;

        public UpdateByExampleParms(Object record, ReportChgExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}