package com.blue.version.reportchg;

import com.blue.version.reportchg.ReportChg;
import com.blue.version.reportchg.ReportChgExample;
import java.util.List;

public interface ReportChgDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    int countByExample(ReportChgExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    int deleteByExample(ReportChgExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    void insert(ReportChg record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    void insertSelective(ReportChg record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    List selectByExample(ReportChgExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    ReportChg selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    int updateByExampleSelective(ReportChg record, ReportChgExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    int updateByExample(ReportChg record, ReportChgExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    int updateByPrimaryKeySelective(ReportChg record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table report_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    int updateByPrimaryKey(ReportChg record);
}