package com.blue.projectchgrecord;

import com.blue.projectchgrecord.ChangeDetail;
import com.blue.projectchgrecord.ChangeDetailExample;
import java.util.List;

public interface ChangeDetailDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table change_detail
     *
     * @ibatorgenerated Tue Jan 08 15:32:41 CST 2013
     */
    int countByExample(ChangeDetailExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table change_detail
     *
     * @ibatorgenerated Tue Jan 08 15:32:41 CST 2013
     */
    int deleteByExample(ChangeDetailExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table change_detail
     *
     * @ibatorgenerated Tue Jan 08 15:32:41 CST 2013
     */
    int deleteByPrimaryKey(Long detailId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table change_detail
     *
     * @ibatorgenerated Tue Jan 08 15:32:41 CST 2013
     */
    void insert(ChangeDetail record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table change_detail
     *
     * @ibatorgenerated Tue Jan 08 15:32:41 CST 2013
     */
    void insertSelective(ChangeDetail record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table change_detail
     *
     * @ibatorgenerated Tue Jan 08 15:32:41 CST 2013
     */
    List selectByExample(ChangeDetailExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table change_detail
     *
     * @ibatorgenerated Tue Jan 08 15:32:41 CST 2013
     */
    ChangeDetail selectByPrimaryKey(Long detailId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table change_detail
     *
     * @ibatorgenerated Tue Jan 08 15:32:41 CST 2013
     */
    int updateByExampleSelective(ChangeDetail record, ChangeDetailExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table change_detail
     *
     * @ibatorgenerated Tue Jan 08 15:32:41 CST 2013
     */
    int updateByExample(ChangeDetail record, ChangeDetailExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table change_detail
     *
     * @ibatorgenerated Tue Jan 08 15:32:41 CST 2013
     */
    int updateByPrimaryKeySelective(ChangeDetail record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table change_detail
     *
     * @ibatorgenerated Tue Jan 08 15:32:41 CST 2013
     */
    int updateByPrimaryKey(ChangeDetail record);
}