package com.blue.mile;

import com.blue.mile.MileStone;
import com.blue.mile.MileStoneExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class MileStoneDAOImpl extends SqlMapClientDaoSupport implements MileStoneDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mile_stone
     *
     * @ibatorgenerated Mon Sep 10 13:51:14 CST 2012
     */
    public MileStoneDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mile_stone
     *
     * @ibatorgenerated Mon Sep 10 13:51:14 CST 2012
     */
    public int countByExample(MileStoneExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("mile_stone.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mile_stone
     *
     * @ibatorgenerated Mon Sep 10 13:51:14 CST 2012
     */
    public int deleteByExample(MileStoneExample example) {
        int rows = getSqlMapClientTemplate().delete("mile_stone.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mile_stone
     *
     * @ibatorgenerated Mon Sep 10 13:51:14 CST 2012
     */
    public int deleteByPrimaryKey(Long mileStoneId) {
        MileStone key = new MileStone();
        key.setMileStoneId(mileStoneId);
        int rows = getSqlMapClientTemplate().delete("mile_stone.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mile_stone
     *
     * @ibatorgenerated Mon Sep 10 13:51:14 CST 2012
     */
    public void insert(MileStone record) {
        getSqlMapClientTemplate().insert("mile_stone.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mile_stone
     *
     * @ibatorgenerated Mon Sep 10 13:51:14 CST 2012
     */
    public void insertSelective(MileStone record) {
        getSqlMapClientTemplate().insert("mile_stone.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mile_stone
     *
     * @ibatorgenerated Mon Sep 10 13:51:14 CST 2012
     */
    public List selectByExample(MileStoneExample example) {
        List list = getSqlMapClientTemplate().queryForList("mile_stone.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mile_stone
     *
     * @ibatorgenerated Mon Sep 10 13:51:14 CST 2012
     */
    public MileStone selectByPrimaryKey(Long mileStoneId) {
        MileStone key = new MileStone();
        key.setMileStoneId(mileStoneId);
        MileStone record = (MileStone) getSqlMapClientTemplate().queryForObject("mile_stone.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mile_stone
     *
     * @ibatorgenerated Mon Sep 10 13:51:14 CST 2012
     */
    public int updateByExampleSelective(MileStone record, MileStoneExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("mile_stone.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mile_stone
     *
     * @ibatorgenerated Mon Sep 10 13:51:14 CST 2012
     */
    public int updateByExample(MileStone record, MileStoneExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("mile_stone.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mile_stone
     *
     * @ibatorgenerated Mon Sep 10 13:51:14 CST 2012
     */
    public int updateByPrimaryKeySelective(MileStone record) {
        int rows = getSqlMapClientTemplate().update("mile_stone.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mile_stone
     *
     * @ibatorgenerated Mon Sep 10 13:51:14 CST 2012
     */
    public int updateByPrimaryKey(MileStone record) {
        int rows = getSqlMapClientTemplate().update("mile_stone.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table mile_stone
     *
     * @ibatorgenerated Mon Sep 10 13:51:14 CST 2012
     */
    private static class UpdateByExampleParms extends MileStoneExample {
        private Object record;

        public UpdateByExampleParms(Object record, MileStoneExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}