package com.blue.otherdaily;

import com.blue.otherdaily.OtherDaily;
import com.blue.otherdaily.OtherDailyExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class OtherDailyDAOImpl extends SqlMapClientDaoSupport implements OtherDailyDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_daily
     *
     * @ibatorgenerated Wed Feb 06 15:57:52 CST 2013
     */
    public OtherDailyDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_daily
     *
     * @ibatorgenerated Wed Feb 06 15:57:52 CST 2013
     */
    public int countByExample(OtherDailyExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("other_daily.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_daily
     *
     * @ibatorgenerated Wed Feb 06 15:57:52 CST 2013
     */
    public int deleteByExample(OtherDailyExample example) {
        int rows = getSqlMapClientTemplate().delete("other_daily.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_daily
     *
     * @ibatorgenerated Wed Feb 06 15:57:52 CST 2013
     */
    public int deleteByPrimaryKey(Long id) {
        OtherDaily key = new OtherDaily();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("other_daily.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_daily
     *
     * @ibatorgenerated Wed Feb 06 15:57:52 CST 2013
     */
    public void insert(OtherDaily record) {
        getSqlMapClientTemplate().insert("other_daily.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_daily
     *
     * @ibatorgenerated Wed Feb 06 15:57:52 CST 2013
     */
    public void insertSelective(OtherDaily record) {
        getSqlMapClientTemplate().insert("other_daily.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_daily
     *
     * @ibatorgenerated Wed Feb 06 15:57:52 CST 2013
     */
    public List selectByExample(OtherDailyExample example) {
        List list = getSqlMapClientTemplate().queryForList("other_daily.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_daily
     *
     * @ibatorgenerated Wed Feb 06 15:57:52 CST 2013
     */
    public OtherDaily selectByPrimaryKey(Long id) {
        OtherDaily key = new OtherDaily();
        key.setId(id);
        OtherDaily record = (OtherDaily) getSqlMapClientTemplate().queryForObject("other_daily.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_daily
     *
     * @ibatorgenerated Wed Feb 06 15:57:52 CST 2013
     */
    public int updateByExampleSelective(OtherDaily record, OtherDailyExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("other_daily.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_daily
     *
     * @ibatorgenerated Wed Feb 06 15:57:52 CST 2013
     */
    public int updateByExample(OtherDaily record, OtherDailyExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("other_daily.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_daily
     *
     * @ibatorgenerated Wed Feb 06 15:57:52 CST 2013
     */
    public int updateByPrimaryKeySelective(OtherDaily record) {
        int rows = getSqlMapClientTemplate().update("other_daily.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_daily
     *
     * @ibatorgenerated Wed Feb 06 15:57:52 CST 2013
     */
    public int updateByPrimaryKey(OtherDaily record) {
        int rows = getSqlMapClientTemplate().update("other_daily.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table other_daily
     *
     * @ibatorgenerated Wed Feb 06 15:57:52 CST 2013
     */
    private static class UpdateByExampleParms extends OtherDailyExample {
        private Object record;

        public UpdateByExampleParms(Object record, OtherDailyExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}