package com.blue.budget;

import com.blue.budget.BudgetInfo;
import com.blue.budget.BudgetInfoExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class BudgetInfoDAOImpl extends SqlMapClientDaoSupport implements BudgetInfoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table budget_info
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public BudgetInfoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table budget_info
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public int countByExample(BudgetInfoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("budget_info.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table budget_info
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public int deleteByExample(BudgetInfoExample example) {
        int rows = getSqlMapClientTemplate().delete("budget_info.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table budget_info
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public int deleteByPrimaryKey(Long budgetId) {
        BudgetInfo key = new BudgetInfo();
        key.setBudgetId(budgetId);
        int rows = getSqlMapClientTemplate().delete("budget_info.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table budget_info
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public void insert(BudgetInfo record) {
        getSqlMapClientTemplate().insert("budget_info.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table budget_info
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public void insertSelective(BudgetInfo record) {
        getSqlMapClientTemplate().insert("budget_info.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table budget_info
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public List selectByExample(BudgetInfoExample example) {
        List list = getSqlMapClientTemplate().queryForList("budget_info.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table budget_info
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public BudgetInfo selectByPrimaryKey(Long budgetId) {
        BudgetInfo key = new BudgetInfo();
        key.setBudgetId(budgetId);
        BudgetInfo record = (BudgetInfo) getSqlMapClientTemplate().queryForObject("budget_info.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table budget_info
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public int updateByExampleSelective(BudgetInfo record, BudgetInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("budget_info.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table budget_info
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public int updateByExample(BudgetInfo record, BudgetInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("budget_info.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table budget_info
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public int updateByPrimaryKeySelective(BudgetInfo record) {
        int rows = getSqlMapClientTemplate().update("budget_info.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table budget_info
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    public int updateByPrimaryKey(BudgetInfo record) {
        int rows = getSqlMapClientTemplate().update("budget_info.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table budget_info
     *
     * @ibatorgenerated Wed Apr 02 17:59:32 CST 2014
     */
    private static class UpdateByExampleParms extends BudgetInfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, BudgetInfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}