package com.yly.discard;

public class Disproduct {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.SamId
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private String samId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.SamCSN
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private String samCSN;
    private String samId_min;
    public String getSamId_min() {
		return samId_min;
	}

	public void setSamId_min(String samId_min) {
		this.samId_min = samId_min;
	}

	public String getSamId_max() {
		return samId_max;
	}

	public void setSamId_max(String samId_max) {
		this.samId_max = samId_max;
	}

	private String samId_max;
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.OAappNo
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private String OAappNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.ProdId
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private String prodId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.PhiTypeId
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private String phiTypeId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.AppTypeId
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private String appTypeId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.KeyType
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private Short keyType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.BinFileVer
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private String binFileVer;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.ManufacId
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private String manufacId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.BatchId
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private String batchId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.WkState
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private Short wkState;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.WkStateChgDate
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private String wkStateChgDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.IOState
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private Short IOState;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.IOStateChgDate
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private String IOStateChgDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.ReuseTime
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private Short reuseTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.UnitId
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private Integer unitId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.IssueTime
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private String issueTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.DetectSign
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private Short detectSign;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.DetectTime
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private String detectTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.PaymentType
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private Short paymentType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.ConsumeType
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private Short consumeType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.W2Sign
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private Short w2Sign;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.AuthSign
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private Short authSign;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.UnitPrice
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private Long unitPrice;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.PurchuseDate
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private String purchuseDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.CardPhyStat
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private Short cardPhyStat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column disproduct.Remarks
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private String remarks;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.SamId
     *
     * @return the value of disproduct.SamId
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public String getSamId() {
        return samId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.SamId
     *
     * @param samId the value for disproduct.SamId
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setSamId(String samId) {
        this.samId = samId == null ? null : samId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.SamCSN
     *
     * @return the value of disproduct.SamCSN
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public String getSamCSN() {
        return samCSN;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.SamCSN
     *
     * @param samCSN the value for disproduct.SamCSN
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setSamCSN(String samCSN) {
        this.samCSN = samCSN == null ? null : samCSN.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.OAappNo
     *
     * @return the value of disproduct.OAappNo
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public String getOAappNo() {
        return OAappNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.OAappNo
     *
     * @param OAappNo the value for disproduct.OAappNo
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setOAappNo(String OAappNo) {
        this.OAappNo = OAappNo == null ? null : OAappNo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.ProdId
     *
     * @return the value of disproduct.ProdId
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public String getProdId() {
        return prodId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.ProdId
     *
     * @param prodId the value for disproduct.ProdId
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setProdId(String prodId) {
        this.prodId = prodId == null ? null : prodId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.PhiTypeId
     *
     * @return the value of disproduct.PhiTypeId
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public String getPhiTypeId() {
        return phiTypeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.PhiTypeId
     *
     * @param phiTypeId the value for disproduct.PhiTypeId
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setPhiTypeId(String phiTypeId) {
        this.phiTypeId = phiTypeId == null ? null : phiTypeId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.AppTypeId
     *
     * @return the value of disproduct.AppTypeId
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public String getAppTypeId() {
        return appTypeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.AppTypeId
     *
     * @param appTypeId the value for disproduct.AppTypeId
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setAppTypeId(String appTypeId) {
        this.appTypeId = appTypeId == null ? null : appTypeId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.KeyType
     *
     * @return the value of disproduct.KeyType
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public Short getKeyType() {
        return keyType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.KeyType
     *
     * @param keyType the value for disproduct.KeyType
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setKeyType(Short keyType) {
        this.keyType = keyType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.BinFileVer
     *
     * @return the value of disproduct.BinFileVer
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public String getBinFileVer() {
        return binFileVer;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.BinFileVer
     *
     * @param binFileVer the value for disproduct.BinFileVer
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setBinFileVer(String binFileVer) {
        this.binFileVer = binFileVer == null ? null : binFileVer.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.ManufacId
     *
     * @return the value of disproduct.ManufacId
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public String getManufacId() {
        return manufacId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.ManufacId
     *
     * @param manufacId the value for disproduct.ManufacId
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setManufacId(String manufacId) {
        this.manufacId = manufacId == null ? null : manufacId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.BatchId
     *
     * @return the value of disproduct.BatchId
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.BatchId
     *
     * @param batchId the value for disproduct.BatchId
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId == null ? null : batchId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.WkState
     *
     * @return the value of disproduct.WkState
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public Short getWkState() {
        return wkState;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.WkState
     *
     * @param wkState the value for disproduct.WkState
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setWkState(Short wkState) {
        this.wkState = wkState;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.WkStateChgDate
     *
     * @return the value of disproduct.WkStateChgDate
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public String getWkStateChgDate() {
        return wkStateChgDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.WkStateChgDate
     *
     * @param wkStateChgDate the value for disproduct.WkStateChgDate
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setWkStateChgDate(String wkStateChgDate) {
        this.wkStateChgDate = wkStateChgDate == null ? null : wkStateChgDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.IOState
     *
     * @return the value of disproduct.IOState
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public Short getIOState() {
        return IOState;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.IOState
     *
     * @param IOState the value for disproduct.IOState
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setIOState(Short IOState) {
        this.IOState = IOState;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.IOStateChgDate
     *
     * @return the value of disproduct.IOStateChgDate
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public String getIOStateChgDate() {
        return IOStateChgDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.IOStateChgDate
     *
     * @param IOStateChgDate the value for disproduct.IOStateChgDate
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setIOStateChgDate(String IOStateChgDate) {
        this.IOStateChgDate = IOStateChgDate == null ? null : IOStateChgDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.ReuseTime
     *
     * @return the value of disproduct.ReuseTime
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public Short getReuseTime() {
        return reuseTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.ReuseTime
     *
     * @param reuseTime the value for disproduct.ReuseTime
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setReuseTime(Short reuseTime) {
        this.reuseTime = reuseTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.UnitId
     *
     * @return the value of disproduct.UnitId
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public Integer getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.UnitId
     *
     * @param unitId the value for disproduct.UnitId
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.IssueTime
     *
     * @return the value of disproduct.IssueTime
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public String getIssueTime() {
        return issueTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.IssueTime
     *
     * @param issueTime the value for disproduct.IssueTime
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setIssueTime(String issueTime) {
        this.issueTime = issueTime == null ? null : issueTime.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.DetectSign
     *
     * @return the value of disproduct.DetectSign
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public Short getDetectSign() {
        return detectSign;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.DetectSign
     *
     * @param detectSign the value for disproduct.DetectSign
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setDetectSign(Short detectSign) {
        this.detectSign = detectSign;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.DetectTime
     *
     * @return the value of disproduct.DetectTime
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public String getDetectTime() {
        return detectTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.DetectTime
     *
     * @param detectTime the value for disproduct.DetectTime
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setDetectTime(String detectTime) {
        this.detectTime = detectTime == null ? null : detectTime.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.PaymentType
     *
     * @return the value of disproduct.PaymentType
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public Short getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.PaymentType
     *
     * @param paymentType the value for disproduct.PaymentType
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setPaymentType(Short paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.ConsumeType
     *
     * @return the value of disproduct.ConsumeType
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public Short getConsumeType() {
        return consumeType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.ConsumeType
     *
     * @param consumeType the value for disproduct.ConsumeType
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setConsumeType(Short consumeType) {
        this.consumeType = consumeType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.W2Sign
     *
     * @return the value of disproduct.W2Sign
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public Short getW2Sign() {
        return w2Sign;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.W2Sign
     *
     * @param w2Sign the value for disproduct.W2Sign
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setW2Sign(Short w2Sign) {
        this.w2Sign = w2Sign;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.AuthSign
     *
     * @return the value of disproduct.AuthSign
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public Short getAuthSign() {
        return authSign;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.AuthSign
     *
     * @param authSign the value for disproduct.AuthSign
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setAuthSign(Short authSign) {
        this.authSign = authSign;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.UnitPrice
     *
     * @return the value of disproduct.UnitPrice
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public Long getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.UnitPrice
     *
     * @param unitPrice the value for disproduct.UnitPrice
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setUnitPrice(Long unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.PurchuseDate
     *
     * @return the value of disproduct.PurchuseDate
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public String getPurchuseDate() {
        return purchuseDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.PurchuseDate
     *
     * @param purchuseDate the value for disproduct.PurchuseDate
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setPurchuseDate(String purchuseDate) {
        this.purchuseDate = purchuseDate == null ? null : purchuseDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.CardPhyStat
     *
     * @return the value of disproduct.CardPhyStat
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public Short getCardPhyStat() {
        return cardPhyStat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.CardPhyStat
     *
     * @param cardPhyStat the value for disproduct.CardPhyStat
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setCardPhyStat(Short cardPhyStat) {
        this.cardPhyStat = cardPhyStat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column disproduct.Remarks
     *
     * @return the value of disproduct.Remarks
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column disproduct.Remarks
     *
     * @param remarks the value for disproduct.Remarks
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
	private String BatchIdParts;
    public String getBatchIdParts() {
		return BatchIdParts;
	}

	public void setBatchIdParts(String batchIdParts) {
		BatchIdParts = batchIdParts;
	}

}