package com.yly.discard;

import com.yly.discard.Disproduct;
import com.yly.discard.DisproductExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class DisproductDAOImpl extends SqlMapClientDaoSupport implements DisproductDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table disproduct
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public DisproductDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table disproduct
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public int countByExample(DisproductExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("disproduct.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table disproduct
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public int deleteByExample(DisproductExample example) {
        int rows = getSqlMapClientTemplate().delete("disproduct.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table disproduct
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public int deleteByPrimaryKey(String samId) {
        Disproduct key = new Disproduct();
        key.setSamId(samId);
        int rows = getSqlMapClientTemplate().delete("disproduct.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table disproduct
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void insert(Disproduct record) {
        getSqlMapClientTemplate().insert("disproduct.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table disproduct
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public void insertSelective(Disproduct record) {
        getSqlMapClientTemplate().insert("disproduct.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table disproduct
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public List selectByExample(DisproductExample example) {
        List list = getSqlMapClientTemplate().queryForList("disproduct.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table disproduct
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public Disproduct selectByPrimaryKey(String samId) {
        Disproduct key = new Disproduct();
        key.setSamId(samId);
        Disproduct record = (Disproduct) getSqlMapClientTemplate().queryForObject("disproduct.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table disproduct
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public int updateByExampleSelective(Disproduct record, DisproductExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("disproduct.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table disproduct
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public int updateByExample(Disproduct record, DisproductExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("disproduct.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table disproduct
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public int updateByPrimaryKeySelective(Disproduct record) {
        int rows = getSqlMapClientTemplate().update("disproduct.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table disproduct
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    public int updateByPrimaryKey(Disproduct record) {
        int rows = getSqlMapClientTemplate().update("disproduct.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table disproduct
     *
     * @ibatorgenerated Thu May 26 17:56:20 CST 2016
     */
    private static class UpdateByExampleParms extends DisproductExample {
        private Object record;

        public UpdateByExampleParms(Object record, DisproductExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}