package com.blue.version.codechg;

import com.blue.version.codechg.CodeChg;
import com.blue.version.codechg.CodeChgExample;
import java.util.List;

public interface CodeChgDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table code_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    int countByExample(CodeChgExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table code_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    int deleteByExample(CodeChgExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table code_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table code_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    void insert(CodeChg record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table code_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    void insertSelective(CodeChg record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table code_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    List selectByExample(CodeChgExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table code_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    CodeChg selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table code_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    int updateByExampleSelective(CodeChg record, CodeChgExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table code_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    int updateByExample(CodeChg record, CodeChgExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table code_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    int updateByPrimaryKeySelective(CodeChg record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table code_chg
     *
     * @ibatorgenerated Thu Mar 21 09:59:31 CST 2013
     */
    int updateByPrimaryKey(CodeChg record);
}