package com.blue.projectdistribute;

public class ProjectDistribute {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_distribute.ID
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_distribute.PROJECT_ID
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    private String projectId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_distribute.USER_ID
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    private String userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_distribute.STEP
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    private String step;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_distribute.START_DATE
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    private String startDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_distribute.END_DATE
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    private String endDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_distribute.PERCENT
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    private Integer percent;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_distribute.IS_DONE
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    private String isDone;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_distribute.MEMO
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    private String memo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_distribute.FINAL_END_DATE
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    private String finalEndDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_distribute.MILE_STONE_ID
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    private Long mileStoneId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_distribute.TASK_NAME
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    private String taskName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_distribute.ACTION_ID
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    private Integer actionId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column project_distribute.MODULE_ID
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    private String moduleId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column project_distribute.ID
     *
     * @return the value of project_distribute.ID
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column project_distribute.ID
     *
     * @param id the value for project_distribute.ID
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column project_distribute.PROJECT_ID
     *
     * @return the value of project_distribute.PROJECT_ID
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column project_distribute.PROJECT_ID
     *
     * @param projectId the value for project_distribute.PROJECT_ID
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column project_distribute.USER_ID
     *
     * @return the value of project_distribute.USER_ID
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column project_distribute.USER_ID
     *
     * @param userId the value for project_distribute.USER_ID
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column project_distribute.STEP
     *
     * @return the value of project_distribute.STEP
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public String getStep() {
        return step;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column project_distribute.STEP
     *
     * @param step the value for project_distribute.STEP
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public void setStep(String step) {
        this.step = step == null ? null : step.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column project_distribute.START_DATE
     *
     * @return the value of project_distribute.START_DATE
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column project_distribute.START_DATE
     *
     * @param startDate the value for project_distribute.START_DATE
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate == null ? null : startDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column project_distribute.END_DATE
     *
     * @return the value of project_distribute.END_DATE
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column project_distribute.END_DATE
     *
     * @param endDate the value for project_distribute.END_DATE
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column project_distribute.PERCENT
     *
     * @return the value of project_distribute.PERCENT
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public Integer getPercent() {
        return percent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column project_distribute.PERCENT
     *
     * @param percent the value for project_distribute.PERCENT
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public void setPercent(Integer percent) {
        this.percent = percent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column project_distribute.IS_DONE
     *
     * @return the value of project_distribute.IS_DONE
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public String getIsDone() {
        return isDone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column project_distribute.IS_DONE
     *
     * @param isDone the value for project_distribute.IS_DONE
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public void setIsDone(String isDone) {
        this.isDone = isDone == null ? null : isDone.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column project_distribute.MEMO
     *
     * @return the value of project_distribute.MEMO
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column project_distribute.MEMO
     *
     * @param memo the value for project_distribute.MEMO
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column project_distribute.FINAL_END_DATE
     *
     * @return the value of project_distribute.FINAL_END_DATE
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public String getFinalEndDate() {
        return finalEndDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column project_distribute.FINAL_END_DATE
     *
     * @param finalEndDate the value for project_distribute.FINAL_END_DATE
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public void setFinalEndDate(String finalEndDate) {
        this.finalEndDate = finalEndDate == null ? null : finalEndDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column project_distribute.MILE_STONE_ID
     *
     * @return the value of project_distribute.MILE_STONE_ID
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public Long getMileStoneId() {
        return mileStoneId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column project_distribute.MILE_STONE_ID
     *
     * @param mileStoneId the value for project_distribute.MILE_STONE_ID
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public void setMileStoneId(Long mileStoneId) {
        this.mileStoneId = mileStoneId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column project_distribute.TASK_NAME
     *
     * @return the value of project_distribute.TASK_NAME
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column project_distribute.TASK_NAME
     *
     * @param taskName the value for project_distribute.TASK_NAME
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column project_distribute.ACTION_ID
     *
     * @return the value of project_distribute.ACTION_ID
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public Integer getActionId() {
        return actionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column project_distribute.ACTION_ID
     *
     * @param actionId the value for project_distribute.ACTION_ID
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public void setActionId(Integer actionId) {
        this.actionId = actionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column project_distribute.MODULE_ID
     *
     * @return the value of project_distribute.MODULE_ID
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column project_distribute.MODULE_ID
     *
     * @param moduleId the value for project_distribute.MODULE_ID
     *
     * @ibatorgenerated Fri Aug 02 16:26:25 CST 2013
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId == null ? null : moduleId.trim();
    }
}