package com.blue.scale;

import com.blue.scale.ActionDef;
import com.blue.scale.ActionDefExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ActionDefDAOImpl extends SqlMapClientDaoSupport implements ActionDefDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table action_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public ActionDefDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table action_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public int countByExample(ActionDefExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("action_def.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table action_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public int deleteByExample(ActionDefExample example) {
        int rows = getSqlMapClientTemplate().delete("action_def.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table action_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public int deleteByPrimaryKey(Integer actionId) {
        ActionDef key = new ActionDef();
        key.setActionId(actionId);
        int rows = getSqlMapClientTemplate().delete("action_def.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table action_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public void insert(ActionDef record) {
        getSqlMapClientTemplate().insert("action_def.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table action_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public void insertSelective(ActionDef record) {
        getSqlMapClientTemplate().insert("action_def.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table action_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public List selectByExample(ActionDefExample example) {
        List list = getSqlMapClientTemplate().queryForList("action_def.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table action_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public ActionDef selectByPrimaryKey(Integer actionId) {
        ActionDef key = new ActionDef();
        key.setActionId(actionId);
        ActionDef record = (ActionDef) getSqlMapClientTemplate().queryForObject("action_def.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table action_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public int updateByExampleSelective(ActionDef record, ActionDefExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("action_def.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table action_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public int updateByExample(ActionDef record, ActionDefExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("action_def.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table action_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public int updateByPrimaryKeySelective(ActionDef record) {
        int rows = getSqlMapClientTemplate().update("action_def.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table action_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public int updateByPrimaryKey(ActionDef record) {
        int rows = getSqlMapClientTemplate().update("action_def.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table action_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    private static class UpdateByExampleParms extends ActionDefExample {
        private Object record;

        public UpdateByExampleParms(Object record, ActionDefExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}