package com.blue.scale;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ScaleDefExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public ScaleDefExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    protected ScaleDefExample(ScaleDefExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andScaleIdIsNull() {
            addCriterion("SCALE_ID is null");
            return this;
        }

        public Criteria andScaleIdIsNotNull() {
            addCriterion("SCALE_ID is not null");
            return this;
        }

        public Criteria andScaleIdEqualTo(Integer value) {
            addCriterion("SCALE_ID =", value, "scaleId");
            return this;
        }

        public Criteria andScaleIdNotEqualTo(Integer value) {
            addCriterion("SCALE_ID <>", value, "scaleId");
            return this;
        }

        public Criteria andScaleIdGreaterThan(Integer value) {
            addCriterion("SCALE_ID >", value, "scaleId");
            return this;
        }

        public Criteria andScaleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("SCALE_ID >=", value, "scaleId");
            return this;
        }

        public Criteria andScaleIdLessThan(Integer value) {
            addCriterion("SCALE_ID <", value, "scaleId");
            return this;
        }

        public Criteria andScaleIdLessThanOrEqualTo(Integer value) {
            addCriterion("SCALE_ID <=", value, "scaleId");
            return this;
        }

        public Criteria andScaleIdIn(List values) {
            addCriterion("SCALE_ID in", values, "scaleId");
            return this;
        }

        public Criteria andScaleIdNotIn(List values) {
            addCriterion("SCALE_ID not in", values, "scaleId");
            return this;
        }

        public Criteria andScaleIdBetween(Integer value1, Integer value2) {
            addCriterion("SCALE_ID between", value1, value2, "scaleId");
            return this;
        }

        public Criteria andScaleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("SCALE_ID not between", value1, value2, "scaleId");
            return this;
        }

        public Criteria andScaleDescIsNull() {
            addCriterion("SCALE_DESC is null");
            return this;
        }

        public Criteria andScaleDescIsNotNull() {
            addCriterion("SCALE_DESC is not null");
            return this;
        }

        public Criteria andScaleDescEqualTo(String value) {
            addCriterion("SCALE_DESC =", value, "scaleDesc");
            return this;
        }

        public Criteria andScaleDescNotEqualTo(String value) {
            addCriterion("SCALE_DESC <>", value, "scaleDesc");
            return this;
        }

        public Criteria andScaleDescGreaterThan(String value) {
            addCriterion("SCALE_DESC >", value, "scaleDesc");
            return this;
        }

        public Criteria andScaleDescGreaterThanOrEqualTo(String value) {
            addCriterion("SCALE_DESC >=", value, "scaleDesc");
            return this;
        }

        public Criteria andScaleDescLessThan(String value) {
            addCriterion("SCALE_DESC <", value, "scaleDesc");
            return this;
        }

        public Criteria andScaleDescLessThanOrEqualTo(String value) {
            addCriterion("SCALE_DESC <=", value, "scaleDesc");
            return this;
        }

        public Criteria andScaleDescLike(String value) {
            addCriterion("SCALE_DESC like", value, "scaleDesc");
            return this;
        }

        public Criteria andScaleDescNotLike(String value) {
            addCriterion("SCALE_DESC not like", value, "scaleDesc");
            return this;
        }

        public Criteria andScaleDescIn(List values) {
            addCriterion("SCALE_DESC in", values, "scaleDesc");
            return this;
        }

        public Criteria andScaleDescNotIn(List values) {
            addCriterion("SCALE_DESC not in", values, "scaleDesc");
            return this;
        }

        public Criteria andScaleDescBetween(String value1, String value2) {
            addCriterion("SCALE_DESC between", value1, value2, "scaleDesc");
            return this;
        }

        public Criteria andScaleDescNotBetween(String value1, String value2) {
            addCriterion("SCALE_DESC not between", value1, value2, "scaleDesc");
            return this;
        }
    }
}