package com.blue.scale;

import com.blue.scale.ScaleDef;
import com.blue.scale.ScaleDefExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ScaleDefDAOImpl extends SqlMapClientDaoSupport implements ScaleDefDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public ScaleDefDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public int countByExample(ScaleDefExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("scale_def.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public int deleteByExample(ScaleDefExample example) {
        int rows = getSqlMapClientTemplate().delete("scale_def.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public int deleteByPrimaryKey(Integer scaleId) {
        ScaleDef key = new ScaleDef();
        key.setScaleId(scaleId);
        int rows = getSqlMapClientTemplate().delete("scale_def.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public void insert(ScaleDef record) {
        getSqlMapClientTemplate().insert("scale_def.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public void insertSelective(ScaleDef record) {
        getSqlMapClientTemplate().insert("scale_def.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public List selectByExampleWithBLOBs(ScaleDefExample example) {
        List list = getSqlMapClientTemplate().queryForList("scale_def.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public List selectByExampleWithoutBLOBs(ScaleDefExample example) {
        List list = getSqlMapClientTemplate().queryForList("scale_def.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public ScaleDef selectByPrimaryKey(Integer scaleId) {
        ScaleDef key = new ScaleDef();
        key.setScaleId(scaleId);
        ScaleDef record = (ScaleDef) getSqlMapClientTemplate().queryForObject("scale_def.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public int updateByExampleSelective(ScaleDef record, ScaleDefExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("scale_def.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public int updateByExampleWithBLOBs(ScaleDef record, ScaleDefExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("scale_def.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public int updateByExampleWithoutBLOBs(ScaleDef record, ScaleDefExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("scale_def.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public int updateByPrimaryKeySelective(ScaleDef record) {
        int rows = getSqlMapClientTemplate().update("scale_def.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public int updateByPrimaryKeyWithBLOBs(ScaleDef record) {
        int rows = getSqlMapClientTemplate().update("scale_def.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    public int updateByPrimaryKeyWithoutBLOBs(ScaleDef record) {
        int rows = getSqlMapClientTemplate().update("scale_def.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table scale_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    private static class UpdateByExampleParms extends ScaleDefExample {
        private Object record;

        public UpdateByExampleParms(Object record, ScaleDefExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}