package com.blue.version.versionhis;

public class VersionHis {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column version_his.VERSION_ID
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    private String versionId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column version_his.PLAN_RELEASE_DATE
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    private String planReleaseDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column version_his.IS_RELEASED
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    private String isReleased;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column version_his.RELEASE_DATE
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    private String releaseDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column version_his.IS_CHECKED
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    private String isChecked;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column version_his.INPUT_USER
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    private String inputUser;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column version_his.INPUT_DATE
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    private String inputDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column version_his.MEMO
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    private String memo;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column version_his.VERSION_ID
     *
     * @return the value of version_his.VERSION_ID
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    public String getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column version_his.VERSION_ID
     *
     * @param versionId the value for version_his.VERSION_ID
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    public void setVersionId(String versionId) {
        this.versionId = versionId == null ? null : versionId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column version_his.PLAN_RELEASE_DATE
     *
     * @return the value of version_his.PLAN_RELEASE_DATE
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    public String getPlanReleaseDate() {
        return planReleaseDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column version_his.PLAN_RELEASE_DATE
     *
     * @param planReleaseDate the value for version_his.PLAN_RELEASE_DATE
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    public void setPlanReleaseDate(String planReleaseDate) {
        this.planReleaseDate = planReleaseDate == null ? null : planReleaseDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column version_his.IS_RELEASED
     *
     * @return the value of version_his.IS_RELEASED
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    public String getIsReleased() {
        return isReleased;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column version_his.IS_RELEASED
     *
     * @param isReleased the value for version_his.IS_RELEASED
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    public void setIsReleased(String isReleased) {
        this.isReleased = isReleased == null ? null : isReleased.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column version_his.RELEASE_DATE
     *
     * @return the value of version_his.RELEASE_DATE
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    public String getReleaseDate() {
        return releaseDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column version_his.RELEASE_DATE
     *
     * @param releaseDate the value for version_his.RELEASE_DATE
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    public void setReleaseDate(String releaseDate) {
        this.releaseDate = releaseDate == null ? null : releaseDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column version_his.IS_CHECKED
     *
     * @return the value of version_his.IS_CHECKED
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    public String getIsChecked() {
        return isChecked;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column version_his.IS_CHECKED
     *
     * @param isChecked the value for version_his.IS_CHECKED
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    public void setIsChecked(String isChecked) {
        this.isChecked = isChecked == null ? null : isChecked.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column version_his.INPUT_USER
     *
     * @return the value of version_his.INPUT_USER
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    public String getInputUser() {
        return inputUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column version_his.INPUT_USER
     *
     * @param inputUser the value for version_his.INPUT_USER
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    public void setInputUser(String inputUser) {
        this.inputUser = inputUser == null ? null : inputUser.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column version_his.INPUT_DATE
     *
     * @return the value of version_his.INPUT_DATE
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    public String getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column version_his.INPUT_DATE
     *
     * @param inputDate the value for version_his.INPUT_DATE
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    public void setInputDate(String inputDate) {
        this.inputDate = inputDate == null ? null : inputDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column version_his.MEMO
     *
     * @return the value of version_his.MEMO
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column version_his.MEMO
     *
     * @param memo the value for version_his.MEMO
     *
     * @ibatorgenerated Fri Mar 29 14:22:23 CST 2013
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}