package com.blue.expenses.detail;

import java.util.Collection;

import com.eis.base.BaseForm;
import com.eis.cache.SingleDicMap;

public class ExpensesDetailForm extends BaseForm{
    
	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column expenses_detail.EDETAIL_ID
     *
     * @ibatorgenerated Thu Mar 20 18:34:48 CST 2014
     */
    private Long edetailId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column expenses_detail.EXPENSES_ID
     *
     * @ibatorgenerated Thu Mar 20 18:34:48 CST 2014
     */
    private Long expensesId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column expenses_detail.TIME
     *
     * @ibatorgenerated Thu Mar 20 18:34:48 CST 2014
     */
    private String time;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column expenses_detail.CONTENT
     *
     * @ibatorgenerated Thu Mar 20 18:34:48 CST 2014
     */
    private String content;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column expenses_detail.INVOICENO
     *
     * @ibatorgenerated Thu Mar 20 18:34:48 CST 2014
     */
    private Integer invoiceno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column expenses_detail.AMT
     *
     * @ibatorgenerated Thu Mar 20 18:34:48 CST 2014
     */
    private Double amt;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column expenses_detail.EDETAIL_ID
     *
     * @return the value of expenses_detail.EDETAIL_ID
     *
     * @ibatorgenerated Thu Mar 20 18:34:48 CST 2014
     */
    public Long getEdetailId() {
        return edetailId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column expenses_detail.EDETAIL_ID
     *
     * @param edetailId the value for expenses_detail.EDETAIL_ID
     *
     * @ibatorgenerated Thu Mar 20 18:34:48 CST 2014
     */
    public void setEdetailId(Long edetailId) {
        this.edetailId = edetailId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column expenses_detail.EXPENSES_ID
     *
     * @return the value of expenses_detail.EXPENSES_ID
     *
     * @ibatorgenerated Thu Mar 20 18:34:48 CST 2014
     */
    public Long getExpensesId() {
        return expensesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column expenses_detail.EXPENSES_ID
     *
     * @param expensesId the value for expenses_detail.EXPENSES_ID
     *
     * @ibatorgenerated Thu Mar 20 18:34:48 CST 2014
     */
    public void setExpensesId(Long expensesId) {
        this.expensesId = expensesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column expenses_detail.TIME
     *
     * @return the value of expenses_detail.TIME
     *
     * @ibatorgenerated Thu Mar 20 18:34:48 CST 2014
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column expenses_detail.TIME
     *
     * @param time the value for expenses_detail.TIME
     *
     * @ibatorgenerated Thu Mar 20 18:34:48 CST 2014
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column expenses_detail.CONTENT
     *
     * @return the value of expenses_detail.CONTENT
     *
     * @ibatorgenerated Thu Mar 20 18:34:48 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column expenses_detail.CONTENT
     *
     * @param content the value for expenses_detail.CONTENT
     *
     * @ibatorgenerated Thu Mar 20 18:34:48 CST 2014
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column expenses_detail.INVOICENO
     *
     * @return the value of expenses_detail.INVOICENO
     *
     * @ibatorgenerated Thu Mar 20 18:34:48 CST 2014
     */
    public Integer getInvoiceno() {
        return invoiceno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column expenses_detail.INVOICENO
     *
     * @param invoiceno the value for expenses_detail.INVOICENO
     *
     * @ibatorgenerated Thu Mar 20 18:34:48 CST 2014
     */
    public void setInvoiceno(Integer invoiceno) {
        this.invoiceno = invoiceno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column expenses_detail.AMT
     *
     * @return the value of expenses_detail.AMT
     *
     * @ibatorgenerated Thu Mar 20 18:34:48 CST 2014
     */
    public Double getAmt() {
        return amt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column expenses_detail.AMT
     *
     * @param amt the value for expenses_detail.AMT
     *
     * @ibatorgenerated Thu Mar 20 18:34:48 CST 2014
     */
    public void setAmt(Double amt) {
        this.amt = amt;
    }
    
    private String feeKind;
    
    public String getFeeKind() {
        return feeKind;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column expenses_detail.FEE_KIND
     *
     * @param feeKind the value for expenses_detail.FEE_KIND
     *
     * @ibatorgenerated Tue Apr 15 15:14:50 CST 2014
     */
    public void setFeeKind(String feeKind) {
        this.feeKind = feeKind == null ? null : feeKind.trim();
    }
}