package com.yly.exstore;

import com.yly.exstore.Stoproduct;
import com.yly.exstore.StoproductExample;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class StoproductDAOImpl extends SqlMapClientDaoSupport implements StoproductDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stoproduct
     *
     * @ibatorgenerated Fri May 13 17:34:02 CST 2016
     */
    public StoproductDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stoproduct
     *
     * @ibatorgenerated Fri May 13 17:34:02 CST 2016
     */
    public int countByExample(StoproductExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("stoproduct.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stoproduct
     *
     * @ibatorgenerated Fri May 13 17:34:02 CST 2016
     */
    public int deleteByExample(StoproductExample example) {
        int rows = getSqlMapClientTemplate().delete("stoproduct.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stoproduct
     *
     * @ibatorgenerated Fri May 13 17:34:02 CST 2016
     */
    public int deleteByPrimaryKey(Stoproduct record) {
        int rows = getSqlMapClientTemplate().delete("stoproduct.ibatorgenerated_deleteByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stoproduct
     *
     * @ibatorgenerated Fri May 13 17:34:02 CST 2016
     */
    public void insert(Stoproduct record) {
        getSqlMapClientTemplate().insert("stoproduct.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stoproduct
     *
     * @ibatorgenerated Fri May 13 17:34:02 CST 2016
     */
    public void insertSelective(Stoproduct record) {
        getSqlMapClientTemplate().insert("stoproduct.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stoproduct
     *
     * @ibatorgenerated Fri May 13 17:34:02 CST 2016
     */
    public List selectByExample(StoproductExample example) {
        List list = getSqlMapClientTemplate().queryForList("stoproduct.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stoproduct
     *
     * @ibatorgenerated Fri May 13 17:34:02 CST 2016
     */
    public Stoproduct selectByPrimaryKey(Stoproduct sto) {
        Stoproduct record = (Stoproduct) getSqlMapClientTemplate().queryForObject("stoproduct.ibatorgenerated_selectByPrimaryKey", sto);
        return record;
    }
    public Stoproduct selectBySamId(String samId) {
        Stoproduct record = (Stoproduct) getSqlMapClientTemplate().queryForObject("stoproduct.ibatorgenerated_selectBySamId", samId);
        return record;
    }
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stoproduct
     *
     * @ibatorgenerated Fri May 13 17:34:02 CST 2016
     */
    public int updateByExampleSelective(Stoproduct record, StoproductExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("stoproduct.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stoproduct
     *
     * @ibatorgenerated Fri May 13 17:34:02 CST 2016
     */
    public int updateByExample(Stoproduct record, StoproductExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("stoproduct.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stoproduct
     *
     * @ibatorgenerated Fri May 13 17:34:02 CST 2016
     */
    public int updateByPrimaryKeySelective(Stoproduct record) {
        int rows = getSqlMapClientTemplate().update("stoproduct.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stoproduct
     *
     * @ibatorgenerated Fri May 13 17:34:02 CST 2016
     */
    public int updateByPrimaryKey(Stoproduct record) {
        int rows = getSqlMapClientTemplate().update("stoproduct.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    public int updateBySamCSN(Stoproduct record) {
        int rows = getSqlMapClientTemplate().update("stoproduct.updateBySamCSN", record);
        return rows;
    }
    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table stoproduct
     *
     * @ibatorgenerated Fri May 13 17:34:02 CST 2016
     */
    private static class UpdateByExampleParms extends StoproductExample {
        private Object record;

        public UpdateByExampleParms(Object record, StoproductExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    public List queryCardListByOa(String appNo){
    	List list = getSqlMapClientTemplate().queryForList("stoproduct.queryCardListByOa",appNo);
        return list;
    }
    public List getReport(StoproductExample example){
    	List list = getSqlMapClientTemplate().queryForList("stoproduct.getReport",example);
        return list;
    }
    public int getIssueNumByOaAppNo(String OAappNo){
    	int num= (int)getSqlMapClientTemplate().queryForObject("stoproduct.getIssueNumByOaAppNo",OAappNo);
        return num;
    }
}