//created on: 2015-7-4
package com.company.license

//list any import classes here.
import com.sample.stateless.Applicant;


//declare any global variables here




rule "Your First Rule"

    when
        $a:Applicant(age  < 18);
    then
        $a.setValid(false);

end

rule "Your Second Rule"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end
