package com.blue.product;

import com.blue.product.ModuleDef;
import com.blue.product.ModuleDefExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ModuleDefDAOImpl extends SqlMapClientDaoSupport implements ModuleDefDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table module_def
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public ModuleDefDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table module_def
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public int countByExample(ModuleDefExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("module_def.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table module_def
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public int deleteByExample(ModuleDefExample example) {
        int rows = getSqlMapClientTemplate().delete("module_def.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table module_def
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public int deleteByPrimaryKey(String moduleId) {
        ModuleDef key = new ModuleDef();
        key.setModuleId(moduleId);
        int rows = getSqlMapClientTemplate().delete("module_def.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table module_def
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public void insert(ModuleDef record) {
        getSqlMapClientTemplate().insert("module_def.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table module_def
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public void insertSelective(ModuleDef record) {
        getSqlMapClientTemplate().insert("module_def.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table module_def
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public List selectByExample(ModuleDefExample example) {
        List list = getSqlMapClientTemplate().queryForList("module_def.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table module_def
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public ModuleDef selectByPrimaryKey(String moduleId) {
        ModuleDef key = new ModuleDef();
        key.setModuleId(moduleId);
        ModuleDef record = (ModuleDef) getSqlMapClientTemplate().queryForObject("module_def.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table module_def
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public int updateByExampleSelective(ModuleDef record, ModuleDefExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("module_def.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table module_def
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public int updateByExample(ModuleDef record, ModuleDefExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("module_def.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table module_def
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public int updateByPrimaryKeySelective(ModuleDef record) {
        int rows = getSqlMapClientTemplate().update("module_def.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table module_def
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public int updateByPrimaryKey(ModuleDef record) {
        int rows = getSqlMapClientTemplate().update("module_def.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table module_def
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    private static class UpdateByExampleParms extends ModuleDefExample {
        private Object record;

        public UpdateByExampleParms(Object record, ModuleDefExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}