package com.blue.product;

public class ModuleDef {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column module_def.MODULE_ID
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    private String moduleId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column module_def.NAME
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column module_def.MANAGER_ID
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    private String managerId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column module_def.VERSION
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    private String version;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column module_def.PRODUCT_CODE
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    private String productCode;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column module_def.MODULE_ID
     *
     * @return the value of module_def.MODULE_ID
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column module_def.MODULE_ID
     *
     * @param moduleId the value for module_def.MODULE_ID
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId == null ? null : moduleId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column module_def.NAME
     *
     * @return the value of module_def.NAME
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column module_def.NAME
     *
     * @param name the value for module_def.NAME
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column module_def.MANAGER_ID
     *
     * @return the value of module_def.MANAGER_ID
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column module_def.MANAGER_ID
     *
     * @param managerId the value for module_def.MANAGER_ID
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId == null ? null : managerId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column module_def.VERSION
     *
     * @return the value of module_def.VERSION
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column module_def.VERSION
     *
     * @param version the value for module_def.VERSION
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column module_def.PRODUCT_CODE
     *
     * @return the value of module_def.PRODUCT_CODE
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column module_def.PRODUCT_CODE
     *
     * @param productCode the value for module_def.PRODUCT_CODE
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }
}