package com.blue.product;

import com.blue.product.ParticipateList;
import com.blue.product.ParticipateListExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ParticipateListDAOImpl extends SqlMapClientDaoSupport implements ParticipateListDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table participate_list
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public ParticipateListDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table participate_list
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public int countByExample(ParticipateListExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("participate_list.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table participate_list
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public int deleteByExample(ParticipateListExample example) {
        int rows = getSqlMapClientTemplate().delete("participate_list.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table participate_list
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) {
        ParticipateList key = new ParticipateList();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("participate_list.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table participate_list
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public void insert(ParticipateList record) {
        getSqlMapClientTemplate().insert("participate_list.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table participate_list
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public void insertSelective(ParticipateList record) {
        getSqlMapClientTemplate().insert("participate_list.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table participate_list
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public List selectByExample(ParticipateListExample example) {
        List list = getSqlMapClientTemplate().queryForList("participate_list.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table participate_list
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public ParticipateList selectByPrimaryKey(Integer id) {
        ParticipateList key = new ParticipateList();
        key.setId(id);
        ParticipateList record = (ParticipateList) getSqlMapClientTemplate().queryForObject("participate_list.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table participate_list
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public int updateByExampleSelective(ParticipateList record, ParticipateListExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("participate_list.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table participate_list
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public int updateByExample(ParticipateList record, ParticipateListExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("participate_list.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table participate_list
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public int updateByPrimaryKeySelective(ParticipateList record) {
        int rows = getSqlMapClientTemplate().update("participate_list.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table participate_list
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    public int updateByPrimaryKey(ParticipateList record) {
        int rows = getSqlMapClientTemplate().update("participate_list.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table participate_list
     *
     * @ibatorgenerated Tue Aug 06 10:09:07 CST 2013
     */
    private static class UpdateByExampleParms extends ParticipateListExample {
        private Object record;

        public UpdateByExampleParms(Object record, ParticipateListExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}