package com.blue.product;

import com.blue.product.ProductDef;
import com.blue.product.ProductDefExample;
import java.util.List;

public interface ProductDefDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table product_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    int countByExample(ProductDefExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table product_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    int deleteByExample(ProductDefExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table product_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    int deleteByPrimaryKey(String productCode);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table product_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    void insert(ProductDef record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table product_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    void insertSelective(ProductDef record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table product_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    List selectByExample(ProductDefExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table product_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    ProductDef selectByPrimaryKey(String productCode);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table product_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    int updateByExampleSelective(ProductDef record, ProductDefExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table product_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    int updateByExample(ProductDef record, ProductDefExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table product_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    int updateByPrimaryKeySelective(ProductDef record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table product_def
     *
     * @ibatorgenerated Mon Jul 29 11:36:07 CST 2013
     */
    int updateByPrimaryKey(ProductDef record);
}