package com.yly.issue;

public class Issueapp {
	private String taskNo;
    public String getTaskNo() {
		return taskNo;
	}

	public void setTaskNo(String taskNo) {
		this.taskNo = taskNo;
	}

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column applyinfotb.AppNo
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    private String appNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column applyinfotb.OAappNo
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    private String OAappNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column applyinfotb.OperationType
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    private Short operationType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column applyinfotb.TaskAmt
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    private Long taskAmt;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column applyinfotb.ProjName
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    private String projName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column applyinfotb.ProjContNum
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    private String projContNum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column applyinfotb.UnitId
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    private Integer unitId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column applyinfotb.Unitperson
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    private String unitperson;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column applyinfotb.Unittel
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    private String unittel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column applyinfotb.PaymentType
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    private Short paymentType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column applyinfotb.TotalPrice
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    private Long totalPrice;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column applyinfotb.FormState
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    private Short formState;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column applyinfotb.Director
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    private String director;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column applyinfotb.OperId
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    private String operId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column applyinfotb.CurrDate
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    private String currDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column applyinfotb.Remarks
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    private String remarks;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column applyinfotb.AppNo
     *
     * @return the value of applyinfotb.AppNo
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public String getAppNo() {
        return appNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column applyinfotb.AppNo
     *
     * @param appNo the value for applyinfotb.AppNo
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public void setAppNo(String appNo) {
        this.appNo = appNo == null ? null : appNo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column applyinfotb.OAappNo
     *
     * @return the value of applyinfotb.OAappNo
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public String getOAappNo() {
        return OAappNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column applyinfotb.OAappNo
     *
     * @param OAappNo the value for applyinfotb.OAappNo
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public void setOAappNo(String OAappNo) {
        this.OAappNo = OAappNo == null ? null : OAappNo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column applyinfotb.OperationType
     *
     * @return the value of applyinfotb.OperationType
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public Short getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column applyinfotb.OperationType
     *
     * @param operationType the value for applyinfotb.OperationType
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public void setOperationType(Short operationType) {
        this.operationType = operationType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column applyinfotb.TaskAmt
     *
     * @return the value of applyinfotb.TaskAmt
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public Long getTaskAmt() {
        return taskAmt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column applyinfotb.TaskAmt
     *
     * @param taskAmt the value for applyinfotb.TaskAmt
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public void setTaskAmt(Long taskAmt) {
        this.taskAmt = taskAmt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column applyinfotb.ProjName
     *
     * @return the value of applyinfotb.ProjName
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public String getProjName() {
        return projName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column applyinfotb.ProjName
     *
     * @param projName the value for applyinfotb.ProjName
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public void setProjName(String projName) {
        this.projName = projName == null ? null : projName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column applyinfotb.ProjContNum
     *
     * @return the value of applyinfotb.ProjContNum
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public String getProjContNum() {
        return projContNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column applyinfotb.ProjContNum
     *
     * @param projContNum the value for applyinfotb.ProjContNum
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public void setProjContNum(String projContNum) {
        this.projContNum = projContNum == null ? null : projContNum.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column applyinfotb.UnitId
     *
     * @return the value of applyinfotb.UnitId
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public Integer getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column applyinfotb.UnitId
     *
     * @param unitId the value for applyinfotb.UnitId
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column applyinfotb.Unitperson
     *
     * @return the value of applyinfotb.Unitperson
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public String getUnitperson() {
        return unitperson;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column applyinfotb.Unitperson
     *
     * @param unitperson the value for applyinfotb.Unitperson
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public void setUnitperson(String unitperson) {
        this.unitperson = unitperson == null ? null : unitperson.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column applyinfotb.Unittel
     *
     * @return the value of applyinfotb.Unittel
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public String getUnittel() {
        return unittel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column applyinfotb.Unittel
     *
     * @param unittel the value for applyinfotb.Unittel
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public void setUnittel(String unittel) {
        this.unittel = unittel == null ? null : unittel.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column applyinfotb.PaymentType
     *
     * @return the value of applyinfotb.PaymentType
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public Short getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column applyinfotb.PaymentType
     *
     * @param paymentType the value for applyinfotb.PaymentType
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public void setPaymentType(Short paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column applyinfotb.TotalPrice
     *
     * @return the value of applyinfotb.TotalPrice
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public Long getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column applyinfotb.TotalPrice
     *
     * @param totalPrice the value for applyinfotb.TotalPrice
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public void setTotalPrice(Long totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column applyinfotb.FormState
     *
     * @return the value of applyinfotb.FormState
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public Short getFormState() {
        return formState;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column applyinfotb.FormState
     *
     * @param formState the value for applyinfotb.FormState
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public void setFormState(Short formState) {
        this.formState = formState;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column applyinfotb.Director
     *
     * @return the value of applyinfotb.Director
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column applyinfotb.Director
     *
     * @param director the value for applyinfotb.Director
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public void setDirector(String director) {
        this.director = director == null ? null : director.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column applyinfotb.OperId
     *
     * @return the value of applyinfotb.OperId
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column applyinfotb.OperId
     *
     * @param operId the value for applyinfotb.OperId
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column applyinfotb.CurrDate
     *
     * @return the value of applyinfotb.CurrDate
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public String getCurrDate() {
        return currDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column applyinfotb.CurrDate
     *
     * @param currDate the value for applyinfotb.CurrDate
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public void setCurrDate(String currDate) {
        this.currDate = currDate == null ? null : currDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column applyinfotb.Remarks
     *
     * @return the value of applyinfotb.Remarks
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column applyinfotb.Remarks
     *
     * @param remarks the value for applyinfotb.Remarks
     *
     * @ibatorgenerated Thu Apr 28 15:19:25 CST 2016
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }


}