package com.yly.issue;

import com.eis.util.CheckUtil;
import com.yly.issue.Issueapp;
import com.yly.issue.IssueappExample;
import com.yly.issue.IssueappExample.Criteria;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IssueappDAOImpl extends SqlMapClientDaoSupport implements IssueappDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issueapp
     *
     * @ibatorgenerated Tue Mar 29 14:27:18 CST 2016
     */
    public IssueappDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issueapp
     *
     * @ibatorgenerated Tue Mar 29 14:27:18 CST 2016
     */
    public int countByExample(IssueappExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("issueapp.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issueapp
     *
     * @ibatorgenerated Tue Mar 29 14:27:18 CST 2016
     */
    public int deleteByExample(IssueappExample example) {
        int rows = getSqlMapClientTemplate().delete("issueapp.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issueapp
     *
     * @ibatorgenerated Tue Mar 29 14:27:18 CST 2016
     */
    public int deleteByPrimaryKey(String appNo) {
        Issueapp key = new Issueapp();
        key.setAppNo(appNo);
        int rows = getSqlMapClientTemplate().delete("issueapp.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issueapp
     *
     * @ibatorgenerated Tue Mar 29 14:27:18 CST 2016
     */
    public void insert(Issueapp record) {
        getSqlMapClientTemplate().insert("issueapp.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issueapp
     *
     * @ibatorgenerated Tue Mar 29 14:27:18 CST 2016
     */
    public void insertSelective(Issueapp record) {
        getSqlMapClientTemplate().insert("issueapp.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issueapp
     *
     * @ibatorgenerated Tue Mar 29 14:27:18 CST 2016
     */
    public List selectByExample(IssueappExample example) {
        List list = getSqlMapClientTemplate().queryForList("issueapp.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issueapp
     *
     * @ibatorgenerated Tue Mar 29 14:27:18 CST 2016
     */
    public Issueapp selectByPrimaryKey(String appNo) {
        Issueapp key = new Issueapp();
        key.setAppNo(appNo);
        Issueapp record = (Issueapp) getSqlMapClientTemplate().queryForObject("issueapp.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    public String selectByOA(String oaAppNo) {
        String result = (String)getSqlMapClientTemplate().queryForObject("issueapp.selectByOAKey", oaAppNo);
        return result;
    }    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issueapp
     *
     * @ibatorgenerated Tue Mar 29 14:27:18 CST 2016
     */
    public int updateByExampleSelective(Issueapp record, IssueappExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("issueapp.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issueapp
     *
     * @ibatorgenerated Tue Mar 29 14:27:18 CST 2016
     */
    public int updateByExample(Issueapp record, IssueappExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("issueapp.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issueapp
     *
     * @ibatorgenerated Tue Mar 29 14:27:18 CST 2016
     */
    public int updateByPrimaryKeySelective(Issueapp record) {
        int rows = getSqlMapClientTemplate().update("issueapp.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issueapp
     *
     * @ibatorgenerated Tue Mar 29 14:27:18 CST 2016
     */
    public int updateByPrimaryKey(Issueapp record) {
        int rows = getSqlMapClientTemplate().update("issueapp.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table issueapp
     *
     * @ibatorgenerated Tue Mar 29 14:27:18 CST 2016
     */
    private static class UpdateByExampleParms extends IssueappExample {
        private Object record;

        public UpdateByExampleParms(Object record, IssueappExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    public List queryIssuExample(IssueappExample example) {
        List list = getSqlMapClientTemplate().queryForList("issueapp.queryIssuExample", example);
        return list;
    }
    public List selectTaskNoByExample(IssueappForm app) {
		IssueappExample e = new IssueappExample();
		Criteria c = e.createCriteria();
		c.issuetaskAndApplytb();
		c.andApplyOperationTypeBetween((short)20, (short)30);//发行业务
		if(!CheckUtil.isEmptry(app.getBeginDate_f())){
			c.andCurrDateGreaterThanOrEqualTo(app.getBeginDate_f()+"000000");
		}
		if(!CheckUtil.isEmptry(app.getEndDate_f())){
			c.andCurrDateLessThanOrEqualTo(app.getEndDate_f()+"999999");
		}
        List list = getSqlMapClientTemplate().queryForList("issueapp.selectTaskNoByExample", e);
        return list;
    } 
    public List getExchangeRawReport(IssueappExample example) {
        List list = getSqlMapClientTemplate().queryForList("issueapp.getExchangeRawReport", example);
        return list;
    }
    public List getMakeUpRawReport(IssueappExample example) {
        List list = getSqlMapClientTemplate().queryForList("issueapp.getMakeUpRawReport", example);
        return list;
    }    
    public Issueapp queryPosExStoreInfo(IssueappExample example) {
    	Issueapp record  = (Issueapp) getSqlMapClientTemplate().queryForObject("issueapp.queryPosExStoreInfo", example);
        return record;
    }  
    public Issueapp queryPosBackInfo(IssueappExample example) {
    	Issueapp record  =  (Issueapp) getSqlMapClientTemplate().queryForObject("issueapp.queryPosBackInfo", example);
        return record;
    }  
}