package com.yly.issue;

import com.yly.issue.IssuetaskctrlExample;

import java.util.Iterator;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IssuetaskctrlDAOImpl extends SqlMapClientDaoSupport implements IssuetaskctrlDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issuetaskctrl
     *
     * @ibatorgenerated Tue Mar 29 14:30:23 CST 2016
     */
    public IssuetaskctrlDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issuetaskctrl
     *
     * @ibatorgenerated Tue Mar 29 14:30:23 CST 2016
     */
    public int countByExample(IssuetaskctrlExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("issuetaskctrl.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issuetaskctrl
     *
     * @ibatorgenerated Tue Mar 29 14:30:23 CST 2016
     */
    public int deleteByExample(IssuetaskctrlExample example) {
        int rows = getSqlMapClientTemplate().delete("issuetaskctrl.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issuetaskctrl
     *
     * @ibatorgenerated Tue Mar 29 14:30:23 CST 2016
     */
    public int deleteByPrimaryKey(String taskCtrlNo) {
        Issuetaskctrl key = new Issuetaskctrl();
        key.setTaskCtrlNo(taskCtrlNo);
        int rows = getSqlMapClientTemplate().delete("issuetaskctrl.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issuetaskctrl
     *
     * @ibatorgenerated Tue Mar 29 14:30:23 CST 2016
     */
    public void insert(Issuetaskctrl record) {
        getSqlMapClientTemplate().insert("issuetaskctrl.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issuetaskctrl
     *
     * @ibatorgenerated Tue Mar 29 14:30:23 CST 2016
     */
    public void insertSelective(Issuetaskctrl record) {
        getSqlMapClientTemplate().insert("issuetaskctrl.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issuetaskctrl
     *
     * @ibatorgenerated Tue Mar 29 14:30:23 CST 2016
     */
    public List selectByExample(IssuetaskctrlExample example) {
        List list = getSqlMapClientTemplate().queryForList("issuetaskctrl.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issuetaskctrl
     *
     * @ibatorgenerated Tue Mar 29 14:30:23 CST 2016
     */
    public Issuetaskctrl selectByPrimaryKey(String taskCtrlNo) {
        Issuetaskctrl key = new Issuetaskctrl();
        key.setTaskCtrlNo(taskCtrlNo);
        Issuetaskctrl record = (Issuetaskctrl) getSqlMapClientTemplate().queryForObject("issuetaskctrl.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issuetaskctrl
     *
     * @ibatorgenerated Tue Mar 29 14:30:23 CST 2016
     */
    public int updateByExampleSelective(Issuetaskctrl record, IssuetaskctrlExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("issuetaskctrl.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issuetaskctrl
     *
     * @ibatorgenerated Tue Mar 29 14:30:23 CST 2016
     */
    public int updateByExample(Issuetaskctrl record, IssuetaskctrlExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("issuetaskctrl.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issuetaskctrl
     *
     * @ibatorgenerated Tue Mar 29 14:30:23 CST 2016
     */
    public int updateByPrimaryKeySelective(Issuetaskctrl record) {
        int rows = getSqlMapClientTemplate().update("issuetaskctrl.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issuetaskctrl
     *
     * @ibatorgenerated Tue Mar 29 14:30:23 CST 2016
     */
    public int updateByPrimaryKey(Issuetaskctrl record) {
        int rows = getSqlMapClientTemplate().update("issuetaskctrl.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table issuetaskctrl
     *
     * @ibatorgenerated Tue Mar 29 14:30:23 CST 2016
     */
    private static class UpdateByExampleParms extends IssuetaskctrlExample {
        private Object record;

        public UpdateByExampleParms(Object record, IssuetaskctrlExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    public String getSamNum(String preCardNo) {
    	String currMaxcard = (String.valueOf(getSqlMapClientTemplate().queryForObject("issuetaskctrl.getMaxSamNum", preCardNo+"%")));
        return currMaxcard;
    }
    public int sumByExample(IssuetaskctrlExample example) {
        Integer sum = (Integer)  getSqlMapClientTemplate().queryForObject("issuetaskctrl.ibatorgenerated_sumByExample", example);
        if(sum==null)
        	sum=0;
        return sum.intValue();
    }
};