package com.yly.issue;

import com.yly.issue.Issuetask;
import com.yly.issue.IssuetaskExample;
import java.util.List;

public interface IssuetaskDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issuetask
     *
     * @ibatorgenerated Tue Mar 29 14:29:07 CST 2016
     */
    int countByExample(IssuetaskExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issuetask
     *
     * @ibatorgenerated Tue Mar 29 14:29:07 CST 2016
     */
    int deleteByExample(IssuetaskExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issuetask
     *
     * @ibatorgenerated Tue Mar 29 14:29:07 CST 2016
     */
    int deleteByPrimaryKey(String taskNo);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issuetask
     *
     * @ibatorgenerated Tue Mar 29 14:29:07 CST 2016
     */
    void insert(Issuetask record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issuetask
     *
     * @ibatorgenerated Tue Mar 29 14:29:07 CST 2016
     */
    void insertSelective(Issuetask record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issuetask
     *
     * @ibatorgenerated Tue Mar 29 14:29:07 CST 2016
     */
    List selectByExample(IssuetaskExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issuetask
     *
     * @ibatorgenerated Tue Mar 29 14:29:07 CST 2016
     */
    Issuetask selectByPrimaryKey(String taskNo);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issuetask
     *
     * @ibatorgenerated Tue Mar 29 14:29:07 CST 2016
     */
    int updateByExampleSelective(Issuetask record, IssuetaskExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issuetask
     *
     * @ibatorgenerated Tue Mar 29 14:29:07 CST 2016
     */
    int updateByExample(Issuetask record, IssuetaskExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issuetask
     *
     * @ibatorgenerated Tue Mar 29 14:29:07 CST 2016
     */
    int updateByPrimaryKeySelective(Issuetask record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table issuetask
     *
     * @ibatorgenerated Tue Mar 29 14:29:07 CST 2016
     */
    int updateByPrimaryKey(Issuetask record);
}