package com.yly.issue;

import java.util.Date;

public class Lsissuetb {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.FlowNo
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private String flowNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.OAappNo
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private String OAappNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.TaskNo
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private String taskNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.FormNo
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private String formNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.AppNo
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private String appNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.UnitId
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private Integer unitId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.ProdId
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private String prodId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.SamId
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private String samId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.SamCSN
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private String samCSN;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.AppTypeId
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private String appTypeId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.CommRate
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private String commRate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.KeyType
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private String keyType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.BinFileVer
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private String binFileVer;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.ManufacId
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private Short manufacId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.MaterType
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private Short materType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.SamIdOld
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private String samIdOld;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.SamCSNOld
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private String samCSNOld;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.BadChangeType
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private Short badChangeType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.OperationType
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private Short operationType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.AuthSign
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private Short authSign;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.W2Sign
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private Short w2Sign;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.ErrorCode
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private Integer errorCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.IssueOperID
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private String issueOperID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column lsissuetb.IssueTime
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    private Date issueTime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.FlowNo
     *
     * @return the value of lsissuetb.FlowNo
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public String getFlowNo() {
        return flowNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.FlowNo
     *
     * @param flowNo the value for lsissuetb.FlowNo
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setFlowNo(String flowNo) {
        this.flowNo = flowNo == null ? null : flowNo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.OAappNo
     *
     * @return the value of lsissuetb.OAappNo
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public String getOAappNo() {
        return OAappNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.OAappNo
     *
     * @param OAappNo the value for lsissuetb.OAappNo
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setOAappNo(String OAappNo) {
        this.OAappNo = OAappNo == null ? null : OAappNo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.TaskNo
     *
     * @return the value of lsissuetb.TaskNo
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public String getTaskNo() {
        return taskNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.TaskNo
     *
     * @param taskNo the value for lsissuetb.TaskNo
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setTaskNo(String taskNo) {
        this.taskNo = taskNo == null ? null : taskNo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.FormNo
     *
     * @return the value of lsissuetb.FormNo
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public String getFormNo() {
        return formNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.FormNo
     *
     * @param formNo the value for lsissuetb.FormNo
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setFormNo(String formNo) {
        this.formNo = formNo == null ? null : formNo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.AppNo
     *
     * @return the value of lsissuetb.AppNo
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public String getAppNo() {
        return appNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.AppNo
     *
     * @param appNo the value for lsissuetb.AppNo
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setAppNo(String appNo) {
        this.appNo = appNo == null ? null : appNo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.UnitId
     *
     * @return the value of lsissuetb.UnitId
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public Integer getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.UnitId
     *
     * @param unitId the value for lsissuetb.UnitId
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.ProdId
     *
     * @return the value of lsissuetb.ProdId
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public String getProdId() {
        return prodId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.ProdId
     *
     * @param prodId the value for lsissuetb.ProdId
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setProdId(String prodId) {
        this.prodId = prodId == null ? null : prodId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.SamId
     *
     * @return the value of lsissuetb.SamId
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public String getSamId() {
        return samId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.SamId
     *
     * @param samId the value for lsissuetb.SamId
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setSamId(String samId) {
        this.samId = samId == null ? null : samId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.SamCSN
     *
     * @return the value of lsissuetb.SamCSN
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public String getSamCSN() {
        return samCSN;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.SamCSN
     *
     * @param samCSN the value for lsissuetb.SamCSN
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setSamCSN(String samCSN) {
        this.samCSN = samCSN == null ? null : samCSN.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.AppTypeId
     *
     * @return the value of lsissuetb.AppTypeId
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public String getAppTypeId() {
        return appTypeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.AppTypeId
     *
     * @param appTypeId the value for lsissuetb.AppTypeId
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setAppTypeId(String appTypeId) {
        this.appTypeId = appTypeId == null ? null : appTypeId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.CommRate
     *
     * @return the value of lsissuetb.CommRate
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public String getCommRate() {
        return commRate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.CommRate
     *
     * @param commRate the value for lsissuetb.CommRate
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setCommRate(String commRate) {
        this.commRate = commRate == null ? null : commRate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.KeyType
     *
     * @return the value of lsissuetb.KeyType
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public String getKeyType() {
        return keyType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.KeyType
     *
     * @param keyType the value for lsissuetb.KeyType
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setKeyType(String keyType) {
        this.keyType = keyType == null ? null : keyType.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.BinFileVer
     *
     * @return the value of lsissuetb.BinFileVer
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public String getBinFileVer() {
        return binFileVer;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.BinFileVer
     *
     * @param binFileVer the value for lsissuetb.BinFileVer
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setBinFileVer(String binFileVer) {
        this.binFileVer = binFileVer == null ? null : binFileVer.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.ManufacId
     *
     * @return the value of lsissuetb.ManufacId
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public Short getManufacId() {
        return manufacId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.ManufacId
     *
     * @param manufacId the value for lsissuetb.ManufacId
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setManufacId(Short manufacId) {
        this.manufacId = manufacId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.MaterType
     *
     * @return the value of lsissuetb.MaterType
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public Short getMaterType() {
        return materType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.MaterType
     *
     * @param materType the value for lsissuetb.MaterType
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setMaterType(Short materType) {
        this.materType = materType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.SamIdOld
     *
     * @return the value of lsissuetb.SamIdOld
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public String getSamIdOld() {
        return samIdOld;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.SamIdOld
     *
     * @param samIdOld the value for lsissuetb.SamIdOld
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setSamIdOld(String samIdOld) {
        this.samIdOld = samIdOld == null ? null : samIdOld.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.SamCSNOld
     *
     * @return the value of lsissuetb.SamCSNOld
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public String getSamCSNOld() {
        return samCSNOld;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.SamCSNOld
     *
     * @param samCSNOld the value for lsissuetb.SamCSNOld
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setSamCSNOld(String samCSNOld) {
        this.samCSNOld = samCSNOld == null ? null : samCSNOld.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.BadChangeType
     *
     * @return the value of lsissuetb.BadChangeType
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public Short getBadChangeType() {
        return badChangeType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.BadChangeType
     *
     * @param badChangeType the value for lsissuetb.BadChangeType
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setBadChangeType(Short badChangeType) {
        this.badChangeType = badChangeType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.OperationType
     *
     * @return the value of lsissuetb.OperationType
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public Short getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.OperationType
     *
     * @param operationType the value for lsissuetb.OperationType
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setOperationType(Short operationType) {
        this.operationType = operationType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.AuthSign
     *
     * @return the value of lsissuetb.AuthSign
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public Short getAuthSign() {
        return authSign;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.AuthSign
     *
     * @param authSign the value for lsissuetb.AuthSign
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setAuthSign(Short authSign) {
        this.authSign = authSign;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.W2Sign
     *
     * @return the value of lsissuetb.W2Sign
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public Short getW2Sign() {
        return w2Sign;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.W2Sign
     *
     * @param w2Sign the value for lsissuetb.W2Sign
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setW2Sign(Short w2Sign) {
        this.w2Sign = w2Sign;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.ErrorCode
     *
     * @return the value of lsissuetb.ErrorCode
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public Integer getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.ErrorCode
     *
     * @param errorCode the value for lsissuetb.ErrorCode
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setErrorCode(Integer errorCode) {
        this.errorCode = errorCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.IssueOperID
     *
     * @return the value of lsissuetb.IssueOperID
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public String getIssueOperID() {
        return issueOperID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.IssueOperID
     *
     * @param issueOperID the value for lsissuetb.IssueOperID
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setIssueOperID(String issueOperID) {
        this.issueOperID = issueOperID == null ? null : issueOperID.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column lsissuetb.IssueTime
     *
     * @return the value of lsissuetb.IssueTime
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public Date getIssueTime() {
        return issueTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column lsissuetb.IssueTime
     *
     * @param issueTime the value for lsissuetb.IssueTime
     *
     * @ibatorgenerated Tue Mar 29 14:31:44 CST 2016
     */
    public void setIssueTime(Date issueTime) {
        this.issueTime = issueTime;
    }
}