package com.yly.issue;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import com.yly.ls.LsinfoExample.Criteria;

public class MwsissuetbExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table mwsissuetb
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table mwsissuetb
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mwsissuetb
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public MwsissuetbExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mwsissuetb
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    protected MwsissuetbExample(MwsissuetbExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mwsissuetb
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mwsissuetb
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mwsissuetb
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mwsissuetb
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mwsissuetb
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mwsissuetb
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mwsissuetb
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table mwsissuetb
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(((Date)iter.next()).getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andFormNoIsNull() {
            addCriterion("FormNo is null");
            return this;
        }

        public Criteria andFormNoIsNotNull() {
            addCriterion("FormNo is not null");
            return this;
        }

        public Criteria andFormNoEqualTo(String value) {
            addCriterion("FormNo =", value, "formNo");
            return this;
        }

        public Criteria andFormNoNotEqualTo(String value) {
            addCriterion("FormNo <>", value, "formNo");
            return this;
        }

        public Criteria andFormNoGreaterThan(String value) {
            addCriterion("FormNo >", value, "formNo");
            return this;
        }

        public Criteria andFormNoGreaterThanOrEqualTo(String value) {
            addCriterion("FormNo >=", value, "formNo");
            return this;
        }

        public Criteria andFormNoLessThan(String value) {
            addCriterion("FormNo <", value, "formNo");
            return this;
        }

        public Criteria andFormNoLessThanOrEqualTo(String value) {
            addCriterion("FormNo <=", value, "formNo");
            return this;
        }

        public Criteria andFormNoLike(String value) {
            addCriterion("FormNo like", value, "formNo");
            return this;
        }

        public Criteria andFormNoNotLike(String value) {
            addCriterion("FormNo not like", value, "formNo");
            return this;
        }

        public Criteria andFormNoIn(List values) {
            addCriterion("FormNo in", values, "formNo");
            return this;
        }

        public Criteria andFormNoNotIn(List values) {
            addCriterion("FormNo not in", values, "formNo");
            return this;
        }

        public Criteria andFormNoBetween(String value1, String value2) {
            addCriterion("FormNo between", value1, value2, "formNo");
            return this;
        }

        public Criteria andFormNoNotBetween(String value1, String value2) {
            addCriterion("FormNo not between", value1, value2, "formNo");
            return this;
        }

        public Criteria andTaskCtrlNoIsNull() {
            addCriterion("TaskCtrlNo is null");
            return this;
        }

        public Criteria andTaskCtrlNoIsNotNull() {
            addCriterion("TaskCtrlNo is not null");
            return this;
        }

        public Criteria andTaskCtrlNoEqualTo(String value) {
            addCriterion("TaskCtrlNo =", value, "taskCtrlNo");
            return this;
        }

        public Criteria andTaskCtrlNoNotEqualTo(String value) {
            addCriterion("TaskCtrlNo <>", value, "taskCtrlNo");
            return this;
        }

        public Criteria andTaskCtrlNoGreaterThan(String value) {
            addCriterion("TaskCtrlNo >", value, "taskCtrlNo");
            return this;
        }

        public Criteria andTaskCtrlNoGreaterThanOrEqualTo(String value) {
            addCriterion("TaskCtrlNo >=", value, "taskCtrlNo");
            return this;
        }

        public Criteria andTaskCtrlNoLessThan(String value) {
            addCriterion("TaskCtrlNo <", value, "taskCtrlNo");
            return this;
        }

        public Criteria andTaskCtrlNoLessThanOrEqualTo(String value) {
            addCriterion("TaskCtrlNo <=", value, "taskCtrlNo");
            return this;
        }

        public Criteria andTaskCtrlNoLike(String value) {
            addCriterion("TaskCtrlNo like", value, "taskCtrlNo");
            return this;
        }

        public Criteria andTaskCtrlNoNotLike(String value) {
            addCriterion("TaskCtrlNo not like", value, "taskCtrlNo");
            return this;
        }

        public Criteria andTaskCtrlNoIn(List values) {
            addCriterion("TaskCtrlNo in", values, "taskCtrlNo");
            return this;
        }

        public Criteria andTaskCtrlNoNotIn(List values) {
            addCriterion("TaskCtrlNo not in", values, "taskCtrlNo");
            return this;
        }

        public Criteria andTaskCtrlNoBetween(String value1, String value2) {
            addCriterion("TaskCtrlNo between", value1, value2, "taskCtrlNo");
            return this;
        }

        public Criteria andTaskCtrlNoNotBetween(String value1, String value2) {
            addCriterion("TaskCtrlNo not between", value1, value2, "taskCtrlNo");
            return this;
        }

        public Criteria andFormTimeIsNull() {
            addCriterion("FormTime is null");
            return this;
        }

        public Criteria andFormTimeIsNotNull() {
            addCriterion("FormTime is not null");
            return this;
        }



        public Criteria andWsSnrIsNull() {
            addCriterion("WsSnr is null");
            return this;
        }

        public Criteria andWsSnrIsNotNull() {
            addCriterion("WsSnr is not null");
            return this;
        }

        public Criteria andWsSnrEqualTo(Short value) {
            addCriterion("WsSnr =", value, "wsSnr");
            return this;
        }

        public Criteria andWsSnrNotEqualTo(Short value) {
            addCriterion("WsSnr <>", value, "wsSnr");
            return this;
        }

        public Criteria andWsSnrGreaterThan(Short value) {
            addCriterion("WsSnr >", value, "wsSnr");
            return this;
        }

        public Criteria andWsSnrGreaterThanOrEqualTo(Short value) {
            addCriterion("WsSnr >=", value, "wsSnr");
            return this;
        }

        public Criteria andWsSnrLessThan(Short value) {
            addCriterion("WsSnr <", value, "wsSnr");
            return this;
        }

        public Criteria andWsSnrLessThanOrEqualTo(Short value) {
            addCriterion("WsSnr <=", value, "wsSnr");
            return this;
        }

        public Criteria andWsSnrIn(List values) {
            addCriterion("WsSnr in", values, "wsSnr");
            return this;
        }

        public Criteria andWsSnrNotIn(List values) {
            addCriterion("WsSnr not in", values, "wsSnr");
            return this;
        }

        public Criteria andWsSnrBetween(Short value1, Short value2) {
            addCriterion("WsSnr between", value1, value2, "wsSnr");
            return this;
        }

        public Criteria andWsSnrNotBetween(Short value1, Short value2) {
            addCriterion("WsSnr not between", value1, value2, "wsSnr");
            return this;
        }

        public Criteria andProdIdIsNull() {
            addCriterion("ProdId is null");
            return this;
        }

        public Criteria andProdIdIsNotNull() {
            addCriterion("ProdId is not null");
            return this;
        }

        public Criteria andProdIdEqualTo(String value) {
            addCriterion("ProdId =", value, "prodId");
            return this;
        }

        public Criteria andProdIdNotEqualTo(String value) {
            addCriterion("ProdId <>", value, "prodId");
            return this;
        }

        public Criteria andProdIdGreaterThan(String value) {
            addCriterion("ProdId >", value, "prodId");
            return this;
        }

        public Criteria andProdIdGreaterThanOrEqualTo(String value) {
            addCriterion("ProdId >=", value, "prodId");
            return this;
        }

        public Criteria andProdIdLessThan(String value) {
            addCriterion("ProdId <", value, "prodId");
            return this;
        }

        public Criteria andProdIdLessThanOrEqualTo(String value) {
            addCriterion("ProdId <=", value, "prodId");
            return this;
        }

        public Criteria andProdIdLike(String value) {
            addCriterion("ProdId like", value, "prodId");
            return this;
        }

        public Criteria andProdIdNotLike(String value) {
            addCriterion("ProdId not like", value, "prodId");
            return this;
        }

        public Criteria andProdIdIn(List values) {
            addCriterion("ProdId in", values, "prodId");
            return this;
        }

        public Criteria andProdIdNotIn(List values) {
            addCriterion("ProdId not in", values, "prodId");
            return this;
        }

        public Criteria andProdIdBetween(String value1, String value2) {
            addCriterion("ProdId between", value1, value2, "prodId");
            return this;
        }

        public Criteria andProdIdNotBetween(String value1, String value2) {
            addCriterion("ProdId not between", value1, value2, "prodId");
            return this;
        }

        public Criteria andKeyTypeIsNull() {
            addCriterion("KeyType is null");
            return this;
        }

        public Criteria andKeyTypeIsNotNull() {
            addCriterion("KeyType is not null");
            return this;
        }

        public Criteria andKeyTypeEqualTo(Short value) {
            addCriterion("KeyType =", value, "keyType");
            return this;
        }

        public Criteria andKeyTypeNotEqualTo(Short value) {
            addCriterion("KeyType <>", value, "keyType");
            return this;
        }

        public Criteria andKeyTypeGreaterThan(Short value) {
            addCriterion("KeyType >", value, "keyType");
            return this;
        }

        public Criteria andKeyTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("KeyType >=", value, "keyType");
            return this;
        }

        public Criteria andKeyTypeLessThan(Short value) {
            addCriterion("KeyType <", value, "keyType");
            return this;
        }

        public Criteria andKeyTypeLessThanOrEqualTo(Short value) {
            addCriterion("KeyType <=", value, "keyType");
            return this;
        }

        public Criteria andKeyTypeIn(List values) {
            addCriterion("KeyType in", values, "keyType");
            return this;
        }

        public Criteria andKeyTypeNotIn(List values) {
            addCriterion("KeyType not in", values, "keyType");
            return this;
        }

        public Criteria andKeyTypeBetween(Short value1, Short value2) {
            addCriterion("KeyType between", value1, value2, "keyType");
            return this;
        }

        public Criteria andKeyTypeNotBetween(Short value1, Short value2) {
            addCriterion("KeyType not between", value1, value2, "keyType");
            return this;
        }

        public Criteria andBinFileVerIsNull() {
            addCriterion("BinFileVer is null");
            return this;
        }

        public Criteria andBinFileVerIsNotNull() {
            addCriterion("BinFileVer is not null");
            return this;
        }

        public Criteria andBinFileVerEqualTo(String value) {
            addCriterion("BinFileVer =", value, "binFileVer");
            return this;
        }

        public Criteria andBinFileVerNotEqualTo(String value) {
            addCriterion("BinFileVer <>", value, "binFileVer");
            return this;
        }

        public Criteria andBinFileVerGreaterThan(String value) {
            addCriterion("BinFileVer >", value, "binFileVer");
            return this;
        }

        public Criteria andBinFileVerGreaterThanOrEqualTo(String value) {
            addCriterion("BinFileVer >=", value, "binFileVer");
            return this;
        }

        public Criteria andBinFileVerLessThan(String value) {
            addCriterion("BinFileVer <", value, "binFileVer");
            return this;
        }

        public Criteria andBinFileVerLessThanOrEqualTo(String value) {
            addCriterion("BinFileVer <=", value, "binFileVer");
            return this;
        }

        public Criteria andBinFileVerLike(String value) {
            addCriterion("BinFileVer like", value, "binFileVer");
            return this;
        }

        public Criteria andBinFileVerNotLike(String value) {
            addCriterion("BinFileVer not like", value, "binFileVer");
            return this;
        }

        public Criteria andBinFileVerIn(List values) {
            addCriterion("BinFileVer in", values, "binFileVer");
            return this;
        }

        public Criteria andBinFileVerNotIn(List values) {
            addCriterion("BinFileVer not in", values, "binFileVer");
            return this;
        }

        public Criteria andBinFileVerBetween(String value1, String value2) {
            addCriterion("BinFileVer between", value1, value2, "binFileVer");
            return this;
        }

        public Criteria andBinFileVerNotBetween(String value1, String value2) {
            addCriterion("BinFileVer not between", value1, value2, "binFileVer");
            return this;
        }

        public Criteria andPhiTypeIdIsNull() {
            addCriterion("PhiTypeId is null");
            return this;
        }

        public Criteria andPhiTypeIdIsNotNull() {
            addCriterion("PhiTypeId is not null");
            return this;
        }

        public Criteria andPhiTypeIdEqualTo(String value) {
            addCriterion("PhiTypeId =", value, "phiTypeId");
            return this;
        }

        public Criteria andPhiTypeIdNotEqualTo(String value) {
            addCriterion("PhiTypeId <>", value, "phiTypeId");
            return this;
        }

        public Criteria andPhiTypeIdGreaterThan(String value) {
            addCriterion("PhiTypeId >", value, "phiTypeId");
            return this;
        }

        public Criteria andPhiTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("PhiTypeId >=", value, "phiTypeId");
            return this;
        }

        public Criteria andPhiTypeIdLessThan(String value) {
            addCriterion("PhiTypeId <", value, "phiTypeId");
            return this;
        }

        public Criteria andPhiTypeIdLessThanOrEqualTo(String value) {
            addCriterion("PhiTypeId <=", value, "phiTypeId");
            return this;
        }

        public Criteria andPhiTypeIdLike(String value) {
            addCriterion("PhiTypeId like", value, "phiTypeId");
            return this;
        }

        public Criteria andPhiTypeIdNotLike(String value) {
            addCriterion("PhiTypeId not like", value, "phiTypeId");
            return this;
        }

        public Criteria andPhiTypeIdIn(List values) {
            addCriterion("PhiTypeId in", values, "phiTypeId");
            return this;
        }

        public Criteria andPhiTypeIdNotIn(List values) {
            addCriterion("PhiTypeId not in", values, "phiTypeId");
            return this;
        }

        public Criteria andPhiTypeIdBetween(String value1, String value2) {
            addCriterion("PhiTypeId between", value1, value2, "phiTypeId");
            return this;
        }

        public Criteria andPhiTypeIdNotBetween(String value1, String value2) {
            addCriterion("PhiTypeId not between", value1, value2, "phiTypeId");
            return this;
        }

        public Criteria andApplyAttrIsNull() {
            addCriterion("ApplyAttr is null");
            return this;
        }

        public Criteria andApplyAttrIsNotNull() {
            addCriterion("ApplyAttr is not null");
            return this;
        }

        public Criteria andApplyAttrEqualTo(String value) {
            addCriterion("ApplyAttr =", value, "applyAttr");
            return this;
        }

        public Criteria andApplyAttrNotEqualTo(String value) {
            addCriterion("ApplyAttr <>", value, "applyAttr");
            return this;
        }

        public Criteria andApplyAttrGreaterThan(String value) {
            addCriterion("ApplyAttr >", value, "applyAttr");
            return this;
        }

        public Criteria andApplyAttrGreaterThanOrEqualTo(String value) {
            addCriterion("ApplyAttr >=", value, "applyAttr");
            return this;
        }

        public Criteria andApplyAttrLessThan(String value) {
            addCriterion("ApplyAttr <", value, "applyAttr");
            return this;
        }

        public Criteria andApplyAttrLessThanOrEqualTo(String value) {
            addCriterion("ApplyAttr <=", value, "applyAttr");
            return this;
        }

        public Criteria andApplyAttrLike(String value) {
            addCriterion("ApplyAttr like", value, "applyAttr");
            return this;
        }

        public Criteria andApplyAttrNotLike(String value) {
            addCriterion("ApplyAttr not like", value, "applyAttr");
            return this;
        }

        public Criteria andApplyAttrIn(List values) {
            addCriterion("ApplyAttr in", values, "applyAttr");
            return this;
        }

        public Criteria andApplyAttrNotIn(List values) {
            addCriterion("ApplyAttr not in", values, "applyAttr");
            return this;
        }

        public Criteria andApplyAttrBetween(String value1, String value2) {
            addCriterion("ApplyAttr between", value1, value2, "applyAttr");
            return this;
        }

        public Criteria andApplyAttrNotBetween(String value1, String value2) {
            addCriterion("ApplyAttr not between", value1, value2, "applyAttr");
            return this;
        }

        public Criteria andAuthSignIsNull() {
            addCriterion("AuthSign is null");
            return this;
        }

        public Criteria andAuthSignIsNotNull() {
            addCriterion("AuthSign is not null");
            return this;
        }

        public Criteria andAuthSignEqualTo(Short value) {
            addCriterion("AuthSign =", value, "authSign");
            return this;
        }

        public Criteria andAuthSignNotEqualTo(Short value) {
            addCriterion("AuthSign <>", value, "authSign");
            return this;
        }

        public Criteria andAuthSignGreaterThan(Short value) {
            addCriterion("AuthSign >", value, "authSign");
            return this;
        }

        public Criteria andAuthSignGreaterThanOrEqualTo(Short value) {
            addCriterion("AuthSign >=", value, "authSign");
            return this;
        }

        public Criteria andAuthSignLessThan(Short value) {
            addCriterion("AuthSign <", value, "authSign");
            return this;
        }

        public Criteria andAuthSignLessThanOrEqualTo(Short value) {
            addCriterion("AuthSign <=", value, "authSign");
            return this;
        }

        public Criteria andAuthSignIn(List values) {
            addCriterion("AuthSign in", values, "authSign");
            return this;
        }

        public Criteria andAuthSignNotIn(List values) {
            addCriterion("AuthSign not in", values, "authSign");
            return this;
        }

        public Criteria andAuthSignBetween(Short value1, Short value2) {
            addCriterion("AuthSign between", value1, value2, "authSign");
            return this;
        }

        public Criteria andAuthSignNotBetween(Short value1, Short value2) {
            addCriterion("AuthSign not between", value1, value2, "authSign");
            return this;
        }

        public Criteria andW2SignIsNull() {
            addCriterion("W2Sign is null");
            return this;
        }

        public Criteria andW2SignIsNotNull() {
            addCriterion("W2Sign is not null");
            return this;
        }

        public Criteria andW2SignEqualTo(Short value) {
            addCriterion("W2Sign =", value, "w2Sign");
            return this;
        }

        public Criteria andW2SignNotEqualTo(Short value) {
            addCriterion("W2Sign <>", value, "w2Sign");
            return this;
        }

        public Criteria andW2SignGreaterThan(Short value) {
            addCriterion("W2Sign >", value, "w2Sign");
            return this;
        }

        public Criteria andW2SignGreaterThanOrEqualTo(Short value) {
            addCriterion("W2Sign >=", value, "w2Sign");
            return this;
        }

        public Criteria andW2SignLessThan(Short value) {
            addCriterion("W2Sign <", value, "w2Sign");
            return this;
        }

        public Criteria andW2SignLessThanOrEqualTo(Short value) {
            addCriterion("W2Sign <=", value, "w2Sign");
            return this;
        }

        public Criteria andW2SignIn(List values) {
            addCriterion("W2Sign in", values, "w2Sign");
            return this;
        }

        public Criteria andW2SignNotIn(List values) {
            addCriterion("W2Sign not in", values, "w2Sign");
            return this;
        }

        public Criteria andW2SignBetween(Short value1, Short value2) {
            addCriterion("W2Sign between", value1, value2, "w2Sign");
            return this;
        }

        public Criteria andW2SignNotBetween(Short value1, Short value2) {
            addCriterion("W2Sign not between", value1, value2, "w2Sign");
            return this;
        }

        public Criteria andBatchIdIsNull() {
            addCriterion("BatchId is null");
            return this;
        }

        public Criteria andBatchIdIsNotNull() {
            addCriterion("BatchId is not null");
            return this;
        }

        public Criteria andBatchIdEqualTo(String value) {
            addCriterion("BatchId =", value, "batchId");
            return this;
        }

        public Criteria andBatchIdNotEqualTo(String value) {
            addCriterion("BatchId <>", value, "batchId");
            return this;
        }

        public Criteria andBatchIdGreaterThan(String value) {
            addCriterion("BatchId >", value, "batchId");
            return this;
        }

        public Criteria andBatchIdGreaterThanOrEqualTo(String value) {
            addCriterion("BatchId >=", value, "batchId");
            return this;
        }

        public Criteria andBatchIdLessThan(String value) {
            addCriterion("BatchId <", value, "batchId");
            return this;
        }

        public Criteria andBatchIdLessThanOrEqualTo(String value) {
            addCriterion("BatchId <=", value, "batchId");
            return this;
        }

        public Criteria andBatchIdLike(String value) {
            addCriterion("BatchId like", value, "batchId");
            return this;
        }

        public Criteria andBatchIdNotLike(String value) {
            addCriterion("BatchId not like", value, "batchId");
            return this;
        }

        public Criteria andBatchIdIn(List values) {
            addCriterion("BatchId in", values, "batchId");
            return this;
        }

        public Criteria andBatchIdNotIn(List values) {
            addCriterion("BatchId not in", values, "batchId");
            return this;
        }

        public Criteria andBatchIdBetween(String value1, String value2) {
            addCriterion("BatchId between", value1, value2, "batchId");
            return this;
        }

        public Criteria andBatchIdNotBetween(String value1, String value2) {
            addCriterion("BatchId not between", value1, value2, "batchId");
            return this;
        }

        public Criteria andPressCardScaleIsNull() {
            addCriterion("PressCardScale is null");
            return this;
        }

        public Criteria andPressCardScaleIsNotNull() {
            addCriterion("PressCardScale is not null");
            return this;
        }

        public Criteria andPressCardScaleEqualTo(String value) {
            addCriterion("PressCardScale =", value, "pressCardScale");
            return this;
        }

        public Criteria andPressCardScaleNotEqualTo(String value) {
            addCriterion("PressCardScale <>", value, "pressCardScale");
            return this;
        }

        public Criteria andPressCardScaleGreaterThan(String value) {
            addCriterion("PressCardScale >", value, "pressCardScale");
            return this;
        }

        public Criteria andPressCardScaleGreaterThanOrEqualTo(String value) {
            addCriterion("PressCardScale >=", value, "pressCardScale");
            return this;
        }

        public Criteria andPressCardScaleLessThan(String value) {
            addCriterion("PressCardScale <", value, "pressCardScale");
            return this;
        }

        public Criteria andPressCardScaleLessThanOrEqualTo(String value) {
            addCriterion("PressCardScale <=", value, "pressCardScale");
            return this;
        }

        public Criteria andPressCardScaleLike(String value) {
            addCriterion("PressCardScale like", value, "pressCardScale");
            return this;
        }

        public Criteria andPressCardScaleNotLike(String value) {
            addCriterion("PressCardScale not like", value, "pressCardScale");
            return this;
        }

        public Criteria andPressCardScaleIn(List values) {
            addCriterion("PressCardScale in", values, "pressCardScale");
            return this;
        }

        public Criteria andPressCardScaleNotIn(List values) {
            addCriterion("PressCardScale not in", values, "pressCardScale");
            return this;
        }

        public Criteria andPressCardScaleBetween(String value1, String value2) {
            addCriterion("PressCardScale between", value1, value2, "pressCardScale");
            return this;
        }

        public Criteria andPressCardScaleNotBetween(String value1, String value2) {
            addCriterion("PressCardScale not between", value1, value2, "pressCardScale");
            return this;
        }

        public Criteria andWorkSheetAmtIsNull() {
            addCriterion("WorkSheetAmt is null");
            return this;
        }

        public Criteria andWorkSheetAmtIsNotNull() {
            addCriterion("WorkSheetAmt is not null");
            return this;
        }

        public Criteria andWorkSheetAmtEqualTo(Long value) {
            addCriterion("WorkSheetAmt =", value, "workSheetAmt");
            return this;
        }

        public Criteria andWorkSheetAmtNotEqualTo(Long value) {
            addCriterion("WorkSheetAmt <>", value, "workSheetAmt");
            return this;
        }

        public Criteria andWorkSheetAmtGreaterThan(Long value) {
            addCriterion("WorkSheetAmt >", value, "workSheetAmt");
            return this;
        }

        public Criteria andWorkSheetAmtGreaterThanOrEqualTo(Long value) {
            addCriterion("WorkSheetAmt >=", value, "workSheetAmt");
            return this;
        }

        public Criteria andWorkSheetAmtLessThan(Long value) {
            addCriterion("WorkSheetAmt <", value, "workSheetAmt");
            return this;
        }

        public Criteria andWorkSheetAmtLessThanOrEqualTo(Long value) {
            addCriterion("WorkSheetAmt <=", value, "workSheetAmt");
            return this;
        }

        public Criteria andWorkSheetAmtIn(List values) {
            addCriterion("WorkSheetAmt in", values, "workSheetAmt");
            return this;
        }

        public Criteria andWorkSheetAmtNotIn(List values) {
            addCriterion("WorkSheetAmt not in", values, "workSheetAmt");
            return this;
        }

        public Criteria andWorkSheetAmtBetween(Long value1, Long value2) {
            addCriterion("WorkSheetAmt between", value1, value2, "workSheetAmt");
            return this;
        }

        public Criteria andWorkSheetAmtNotBetween(Long value1, Long value2) {
            addCriterion("WorkSheetAmt not between", value1, value2, "workSheetAmt");
            return this;
        }

        public Criteria andSamIdBeginIsNull() {
            addCriterion("SamIdBegin is null");
            return this;
        }

        public Criteria andSamIdBeginIsNotNull() {
            addCriterion("SamIdBegin is not null");
            return this;
        }

        public Criteria andSamIdBeginEqualTo(String value) {
            addCriterion("SamIdBegin =", value, "samIdBegin");
            return this;
        }

        public Criteria andSamIdBeginNotEqualTo(String value) {
            addCriterion("SamIdBegin <>", value, "samIdBegin");
            return this;
        }

        public Criteria andSamIdBeginGreaterThan(String value) {
            addCriterion("SamIdBegin >", value, "samIdBegin");
            return this;
        }

        public Criteria andSamIdBeginGreaterThanOrEqualTo(String value) {
            addCriterion("SamIdBegin >=", value, "samIdBegin");
            return this;
        }

        public Criteria andSamIdBeginLessThan(String value) {
            addCriterion("SamIdBegin <", value, "samIdBegin");
            return this;
        }

        public Criteria andSamIdBeginLessThanOrEqualTo(String value) {
            addCriterion("SamIdBegin <=", value, "samIdBegin");
            return this;
        }

        public Criteria andSamIdBeginLike(String value) {
            addCriterion("SamIdBegin like", value, "samIdBegin");
            return this;
        }

        public Criteria andSamIdBeginNotLike(String value) {
            addCriterion("SamIdBegin not like", value, "samIdBegin");
            return this;
        }

        public Criteria andSamIdBeginIn(List values) {
            addCriterion("SamIdBegin in", values, "samIdBegin");
            return this;
        }

        public Criteria andSamIdBeginNotIn(List values) {
            addCriterion("SamIdBegin not in", values, "samIdBegin");
            return this;
        }

        public Criteria andSamIdBeginBetween(String value1, String value2) {
            addCriterion("SamIdBegin between", value1, value2, "samIdBegin");
            return this;
        }

        public Criteria andSamIdBeginNotBetween(String value1, String value2) {
            addCriterion("SamIdBegin not between", value1, value2, "samIdBegin");
            return this;
        }

        public Criteria andSamIdEndIsNull() {
            addCriterion("SamIdEnd is null");
            return this;
        }

        public Criteria andSamIdEndIsNotNull() {
            addCriterion("SamIdEnd is not null");
            return this;
        }

        public Criteria andSamIdEndEqualTo(String value) {
            addCriterion("SamIdEnd =", value, "samIdEnd");
            return this;
        }

        public Criteria andSamIdEndNotEqualTo(String value) {
            addCriterion("SamIdEnd <>", value, "samIdEnd");
            return this;
        }

        public Criteria andSamIdEndGreaterThan(String value) {
            addCriterion("SamIdEnd >", value, "samIdEnd");
            return this;
        }

        public Criteria andSamIdEndGreaterThanOrEqualTo(String value) {
            addCriterion("SamIdEnd >=", value, "samIdEnd");
            return this;
        }

        public Criteria andSamIdEndLessThan(String value) {
            addCriterion("SamIdEnd <", value, "samIdEnd");
            return this;
        }

        public Criteria andSamIdEndLessThanOrEqualTo(String value) {
            addCriterion("SamIdEnd <=", value, "samIdEnd");
            return this;
        }

        public Criteria andSamIdEndLike(String value) {
            addCriterion("SamIdEnd like", value, "samIdEnd");
            return this;
        }

        public Criteria andSamIdEndNotLike(String value) {
            addCriterion("SamIdEnd not like", value, "samIdEnd");
            return this;
        }

        public Criteria andSamIdEndIn(List values) {
            addCriterion("SamIdEnd in", values, "samIdEnd");
            return this;
        }

        public Criteria andSamIdEndNotIn(List values) {
            addCriterion("SamIdEnd not in", values, "samIdEnd");
            return this;
        }

        public Criteria andSamIdEndBetween(String value1, String value2) {
            addCriterion("SamIdEnd between", value1, value2, "samIdEnd");
            return this;
        }

        public Criteria andSamIdEndNotBetween(String value1, String value2) {
            addCriterion("SamIdEnd not between", value1, value2, "samIdEnd");
            return this;
        }

        public Criteria andSamIdIsNull() {
            addCriterion("SamId is null");
            return this;
        }

        public Criteria andSamIdIsNotNull() {
            addCriterion("SamId is not null");
            return this;
        }

        public Criteria andSamIdEqualTo(String value) {
            addCriterion("SamId =", value, "samId");
            return this;
        }

        public Criteria andSamIdNotEqualTo(String value) {
            addCriterion("SamId <>", value, "samId");
            return this;
        }

        public Criteria andSamIdGreaterThan(String value) {
            addCriterion("SamId >", value, "samId");
            return this;
        }

        public Criteria andSamIdGreaterThanOrEqualTo(String value) {
            addCriterion("SamId >=", value, "samId");
            return this;
        }

        public Criteria andSamIdLessThan(String value) {
            addCriterion("SamId <", value, "samId");
            return this;
        }

        public Criteria andSamIdLessThanOrEqualTo(String value) {
            addCriterion("SamId <=", value, "samId");
            return this;
        }

        public Criteria andSamIdLike(String value) {
            addCriterion("SamId like", value, "samId");
            return this;
        }

        public Criteria andSamIdNotLike(String value) {
            addCriterion("SamId not like", value, "samId");
            return this;
        }

        public Criteria andSamIdIn(List values) {
            addCriterion("SamId in", values, "samId");
            return this;
        }

        public Criteria andSamIdNotIn(List values) {
            addCriterion("SamId not in", values, "samId");
            return this;
        }

        public Criteria andSamIdBetween(String value1, String value2) {
            addCriterion("SamId between", value1, value2, "samId");
            return this;
        }

        public Criteria andSamIdNotBetween(String value1, String value2) {
            addCriterion("SamId not between", value1, value2, "samId");
            return this;
        }

        public Criteria andIssueDoneAmtIsNull() {
            addCriterion("IssueDoneAmt is null");
            return this;
        }

        public Criteria andIssueDoneAmtIsNotNull() {
            addCriterion("IssueDoneAmt is not null");
            return this;
        }

        public Criteria andIssueDoneAmtEqualTo(Long value) {
            addCriterion("IssueDoneAmt =", value, "issueDoneAmt");
            return this;
        }

        public Criteria andIssueDoneAmtNotEqualTo(Long value) {
            addCriterion("IssueDoneAmt <>", value, "issueDoneAmt");
            return this;
        }

        public Criteria andIssueDoneAmtGreaterThan(Long value) {
            addCriterion("IssueDoneAmt >", value, "issueDoneAmt");
            return this;
        }

        public Criteria andIssueDoneAmtGreaterThanOrEqualTo(Long value) {
            addCriterion("IssueDoneAmt >=", value, "issueDoneAmt");
            return this;
        }

        public Criteria andIssueDoneAmtLessThan(Long value) {
            addCriterion("IssueDoneAmt <", value, "issueDoneAmt");
            return this;
        }

        public Criteria andIssueDoneAmtLessThanOrEqualTo(Long value) {
            addCriterion("IssueDoneAmt <=", value, "issueDoneAmt");
            return this;
        }

        public Criteria andIssueDoneAmtIn(List values) {
            addCriterion("IssueDoneAmt in", values, "issueDoneAmt");
            return this;
        }

        public Criteria andIssueDoneAmtNotIn(List values) {
            addCriterion("IssueDoneAmt not in", values, "issueDoneAmt");
            return this;
        }

        public Criteria andIssueDoneAmtBetween(Long value1, Long value2) {
            addCriterion("IssueDoneAmt between", value1, value2, "issueDoneAmt");
            return this;
        }

        public Criteria andIssueDoneAmtNotBetween(Long value1, Long value2) {
            addCriterion("IssueDoneAmt not between", value1, value2, "issueDoneAmt");
            return this;
        }

        public Criteria andFormStateIsNull() {
            addCriterion("FormState is null");
            return this;
        }

        public Criteria andFormStateIsNotNull() {
            addCriterion("FormState is not null");
            return this;
        }

        public Criteria andFormStateEqualTo(Short value) {
            addCriterion("FormState =", value, "formState");
            return this;
        }

        public Criteria andFormStateNotEqualTo(Short value) {
            addCriterion("FormState <>", value, "formState");
            return this;
        }

        public Criteria andFormStateGreaterThan(Short value) {
            addCriterion("FormState >", value, "formState");
            return this;
        }

        public Criteria andFormStateGreaterThanOrEqualTo(Short value) {
            addCriterion("FormState >=", value, "formState");
            return this;
        }

        public Criteria andFormStateLessThan(Short value) {
            addCriterion("FormState <", value, "formState");
            return this;
        }

        public Criteria andFormStateLessThanOrEqualTo(Short value) {
            addCriterion("FormState <=", value, "formState");
            return this;
        }

        public Criteria andFormStateIn(List values) {
            addCriterion("FormState in", values, "formState");
            return this;
        }

        public Criteria andFormStateNotIn(List values) {
            addCriterion("FormState not in", values, "formState");
            return this;
        }

        public Criteria andFormStateBetween(Short value1, Short value2) {
            addCriterion("FormState between", value1, value2, "formState");
            return this;
        }

        public Criteria andFormStateNotBetween(Short value1, Short value2) {
            addCriterion("FormState not between", value1, value2, "formState");
            return this;
        }

        public Criteria andIssueOperIDIsNull() {
            addCriterion("IssueOperID is null");
            return this;
        }

        public Criteria andIssueOperIDIsNotNull() {
            addCriterion("IssueOperID is not null");
            return this;
        }

        public Criteria andIssueOperIDEqualTo(String value) {
            addCriterion("IssueOperID =", value, "issueOperID");
            return this;
        }

        public Criteria andIssueOperIDNotEqualTo(String value) {
            addCriterion("IssueOperID <>", value, "issueOperID");
            return this;
        }

        public Criteria andIssueOperIDGreaterThan(String value) {
            addCriterion("IssueOperID >", value, "issueOperID");
            return this;
        }

        public Criteria andIssueOperIDGreaterThanOrEqualTo(String value) {
            addCriterion("IssueOperID >=", value, "issueOperID");
            return this;
        }

        public Criteria andIssueOperIDLessThan(String value) {
            addCriterion("IssueOperID <", value, "issueOperID");
            return this;
        }

        public Criteria andIssueOperIDLessThanOrEqualTo(String value) {
            addCriterion("IssueOperID <=", value, "issueOperID");
            return this;
        }

        public Criteria andIssueOperIDLike(String value) {
            addCriterion("IssueOperID like", value, "issueOperID");
            return this;
        }

        public Criteria andIssueOperIDNotLike(String value) {
            addCriterion("IssueOperID not like", value, "issueOperID");
            return this;
        }

        public Criteria andIssueOperIDIn(List values) {
            addCriterion("IssueOperID in", values, "issueOperID");
            return this;
        }

        public Criteria andIssueOperIDNotIn(List values) {
            addCriterion("IssueOperID not in", values, "issueOperID");
            return this;
        }

        public Criteria andIssueOperIDBetween(String value1, String value2) {
            addCriterion("IssueOperID between", value1, value2, "issueOperID");
            return this;
        }

        public Criteria andIssueOperIDNotBetween(String value1, String value2) {
            addCriterion("IssueOperID not between", value1, value2, "issueOperID");
            return this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("Remarks is null");
            return this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("Remarks is not null");
            return this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("Remarks =", value, "remarks");
            return this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("Remarks <>", value, "remarks");
            return this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("Remarks >", value, "remarks");
            return this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("Remarks >=", value, "remarks");
            return this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("Remarks <", value, "remarks");
            return this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("Remarks <=", value, "remarks");
            return this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("Remarks like", value, "remarks");
            return this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("Remarks not like", value, "remarks");
            return this;
        }

        public Criteria andRemarksIn(List values) {
            addCriterion("Remarks in", values, "remarks");
            return this;
        }

        public Criteria andRemarksNotIn(List values) {
            addCriterion("Remarks not in", values, "remarks");
            return this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("Remarks between", value1, value2, "remarks");
            return this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("Remarks not between", value1, value2, "remarks");
            return this;
        }


        public Criteria andFormTimeEqualTo(String value) {
            addCriterion("FormTime =", value, "FormTime");
            return this;
        }

        public Criteria andFormTimeNotEqualTo(String value) {
            addCriterion("FormTime <>", value, "FormTime");
            return this;
        }

        public Criteria andFormTimeGreaterThan(String value) {
            addCriterion("FormTime >", value, "FormTime");
            return this;
        }

        public Criteria andFormTimeGreaterThanOrEqualTo(String value) {
            addCriterion("FormTime >=", value, "FormTime");
            return this;
        }

        public Criteria andFormTimeLessThan(String value) {
            addCriterion("FormTime <", value, "FormTime");
            return this;
        }

        public Criteria andFormTimeLessThanOrEqualTo(String value) {
            addCriterion("FormTime <=", value, "FormTime");
            return this;
        }

        public Criteria andFormTimeLike(String value) {
            addCriterion("FormTime like", value, "FormTime");
            return this;
        }

        public Criteria andFormTimeNotLike(String value) {
            addCriterion("FormTime not like", value, "FormTime");
            return this;
        }

        public Criteria andFormTimeIn(List values) {
            addCriterion("FormTime in", values, "FormTime");
            return this;
        }

        public Criteria andFormTimeNotIn(List values) {
            addCriterion("FormTime not in", values, "FormTime");
            return this;
        }

        public Criteria andFormTimeBetween(String value1, String value2) {
            addCriterion("FormTime between", value1, value2, "FormTime");
            return this;
        }

        public Criteria andFormTimeNotBetween(String value1, String value2) {
            addCriterion("FormTime not between", value1, value2, "FormTime");
            return this;
        }
        public Criteria andOperationTypeIsNull() {
            addCriterion("OperationType is null");
            return this;
        }

        public Criteria andOperationTypeIsNotNull() {
            addCriterion("OperationType is not null");
            return this;
        }

        public Criteria andOperationTypeEqualTo(Short value) {
            addCriterion("OperationType =", value, "operationType");
            return this;
        }

        public Criteria andOperationTypeNotEqualTo(Short value) {
            addCriterion("OperationType <>", value, "operationType");
            return this;
        }

        public Criteria andOperationTypeGreaterThan(Short value) {
            addCriterion("OperationType >", value, "operationType");
            return this;
        }

        public Criteria andOperationTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("OperationType >=", value, "operationType");
            return this;
        }

        public Criteria andOperationTypeLessThan(Short value) {
            addCriterion("OperationType <", value, "operationType");
            return this;
        }

        public Criteria andOperationTypeLessThanOrEqualTo(Short value) {
            addCriterion("OperationType <=", value, "operationType");
            return this;
        }

        public Criteria andOperationTypeIn(List values) {
            addCriterion("OperationType in", values, "operationType");
            return this;
        }

        public Criteria andOperationTypeNotIn(List values) {
            addCriterion("OperationType not in", values, "operationType");
            return this;
        }

        public Criteria andOperationTypeBetween(Short value1, Short value2) {
            addCriterion("OperationType between", value1, value2, "operationType");
            return this;
        }

        public Criteria andOperationTypeNotBetween(Short value1, Short value2) {
            addCriterion("OperationType not between", value1, value2, "operationType");
            return this;
        }
        
    }
}