package com.yly.issue;

import java.util.Date;

public class Mwsissuetb {
	private Short operationType;
    private String appNo;
    private String taskNo;
    private Integer unitId;
    private Short consumeType;
	private Short paymentType;
	private Long unitPrice;
	private Short taskState;
	private String OAappNo;
	private String beginDate_f;
	private String endDate_f;
	public String getBeginDate_f() {
		return beginDate_f;
	}

	public void setBeginDate_f(String beginDate_f) {
		this.beginDate_f = beginDate_f;
	}

	public String getEndDate_f() {
		return endDate_f;
	}

	public void setEndDate_f(String endDate_f) {
		this.endDate_f = endDate_f;
	}

	public String getOAappNo() {
		return OAappNo;
	}

	public void setOAappNo(String oAappNo) {
		OAappNo = oAappNo;
	}
    public Short getOperationType() {
		return operationType;
	}

	public void setOperationType(Short operationType) {
		this.operationType = operationType;
	}

	private String manufacId;

	public String getManufacId() {
		return manufacId;
	}

	public void setManufacId(String manufacId) {
		this.manufacId = manufacId;
	}

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column mwsissuetb.FormNo
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    private String formNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column mwsissuetb.TaskCtrlNo
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    private String taskCtrlNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column mwsissuetb.FormTime
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    private String formTime;

    public String getFormTime() {
		return formTime;
	}

	public void setFormTime(String formTime) {
		this.formTime = formTime;
	}

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column mwsissuetb.WsSnr
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    private Short wsSnr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column mwsissuetb.ProdId
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    private String prodId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column mwsissuetb.KeyType
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    private Short keyType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column mwsissuetb.BinFileVer
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    private String binFileVer;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column mwsissuetb.PhiTypeId
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    private String phiTypeId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column mwsissuetb.ApplyAttr
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    private String applyAttr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column mwsissuetb.AuthSign
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    private Short authSign;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column mwsissuetb.W2Sign
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    private Short w2Sign;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column mwsissuetb.BatchId
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    private String batchId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column mwsissuetb.PressCardScale
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    private String pressCardScale;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column mwsissuetb.WorkSheetAmt
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    private Long workSheetAmt;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column mwsissuetb.SamIdBegin
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    private String samIdBegin;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column mwsissuetb.SamIdEnd
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    private String samIdEnd;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column mwsissuetb.SamId
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    private String samId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column mwsissuetb.IssueDoneAmt
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    private Long issueDoneAmt;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column mwsissuetb.FormState
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    private Short formState;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column mwsissuetb.IssueOperID
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    private String issueOperID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column mwsissuetb.Remarks
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    private String remarks;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column mwsissuetb.FormNo
     *
     * @return the value of mwsissuetb.FormNo
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public String getFormNo() {
        return formNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column mwsissuetb.FormNo
     *
     * @param formNo the value for mwsissuetb.FormNo
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public void setFormNo(String formNo) {
        this.formNo = formNo == null ? null : formNo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column mwsissuetb.TaskCtrlNo
     *
     * @return the value of mwsissuetb.TaskCtrlNo
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public String getTaskCtrlNo() {
        return taskCtrlNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column mwsissuetb.TaskCtrlNo
     *
     * @param taskCtrlNo the value for mwsissuetb.TaskCtrlNo
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public void setTaskCtrlNo(String taskCtrlNo) {
        this.taskCtrlNo = taskCtrlNo == null ? null : taskCtrlNo.trim();
    }

 

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column mwsissuetb.WsSnr
     *
     * @return the value of mwsissuetb.WsSnr
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public Short getWsSnr() {
        return wsSnr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column mwsissuetb.WsSnr
     *
     * @param wsSnr the value for mwsissuetb.WsSnr
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public void setWsSnr(Short wsSnr) {
        this.wsSnr = wsSnr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column mwsissuetb.ProdId
     *
     * @return the value of mwsissuetb.ProdId
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public String getProdId() {
        return prodId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column mwsissuetb.ProdId
     *
     * @param prodId the value for mwsissuetb.ProdId
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public void setProdId(String prodId) {
        this.prodId = prodId == null ? null : prodId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column mwsissuetb.KeyType
     *
     * @return the value of mwsissuetb.KeyType
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public Short getKeyType() {
        return keyType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column mwsissuetb.KeyType
     *
     * @param keyType the value for mwsissuetb.KeyType
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public void setKeyType(Short keyType) {
        this.keyType = keyType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column mwsissuetb.BinFileVer
     *
     * @return the value of mwsissuetb.BinFileVer
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public String getBinFileVer() {
        return binFileVer;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column mwsissuetb.BinFileVer
     *
     * @param binFileVer the value for mwsissuetb.BinFileVer
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public void setBinFileVer(String binFileVer) {
        this.binFileVer = binFileVer == null ? null : binFileVer.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column mwsissuetb.PhiTypeId
     *
     * @return the value of mwsissuetb.PhiTypeId
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public String getPhiTypeId() {
        return phiTypeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column mwsissuetb.PhiTypeId
     *
     * @param phiTypeId the value for mwsissuetb.PhiTypeId
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public void setPhiTypeId(String phiTypeId) {
        this.phiTypeId = phiTypeId == null ? null : phiTypeId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column mwsissuetb.ApplyAttr
     *
     * @return the value of mwsissuetb.ApplyAttr
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public String getApplyAttr() {
        return applyAttr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column mwsissuetb.ApplyAttr
     *
     * @param applyAttr the value for mwsissuetb.ApplyAttr
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public void setApplyAttr(String applyAttr) {
        this.applyAttr = applyAttr == null ? null : applyAttr.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column mwsissuetb.AuthSign
     *
     * @return the value of mwsissuetb.AuthSign
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public Short getAuthSign() {
        return authSign;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column mwsissuetb.AuthSign
     *
     * @param authSign the value for mwsissuetb.AuthSign
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public void setAuthSign(Short authSign) {
        this.authSign = authSign;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column mwsissuetb.W2Sign
     *
     * @return the value of mwsissuetb.W2Sign
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public Short getW2Sign() {
        return w2Sign;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column mwsissuetb.W2Sign
     *
     * @param w2Sign the value for mwsissuetb.W2Sign
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public void setW2Sign(Short w2Sign) {
        this.w2Sign = w2Sign;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column mwsissuetb.BatchId
     *
     * @return the value of mwsissuetb.BatchId
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column mwsissuetb.BatchId
     *
     * @param batchId the value for mwsissuetb.BatchId
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId == null ? null : batchId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column mwsissuetb.PressCardScale
     *
     * @return the value of mwsissuetb.PressCardScale
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public String getPressCardScale() {
        return pressCardScale;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column mwsissuetb.PressCardScale
     *
     * @param pressCardScale the value for mwsissuetb.PressCardScale
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public void setPressCardScale(String pressCardScale) {
        this.pressCardScale = pressCardScale == null ? null : pressCardScale.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column mwsissuetb.WorkSheetAmt
     *
     * @return the value of mwsissuetb.WorkSheetAmt
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public Long getWorkSheetAmt() {
        return workSheetAmt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column mwsissuetb.WorkSheetAmt
     *
     * @param workSheetAmt the value for mwsissuetb.WorkSheetAmt
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public void setWorkSheetAmt(Long workSheetAmt) {
        this.workSheetAmt = workSheetAmt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column mwsissuetb.SamIdBegin
     *
     * @return the value of mwsissuetb.SamIdBegin
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public String getSamIdBegin() {
        return samIdBegin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column mwsissuetb.SamIdBegin
     *
     * @param samIdBegin the value for mwsissuetb.SamIdBegin
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public void setSamIdBegin(String samIdBegin) {
        this.samIdBegin = samIdBegin == null ? null : samIdBegin.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column mwsissuetb.SamIdEnd
     *
     * @return the value of mwsissuetb.SamIdEnd
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public String getSamIdEnd() {
        return samIdEnd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column mwsissuetb.SamIdEnd
     *
     * @param samIdEnd the value for mwsissuetb.SamIdEnd
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public void setSamIdEnd(String samIdEnd) {
        this.samIdEnd = samIdEnd == null ? null : samIdEnd.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column mwsissuetb.SamId
     *
     * @return the value of mwsissuetb.SamId
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public String getSamId() {
        return samId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column mwsissuetb.SamId
     *
     * @param samId the value for mwsissuetb.SamId
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public void setSamId(String samId) {
        this.samId = samId == null ? null : samId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column mwsissuetb.IssueDoneAmt
     *
     * @return the value of mwsissuetb.IssueDoneAmt
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public Long getIssueDoneAmt() {
        return issueDoneAmt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column mwsissuetb.IssueDoneAmt
     *
     * @param issueDoneAmt the value for mwsissuetb.IssueDoneAmt
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public void setIssueDoneAmt(Long issueDoneAmt) {
        this.issueDoneAmt = issueDoneAmt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column mwsissuetb.FormState
     *
     * @return the value of mwsissuetb.FormState
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public Short getFormState() {
        return formState;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column mwsissuetb.FormState
     *
     * @param formState the value for mwsissuetb.FormState
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public void setFormState(Short formState) {
        this.formState = formState;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column mwsissuetb.IssueOperID
     *
     * @return the value of mwsissuetb.IssueOperID
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public String getIssueOperID() {
        return issueOperID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column mwsissuetb.IssueOperID
     *
     * @param issueOperID the value for mwsissuetb.IssueOperID
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public void setIssueOperID(String issueOperID) {
        this.issueOperID = issueOperID == null ? null : issueOperID.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column mwsissuetb.Remarks
     *
     * @return the value of mwsissuetb.Remarks
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column mwsissuetb.Remarks
     *
     * @param remarks the value for mwsissuetb.Remarks
     *
     * @ibatorgenerated Tue May 10 13:31:14 CST 2016
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    public Integer getW2Limit() {
		return w2Limit;
	}

	public void setW2Limit(Integer w2Limit) {
		this.w2Limit = w2Limit;
	}

	public Integer getZeroExauthFlag() {
		return zeroExauthFlag;
	}

	public void setZeroExauthFlag(Integer zeroExauthFlag) {
		this.zeroExauthFlag = zeroExauthFlag;
	}

	public Integer getIsPki() {
		return isPki;
	}

	public void setIsPki(Integer isPki) {
		this.isPki = isPki;
	}

	public String getIsHTCard() {
		return isHTCard;
	}

	public void setIsHTCard(String isHTCard) {
		this.isHTCard = isHTCard;
	}
    
    private Integer w2Limit;
	private Integer zeroExauthFlag;
    private Integer isPki;
	private String isHTCard;

	public String getAppNo() {
		return appNo;
	}

	public void setAppNo(String appNo) {
		this.appNo = appNo;
	}

	public String getTaskNo() {
		return taskNo;
	}

	public void setTaskNo(String taskNo) {
		this.taskNo = taskNo;
	}

	public Integer getUnitId() {
		return unitId;
	}

	public void setUnitId(Integer unitId) {
		this.unitId = unitId;
	}

	public Short getConsumeType() {
		return consumeType;
	}

	public void setConsumeType(Short consumeType) {
		this.consumeType = consumeType;
	}

	public Short getPaymentType() {
		return paymentType;
	}

	public void setPaymentType(Short paymentType) {
		this.paymentType = paymentType;
	}

	public Long getUnitPrice() {
		return unitPrice;
	}

	public void setUnitPrice(Long unitPrice) {
		this.unitPrice = unitPrice;
	}

	public Short getTaskState() {
		return taskState;
	}

	public void setTaskState(Short taskState) {
		this.taskState = taskState;
	}

}