package com.blue.expenses;

import java.util.Collection;

import com.eis.base.BaseForm;
import com.eis.cache.SingleDicMap;

public class ExpensesInfoForm extends BaseForm{
	private String depart_f;
	private String project_f;
	private Collection depart_f_options;
	private String results;
	
	public String getResults() {
		return results;
	}

	public void setResults(String results) {
		this.results = results;
	}

	public Collection getDepart_f_options() {
		return  SingleDicMap.getOptionCollection("9990");
	}

	public void setDepart_f_options(Collection collection) {
		depart_f_options = collection;
	}
	
	
	public String getDepart_f() {
		return depart_f;
	}

	public void setDepart_f(String depart_f) {
		this.depart_f = depart_f;
	}

	public String getProject_f() {
		return project_f;
	}

	public void setProject_f(String project_f) {
		this.project_f = project_f;
	}
    private String regUser;
    
	public String getRegUser() {
		return regUser;
	}

	public void setRegUser(String regUser) {
		this.regUser = regUser;
	}
	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column expenses_info.EXPENSES_ID
     *
     * @ibatorgenerated Tue Mar 25 17:11:02 CST 2014
     */
    private Long expensesId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column expenses_info.DEPT
     *
     * @ibatorgenerated Tue Mar 25 17:11:02 CST 2014
     */
    private String dept;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column expenses_info.PROJECT_NO
     *
     * @ibatorgenerated Tue Mar 25 17:11:02 CST 2014
     */
    private String projectNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column expenses_info.PROJECT_NAME
     *
     * @ibatorgenerated Tue Mar 25 17:11:02 CST 2014
     */
    private String projectName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column expenses_info.CURR_USER
     *
     * @ibatorgenerated Tue Mar 25 17:11:02 CST 2014
     */
    private String currUser;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column expenses_info.CURR_STAT
     *
     * @ibatorgenerated Tue Mar 25 17:11:02 CST 2014
     */
    private String currStat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column expenses_info.REG_DATE
     *
     * @ibatorgenerated Tue Mar 25 17:11:02 CST 2014
     */
    private String regDate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column expenses_info.EXPENSES_ID
     *
     * @return the value of expenses_info.EXPENSES_ID
     *
     * @ibatorgenerated Tue Mar 25 17:11:02 CST 2014
     */
    public Long getExpensesId() {
        return expensesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column expenses_info.EXPENSES_ID
     *
     * @param expensesId the value for expenses_info.EXPENSES_ID
     *
     * @ibatorgenerated Tue Mar 25 17:11:02 CST 2014
     */
    public void setExpensesId(Long expensesId) {
        this.expensesId = expensesId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column expenses_info.DEPT
     *
     * @return the value of expenses_info.DEPT
     *
     * @ibatorgenerated Tue Mar 25 17:11:02 CST 2014
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column expenses_info.DEPT
     *
     * @param dept the value for expenses_info.DEPT
     *
     * @ibatorgenerated Tue Mar 25 17:11:02 CST 2014
     */
    public void setDept(String dept) {
        this.dept = dept == null ? null : dept.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column expenses_info.PROJECT_NO
     *
     * @return the value of expenses_info.PROJECT_NO
     *
     * @ibatorgenerated Tue Mar 25 17:11:02 CST 2014
     */
    public String getProjectNo() {
        return projectNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column expenses_info.PROJECT_NO
     *
     * @param projectNo the value for expenses_info.PROJECT_NO
     *
     * @ibatorgenerated Tue Mar 25 17:11:02 CST 2014
     */
    public void setProjectNo(String projectNo) {
        this.projectNo = projectNo == null ? null : projectNo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column expenses_info.PROJECT_NAME
     *
     * @return the value of expenses_info.PROJECT_NAME
     *
     * @ibatorgenerated Tue Mar 25 17:11:02 CST 2014
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column expenses_info.PROJECT_NAME
     *
     * @param projectName the value for expenses_info.PROJECT_NAME
     *
     * @ibatorgenerated Tue Mar 25 17:11:02 CST 2014
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column expenses_info.CURR_USER
     *
     * @return the value of expenses_info.CURR_USER
     *
     * @ibatorgenerated Tue Mar 25 17:11:02 CST 2014
     */
    public String getCurrUser() {
        return currUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column expenses_info.CURR_USER
     *
     * @param currUser the value for expenses_info.CURR_USER
     *
     * @ibatorgenerated Tue Mar 25 17:11:02 CST 2014
     */
    public void setCurrUser(String currUser) {
        this.currUser = currUser == null ? null : currUser.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column expenses_info.CURR_STAT
     *
     * @return the value of expenses_info.CURR_STAT
     *
     * @ibatorgenerated Tue Mar 25 17:11:02 CST 2014
     */
    public String getCurrStat() {
        return currStat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column expenses_info.CURR_STAT
     *
     * @param currStat the value for expenses_info.CURR_STAT
     *
     * @ibatorgenerated Tue Mar 25 17:11:02 CST 2014
     */
    public void setCurrStat(String currStat) {
        this.currStat = currStat == null ? null : currStat.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column expenses_info.REG_DATE
     *
     * @return the value of expenses_info.REG_DATE
     *
     * @ibatorgenerated Tue Mar 25 17:11:02 CST 2014
     */
    public String getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column expenses_info.REG_DATE
     *
     * @param regDate the value for expenses_info.REG_DATE
     *
     * @ibatorgenerated Tue Mar 25 17:11:02 CST 2014
     */
    public void setRegDate(String regDate) {
        this.regDate = regDate == null ? null : regDate.trim();
    }

	private Collection fee_kind_options;
	public Collection getFee_kind_options() {
		return  SingleDicMap.getOptionCollection("7001");
	}


	public void setFee_kind_options(Collection fee_kind_options) {
		this.fee_kind_options = fee_kind_options;
	}
	private String regDate_from;
	private String regDate_to;

	public String getRegDate_from() {
		return regDate_from;
	}

	public void setRegDate_from(String regDate_from) {
		this.regDate_from = regDate_from;
	}

	public String getRegDate_to() {
		return regDate_to;
	}

	public void setRegDate_to(String regDate_to) {
		this.regDate_to = regDate_to;
	}
	private String userId;

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}
	private String feeKind_f;

	public String getFeeKind_f() {
		return feeKind_f;
	}

	public void setFeeKind_f(String feeKind_f) {
		this.feeKind_f = feeKind_f;
	}
	
	
}