package com.blue.expenses;

import com.blue.expenses.ExpensesInfo;
import com.blue.expenses.ExpensesInfoExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ExpensesInfoDAOImpl extends SqlMapClientDaoSupport implements ExpensesInfoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table expenses_info
     *
     * @ibatorgenerated Tue Apr 15 16:57:38 CST 2014
     */
    public ExpensesInfoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table expenses_info
     *
     * @ibatorgenerated Tue Apr 15 16:57:38 CST 2014
     */
    public int countByExample(ExpensesInfoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("expenses_info.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table expenses_info
     *
     * @ibatorgenerated Tue Apr 15 16:57:38 CST 2014
     */
    public int deleteByExample(ExpensesInfoExample example) {
        int rows = getSqlMapClientTemplate().delete("expenses_info.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table expenses_info
     *
     * @ibatorgenerated Tue Apr 15 16:57:38 CST 2014
     */
    public int deleteByPrimaryKey(Long expensesId) {
        ExpensesInfo key = new ExpensesInfo();
        key.setExpensesId(expensesId);
        int rows = getSqlMapClientTemplate().delete("expenses_info.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table expenses_info
     *
     * @ibatorgenerated Tue Apr 15 16:57:38 CST 2014
     */
    public void insert(ExpensesInfo record) {
        getSqlMapClientTemplate().insert("expenses_info.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table expenses_info
     *
     * @ibatorgenerated Tue Apr 15 16:57:38 CST 2014
     */
    public void insertSelective(ExpensesInfo record) {
        getSqlMapClientTemplate().insert("expenses_info.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table expenses_info
     *
     * @ibatorgenerated Tue Apr 15 16:57:38 CST 2014
     */
    public List selectByExample(ExpensesInfoExample example) {
        List list = getSqlMapClientTemplate().queryForList("expenses_info.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table expenses_info
     *
     * @ibatorgenerated Tue Apr 15 16:57:38 CST 2014
     */
    public ExpensesInfo selectByPrimaryKey(Long expensesId) {
        ExpensesInfo key = new ExpensesInfo();
        key.setExpensesId(expensesId);
        ExpensesInfo record = (ExpensesInfo) getSqlMapClientTemplate().queryForObject("expenses_info.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table expenses_info
     *
     * @ibatorgenerated Tue Apr 15 16:57:38 CST 2014
     */
    public int updateByExampleSelective(ExpensesInfo record, ExpensesInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("expenses_info.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table expenses_info
     *
     * @ibatorgenerated Tue Apr 15 16:57:38 CST 2014
     */
    public int updateByExample(ExpensesInfo record, ExpensesInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("expenses_info.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table expenses_info
     *
     * @ibatorgenerated Tue Apr 15 16:57:38 CST 2014
     */
    public int updateByPrimaryKeySelective(ExpensesInfo record) {
        int rows = getSqlMapClientTemplate().update("expenses_info.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table expenses_info
     *
     * @ibatorgenerated Tue Apr 15 16:57:38 CST 2014
     */
    public int updateByPrimaryKey(ExpensesInfo record) {
        int rows = getSqlMapClientTemplate().update("expenses_info.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table expenses_info
     *
     * @ibatorgenerated Tue Apr 15 16:57:38 CST 2014
     */
    private static class UpdateByExampleParms extends ExpensesInfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, ExpensesInfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}