package com.yly.conf;

import com.yly.conf.Callfuncconf;
import com.yly.conf.CallfuncconfExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CallfuncconfDAOImpl extends SqlMapClientDaoSupport implements CallfuncconfDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public CallfuncconfDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public int countByExample(CallfuncconfExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("callfuncconf.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public int deleteByExample(CallfuncconfExample example) {
        int rows = getSqlMapClientTemplate().delete("callfuncconf.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public int deleteByPrimaryKey(String callerId) {
        Callfuncconf key = new Callfuncconf();
        key.setCallerId(callerId);
        int rows = getSqlMapClientTemplate().delete("callfuncconf.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public void insert(Callfuncconf record) {
        getSqlMapClientTemplate().insert("callfuncconf.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public void insertSelective(Callfuncconf record) {
        getSqlMapClientTemplate().insert("callfuncconf.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public List selectByExample(CallfuncconfExample example) {
        List list = getSqlMapClientTemplate().queryForList("callfuncconf.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public Callfuncconf selectByPrimaryKey(String callerId) {
        Callfuncconf key = new Callfuncconf();
        key.setCallerId(callerId);
        Callfuncconf record = (Callfuncconf) getSqlMapClientTemplate().queryForObject("callfuncconf.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public int updateByExampleSelective(Callfuncconf record, CallfuncconfExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("callfuncconf.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public int updateByExample(Callfuncconf record, CallfuncconfExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("callfuncconf.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public int updateByPrimaryKeySelective(Callfuncconf record) {
        int rows = getSqlMapClientTemplate().update("callfuncconf.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public int updateByPrimaryKey(Callfuncconf record) {
        int rows = getSqlMapClientTemplate().update("callfuncconf.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    private static class UpdateByExampleParms extends CallfuncconfExample {
        private Object record;

        public UpdateByExampleParms(Object record, CallfuncconfExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}