package com.yly.conf;

import com.yly.conf.Callfuncconf;
import com.yly.conf.CallfuncconfExample;
import java.util.List;

public interface CallfuncconfDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    int countByExample(CallfuncconfExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    int deleteByExample(CallfuncconfExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    int deleteByPrimaryKey(String callerId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    void insert(Callfuncconf record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    void insertSelective(Callfuncconf record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    List selectByExample(CallfuncconfExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    Callfuncconf selectByPrimaryKey(String callerId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    int updateByExampleSelective(Callfuncconf record, CallfuncconfExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    int updateByExample(Callfuncconf record, CallfuncconfExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    int updateByPrimaryKeySelective(Callfuncconf record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table callfuncconf
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    int updateByPrimaryKey(Callfuncconf record);
}