package com.yly.conf;

import java.util.Collection;

import com.eis.base.BaseForm;
import com.eis.cache.ReDefSDicMap;
import com.eis.cache.RedefSDicCodes;
import com.eis.cache.SingleDic;
import com.eis.cache.SingleDicMap;

public class CallfuncconfForm extends BaseForm {
	
	private Collection manufacIdCollection;

	private Collection prodIdcollection;

	private Collection operationTypecollection;
	
	private Collection appTypeIdcollection;
	
	private Collection funcId1collection;
	private Collection funcId2collection;
	private Collection funcId3collection;
	private Collection funcId4collection;
	
    public Collection getManufacIdCollection() {
		return SingleDicMap.getOptionCollection(SingleDic.MAUN_ID);
	}

	public void setManufacIdCollection(Collection manufacIdCollection) {
		this.manufacIdCollection = manufacIdCollection;
	}

	public Collection getProdIdcollection() {
		return SingleDicMap.getOptionCollection(SingleDic.PROD_ID);
	}

	public void setProdIdcollection(Collection prodIdcollection) {
		this.prodIdcollection = prodIdcollection;
	}

	public Collection getOperationTypecollection() {
		return SingleDicMap.getOptionCollection(SingleDic.OPERATIONTYPE);
	}

	public void setOperationTypecollection(Collection operationTypecollection) {
		this.operationTypecollection = operationTypecollection;
	}

	public Collection getAppTypeIdcollection() {
		return ReDefSDicMap.getOptionCollection(RedefSDicCodes.APPTYPEID);

	}

	public void setAppTypeIdcollection(Collection appTypeIdcollection) {
		this.appTypeIdcollection = appTypeIdcollection;
	}

	public Collection getFuncId1collection() {
		return SingleDicMap.getOptionCollection(SingleDic.AUTHKEY);
	}

	public void setFuncId1collection(Collection funcIdcollection) {
		this.funcId1collection = funcIdcollection;
	}
    public Collection getFuncId2collection() {
		return SingleDicMap.getOptionCollection(SingleDic.AUTHKEY);
	}

	public void setFuncId2collection(Collection funcId2collection) {
		this.funcId2collection = funcId2collection;
	}

	public Collection getFuncId3collection() {
		return SingleDicMap.getOptionCollection(SingleDic.AUTHKEY);
	}

	public void setFuncId3collection(Collection funcId3collection) {
		this.funcId3collection = funcId3collection;
	}

	public Collection getFuncId4collection() {
		return SingleDicMap.getOptionCollection(SingleDic.AUTHKEY);
	}

	public void setFuncId4collection(Collection funcId4collection) {
		this.funcId4collection = funcId4collection;
	}
	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column callfuncconf.CallerId
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    private String callerId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column callfuncconf.OperationType
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    private Short operationType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column callfuncconf.ManufacId
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    private String manufacId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column callfuncconf.ProdId
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    private String prodId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column callfuncconf.ApplyTypeId
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    private String applyTypeId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column callfuncconf.func1
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    private String func1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column callfuncconf.func2
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    private String func2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column callfuncconf.func3
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    private String func3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column callfuncconf.func4
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    private String func4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column callfuncconf.OperId
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    private String operId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column callfuncconf.CurrDate
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    private String currDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column callfuncconf.Remarks
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    private String remarks;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column callfuncconf.CallerId
     *
     * @return the value of callfuncconf.CallerId
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public String getCallerId() {
        return callerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column callfuncconf.CallerId
     *
     * @param callerId the value for callfuncconf.CallerId
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public void setCallerId(String callerId) {
        this.callerId = callerId == null ? null : callerId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column callfuncconf.OperationType
     *
     * @return the value of callfuncconf.OperationType
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public Short getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column callfuncconf.OperationType
     *
     * @param operationType the value for callfuncconf.OperationType
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public void setOperationType(Short operationType) {
        this.operationType = operationType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column callfuncconf.ManufacId
     *
     * @return the value of callfuncconf.ManufacId
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public String getManufacId() {
        return manufacId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column callfuncconf.ManufacId
     *
     * @param manufacId the value for callfuncconf.ManufacId
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public void setManufacId(String manufacId) {
        this.manufacId = manufacId == null ? null : manufacId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column callfuncconf.ProdId
     *
     * @return the value of callfuncconf.ProdId
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public String getProdId() {
        return prodId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column callfuncconf.ProdId
     *
     * @param prodId the value for callfuncconf.ProdId
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public void setProdId(String prodId) {
        this.prodId = prodId == null ? null : prodId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column callfuncconf.ApplyTypeId
     *
     * @return the value of callfuncconf.ApplyTypeId
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public String getApplyTypeId() {
        return applyTypeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column callfuncconf.ApplyTypeId
     *
     * @param applyTypeId the value for callfuncconf.ApplyTypeId
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public void setApplyTypeId(String applyTypeId) {
        this.applyTypeId = applyTypeId == null ? null : applyTypeId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column callfuncconf.func1
     *
     * @return the value of callfuncconf.func1
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public String getFunc1() {
        return func1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column callfuncconf.func1
     *
     * @param func1 the value for callfuncconf.func1
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public void setFunc1(String func1) {
        this.func1 = func1 == null ? null : func1.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column callfuncconf.func2
     *
     * @return the value of callfuncconf.func2
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public String getFunc2() {
        return func2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column callfuncconf.func2
     *
     * @param func2 the value for callfuncconf.func2
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public void setFunc2(String func2) {
        this.func2 = func2 == null ? null : func2.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column callfuncconf.func3
     *
     * @return the value of callfuncconf.func3
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public String getFunc3() {
        return func3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column callfuncconf.func3
     *
     * @param func3 the value for callfuncconf.func3
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public void setFunc3(String func3) {
        this.func3 = func3 == null ? null : func3.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column callfuncconf.func4
     *
     * @return the value of callfuncconf.func4
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public String getFunc4() {
        return func4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column callfuncconf.func4
     *
     * @param func4 the value for callfuncconf.func4
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public void setFunc4(String func4) {
        this.func4 = func4 == null ? null : func4.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column callfuncconf.OperId
     *
     * @return the value of callfuncconf.OperId
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column callfuncconf.OperId
     *
     * @param operId the value for callfuncconf.OperId
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column callfuncconf.CurrDate
     *
     * @return the value of callfuncconf.CurrDate
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public String getCurrDate() {
        return currDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column callfuncconf.CurrDate
     *
     * @param currDate the value for callfuncconf.CurrDate
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public void setCurrDate(String currDate) {
        this.currDate = currDate == null ? null : currDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column callfuncconf.Remarks
     *
     * @return the value of callfuncconf.Remarks
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column callfuncconf.Remarks
     *
     * @param remarks the value for callfuncconf.Remarks
     *
     * @ibatorgenerated Thu Jun 16 01:07:54 CST 2016
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

}
