package com.yly.conf;

import com.yly.conf.Moduleconf;
import com.yly.conf.ModuleconfExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ModuleconfDAOImpl extends SqlMapClientDaoSupport implements ModuleconfDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    public ModuleconfDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    public int countByExample(ModuleconfExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("moduleconf.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    public int deleteByExample(ModuleconfExample example) {
        int rows = getSqlMapClientTemplate().delete("moduleconf.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    public int deleteByPrimaryKey(Integer moduleId) {
        Moduleconf key = new Moduleconf();
        key.setModuleId(moduleId);
        int rows = getSqlMapClientTemplate().delete("moduleconf.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    public void insert(Moduleconf record) {
        getSqlMapClientTemplate().insert("moduleconf.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    public void insertSelective(Moduleconf record) {
        getSqlMapClientTemplate().insert("moduleconf.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    public List selectByExample(ModuleconfExample example) {
        List list = getSqlMapClientTemplate().queryForList("moduleconf.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    public Moduleconf selectByPrimaryKey(Integer moduleId) {
        Moduleconf key = new Moduleconf();
        key.setModuleId(moduleId);
        Moduleconf record = (Moduleconf) getSqlMapClientTemplate().queryForObject("moduleconf.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    public int updateByExampleSelective(Moduleconf record, ModuleconfExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("moduleconf.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    public int updateByExample(Moduleconf record, ModuleconfExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("moduleconf.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    public int updateByPrimaryKeySelective(Moduleconf record) {
        int rows = getSqlMapClientTemplate().update("moduleconf.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    public int updateByPrimaryKey(Moduleconf record) {
        int rows = getSqlMapClientTemplate().update("moduleconf.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    private static class UpdateByExampleParms extends ModuleconfExample {
        private Object record;

        public UpdateByExampleParms(Object record, ModuleconfExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}