package com.yly.conf;

import com.yly.conf.Moduleconf;
import com.yly.conf.ModuleconfExample;
import java.util.List;

public interface ModuleconfDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    int countByExample(ModuleconfExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    int deleteByExample(ModuleconfExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    int deleteByPrimaryKey(Integer moduleId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    void insert(Moduleconf record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    void insertSelective(Moduleconf record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    List selectByExample(ModuleconfExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    Moduleconf selectByPrimaryKey(Integer moduleId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    int updateByExampleSelective(Moduleconf record, ModuleconfExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    int updateByExample(Moduleconf record, ModuleconfExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    int updateByPrimaryKeySelective(Moduleconf record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table moduleconf
     *
     * @ibatorgenerated Thu Jul 21 19:38:04 CST 2016
     */
    int updateByPrimaryKey(Moduleconf record);
}