package com.blue.travel;

import com.blue.travel.TravelInfo;
import com.blue.travel.TravelInfoExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TravelInfoDAOImpl extends SqlMapClientDaoSupport implements TravelInfoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table travel_info
     *
     * @ibatorgenerated Thu Apr 17 14:12:42 CST 2014
     */
    public TravelInfoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table travel_info
     *
     * @ibatorgenerated Thu Apr 17 14:12:42 CST 2014
     */
    public int countByExample(TravelInfoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("travel_info.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table travel_info
     *
     * @ibatorgenerated Thu Apr 17 14:12:42 CST 2014
     */
    public int deleteByExample(TravelInfoExample example) {
        int rows = getSqlMapClientTemplate().delete("travel_info.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table travel_info
     *
     * @ibatorgenerated Thu Apr 17 14:12:42 CST 2014
     */
    public int deleteByPrimaryKey(Long expensesId) {
        TravelInfo key = new TravelInfo();
        key.setExpensesId(expensesId);
        int rows = getSqlMapClientTemplate().delete("travel_info.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table travel_info
     *
     * @ibatorgenerated Thu Apr 17 14:12:42 CST 2014
     */
    public void insert(TravelInfo record) {
        getSqlMapClientTemplate().insert("travel_info.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table travel_info
     *
     * @ibatorgenerated Thu Apr 17 14:12:42 CST 2014
     */
    public void insertSelective(TravelInfo record) {
        getSqlMapClientTemplate().insert("travel_info.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table travel_info
     *
     * @ibatorgenerated Thu Apr 17 14:12:42 CST 2014
     */
    public List selectByExample(TravelInfoExample example) {
        List list = getSqlMapClientTemplate().queryForList("travel_info.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table travel_info
     *
     * @ibatorgenerated Thu Apr 17 14:12:42 CST 2014
     */
    public TravelInfo selectByPrimaryKey(Long expensesId) {
        TravelInfo key = new TravelInfo();
        key.setExpensesId(expensesId);
        TravelInfo record = (TravelInfo) getSqlMapClientTemplate().queryForObject("travel_info.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table travel_info
     *
     * @ibatorgenerated Thu Apr 17 14:12:42 CST 2014
     */
    public int updateByExampleSelective(TravelInfo record, TravelInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("travel_info.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table travel_info
     *
     * @ibatorgenerated Thu Apr 17 14:12:42 CST 2014
     */
    public int updateByExample(TravelInfo record, TravelInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("travel_info.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table travel_info
     *
     * @ibatorgenerated Thu Apr 17 14:12:42 CST 2014
     */
    public int updateByPrimaryKeySelective(TravelInfo record) {
        int rows = getSqlMapClientTemplate().update("travel_info.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table travel_info
     *
     * @ibatorgenerated Thu Apr 17 14:12:42 CST 2014
     */
    public int updateByPrimaryKey(TravelInfo record) {
        int rows = getSqlMapClientTemplate().update("travel_info.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table travel_info
     *
     * @ibatorgenerated Thu Apr 17 14:12:42 CST 2014
     */
    private static class UpdateByExampleParms extends TravelInfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, TravelInfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}